(function(){
  'use strict';
  const $=selector=>document.querySelector(selector);
  const STORAGE_KEY='ezpk-lang-v5';
  const SUPPORTED=['en','fr','de','ko','th','ja','pt','es','tr','zh-tw','it','ar','vi','id'];
  let lang=SUPPORTED.includes(localStorage.getItem(STORAGE_KEY))?localStorage.getItem(STORAGE_KEY):'en';
  let authState=null,loaded=false,loading=false,layout=null,currentMemberId=null,selectedId=null;
  let scale=1,panX=0,panY=0,suppressClick=false;
  const ZOOM_STEPS=[.35,.5,.65,.8,1,1.2,1.4,1.7,2,2.3,2.6];
  const pointers=new Map();let dragStart=null,pinchStart=null;

  const T={
    ko:{title:'연맹 배치도',lead:'현재 게시된 최신 연맹 배치도입니다.',placed:'배치 인원',count:n=>`${n}명`,published:'최종 게시',search:'닉네임 검색',find:'내 위치 찾기',findShort:'내 위치',map:'게시 배치도',overview:'전체 배치 현황',overviewHint:'번호로 위치 확인',fullscreen:'전체 화면으로 배치도 보기',gesture:'드래그 이동 · 휠 확대/축소',mobileGesture:'이동 · 확대/축소',close:'배치도 닫기',login:'로그인',gate:'연맹 배치도 🔒',gateLead:'연맹 배치도는 로그인한 연맹원만 확인할 수 있습니다.',guide:'배치 안내',g1:'자신에게 배정된 위치로만 이동해 주세요.',g2:'배치도는 최신으로 등록된 연맹원 스펙을 기준으로 작성되었습니다.',g3:'위치를 변경하려면 해당 연맹원과 상호 협의한 후 진행해 주세요.',g4:'킬데이 및 각종 이벤트 진행 상황에 따라 배치가 일시적으로 변경될 수 있습니다.',g5a:'배치와 관련된 요청사항은 ',g5b:'요청 게시판',g5c:'에 남겨주세요.',loading:'배치도를 불러오는 중입니다.',empty:'아직 게시된 연맹 배치도가 없습니다.',notFound:'일치하는 연맹원을 찾을 수 없습니다.',noMe:'현재 게시된 배치도에서 내 위치를 찾을 수 없습니다.',failed:'배치도를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.',retry:'다시 불러오기',unregistered:'미등록',menu:'메뉴',account:'내 계정',back:'뒤로 가기',selected:'선택된 연맹원',building:(n,name)=>`${name}, 배치 ${n}번`},
    en:{title:'ALLIANCE LAYOUT',lead:'This is the latest published alliance layout.',placed:'PLACED MEMBERS',count:n=>`${n} members`,published:'LAST PUBLISHED',search:'Search nickname',find:'Find my position',findShort:'My position',map:'PUBLISHED LAYOUT',overview:'FULL LAYOUT',overviewHint:'Check positions by number',fullscreen:'View layout full screen',gesture:'Drag to move · Wheel to zoom',mobileGesture:'Move · Pinch to zoom',close:'Close layout',login:'LOG IN',gate:'ALLIANCE LAYOUT 🔒',gateLead:'Only logged-in alliance members can view the alliance layout.',guide:'LAYOUT GUIDE',g1:'Move only to the position assigned to you.',g2:'The layout is based on the latest registered member specifications.',g3:'To change positions, coordinate with the other member first.',g4:'Positions may be changed temporarily during Kill Day or other events.',g5a:'For layout requests, please use the ',g5b:'Request Board',g5c:'.',loading:'Loading the alliance layout.',empty:'No alliance layout has been published yet.',notFound:'No matching member was found.',noMe:'Your position could not be found in the current published layout.',failed:'The layout could not be loaded. Please try again shortly.',retry:'Try again',unregistered:'Not registered',menu:'Menu',account:'My account',back:'Back',selected:'Selected member',building:(n,name)=>`${name}, position ${n}`},
    pt:{title:'MAPA DA ALIANÇA',lead:'Este é o mapa mais recente publicado da aliança.',placed:'MEMBROS POSICIONADOS',count:n=>`${n} membros`,published:'ÚLTIMA PUBLICAÇÃO',search:'Buscar apelido',find:'Encontrar minha posição',findShort:'Minha posição',map:'MAPA PUBLICADO',overview:'MAPA COMPLETO',overviewHint:'Confira as posições pelo número',fullscreen:'Ver mapa em tela cheia',gesture:'Arraste para mover · Roda para ampliar',mobileGesture:'Mover · Pinçar para ampliar',close:'Fechar mapa',login:'ENTRAR',gate:'MAPA DA ALIANÇA 🔒',gateLead:'Somente membros da aliança conectados podem ver o mapa.',guide:'ORIENTAÇÕES DE POSICIONAMENTO',g1:'Mova-se somente para a posição atribuída a você.',g2:'O mapa foi criado com base nas especificações mais recentes registradas.',g3:'Para mudar de posição, combine primeiro com o outro membro.',g4:'As posições podem mudar temporariamente durante o Dia de Abates ou outros eventos.',g5a:'Para solicitações sobre o mapa, use o ',g5b:'Quadro de Pedidos',g5c:'.',loading:'Carregando o mapa da aliança.',empty:'Ainda não há um mapa da aliança publicado.',notFound:'Nenhum membro correspondente foi encontrado.',noMe:'Sua posição não foi encontrada no mapa publicado atual.',failed:'Não foi possível carregar o mapa. Tente novamente em instantes.',retry:'Tentar novamente',unregistered:'Não registrado',menu:'Menu',account:'Minha conta',back:'Voltar',selected:'Membro selecionado',building:(n,name)=>`${name}, posição ${n}`},
    vi:{title:'SƠ ĐỒ LIÊN MINH',lead:'Đây là sơ đồ liên minh mới nhất đã được đăng.',placed:'THÀNH VIÊN ĐÃ XẾP',count:n=>`${n} thành viên`,published:'ĐĂNG LẦN CUỐI',search:'Tìm biệt danh',find:'Tìm vị trí của tôi',findShort:'Vị trí của tôi',map:'SƠ ĐỒ ĐÃ ĐĂNG',overview:'TOÀN BỘ SƠ ĐỒ',overviewHint:'Kiểm tra vị trí theo số',fullscreen:'Xem sơ đồ toàn màn hình',gesture:'Kéo để di chuyển · Cuộn để thu phóng',mobileGesture:'Di chuyển · Chụm để thu phóng',close:'Đóng sơ đồ',login:'ĐĂNG NHẬP',gate:'SƠ ĐỒ LIÊN MINH 🔒',gateLead:'Chỉ thành viên liên minh đã đăng nhập mới có thể xem sơ đồ.',guide:'HƯỚNG DẪN BỐ TRÍ',g1:'Chỉ di chuyển đến vị trí được chỉ định cho bạn.',g2:'Sơ đồ được lập dựa trên thông số thành viên mới nhất đã đăng ký.',g3:'Nếu muốn đổi vị trí, hãy thỏa thuận trước với thành viên liên quan.',g4:'Vị trí có thể tạm thời thay đổi trong Ngày Tiêu Diệt hoặc các sự kiện khác.',g5a:'Nếu có yêu cầu về bố trí, hãy gửi tại ',g5b:'Bảng Yêu Cầu',g5c:'.',loading:'Đang tải sơ đồ liên minh.',empty:'Chưa có sơ đồ liên minh nào được đăng.',notFound:'Không tìm thấy thành viên phù hợp.',noMe:'Không tìm thấy vị trí của bạn trong sơ đồ hiện tại.',failed:'Không thể tải sơ đồ. Vui lòng thử lại sau.',retry:'Tải lại',unregistered:'Chưa đăng ký',menu:'Menu',account:'Tài khoản của tôi',back:'Quay lại',selected:'Thành viên đã chọn',building:(n,name)=>`${name}, vị trí ${n}`},
    ar:{title:'مخطط التحالف',lead:'هذا هو أحدث مخطط منشور للتحالف.',placed:'الأعضاء الموزعون',count:n=>`${n} عضو`,published:'آخر نشر',search:'البحث بالاسم',find:'العثور على موقعي',findShort:'موقعي',map:'المخطط المنشور',overview:'المخطط الكامل',overviewHint:'تحقق من المواقع حسب الرقم',fullscreen:'عرض المخطط بملء الشاشة',gesture:'اسحب للتحريك · استخدم العجلة للتكبير',mobileGesture:'حرّك · قرّب بإصبعين',close:'إغلاق المخطط',login:'تسجيل الدخول',gate:'مخطط التحالف 🔒',gateLead:'يمكن فقط لأعضاء التحالف المسجلين الدخول عرض المخطط.',guide:'إرشادات التوزيع',g1:'انتقل فقط إلى الموقع المخصص لك.',g2:'تم إعداد المخطط بناءً على أحدث مواصفات الأعضاء المسجلة.',g3:'لتغيير الموقع، اتفق أولاً مع العضو المعني.',g4:'قد تتغير المواقع مؤقتًا خلال يوم القتل أو الفعاليات الأخرى.',g5a:'لطلبات التوزيع، استخدم ',g5b:'لوحة الطلبات',g5c:'.',loading:'جارٍ تحميل مخطط التحالف.',empty:'لم يتم نشر مخطط للتحالف بعد.',notFound:'لم يتم العثور على عضو مطابق.',noMe:'تعذر العثور على موقعك في المخطط المنشور الحالي.',failed:'تعذر تحميل المخطط. يرجى المحاولة بعد قليل.',retry:'إعادة المحاولة',unregistered:'غير مسجل',menu:'القائمة',account:'حسابي',back:'رجوع',selected:'العضو المحدد',building:(n,name)=>`${name}، الموقع ${n}`},
    ja:{title:'同盟配置図',lead:'現在公開されている最新の同盟配置図です。',placed:'配置人数',count:n=>`${n}名`,published:'最終公開',search:'ニックネーム検索',find:'自分の位置を探す',findShort:'自分の位置',map:'公開配置図',overview:'配置図全体',overviewHint:'番号で位置を確認',fullscreen:'全画面で配置図を見る',gesture:'ドラッグで移動・ホイールで拡大縮小',mobileGesture:'移動・ピンチで拡大縮小',close:'配置図を閉じる',login:'ログイン',gate:'同盟配置図 🔒',gateLead:'ログイン中の同盟メンバーのみ配置図を確認できます。',guide:'配置案内',g1:'自分に割り当てられた位置にのみ移動してください。',g2:'配置図は登録された最新のメンバー情報を基準に作成されています。',g3:'位置を変更する場合は、該当メンバーと相談してから行ってください。',g4:'キルデイや各種イベントの状況により、一時的に配置が変更される場合があります。',g5a:'配置に関する要望は',g5b:'リクエスト掲示板',g5c:'に残してください。',loading:'同盟配置図を読み込んでいます。',empty:'まだ公開された同盟配置図はありません。',notFound:'一致するメンバーが見つかりません。',noMe:'現在の公開配置図に自分の位置がありません。',failed:'配置図を読み込めませんでした。しばらくしてからもう一度お試しください。',retry:'再読み込み',unregistered:'未登録',menu:'メニュー',account:'マイアカウント',back:'戻る',selected:'選択中のメンバー',building:(n,name)=>`${name}、配置${n}番`},
    th:{title:'ผังพันธมิตร',lead:'นี่คือผังพันธมิตรล่าสุดที่เผยแพร่',placed:'สมาชิกที่จัดวาง',count:n=>`${n} คน`,published:'เผยแพร่ล่าสุด',search:'ค้นหาชื่อเล่น',find:'ค้นหาตำแหน่งของฉัน',findShort:'ตำแหน่งของฉัน',map:'ผังที่เผยแพร่',overview:'ผังทั้งหมด',overviewHint:'ตรวจสอบตำแหน่งตามหมายเลข',fullscreen:'ดูผังแบบเต็มหน้าจอ',gesture:'ลากเพื่อเลื่อน · ใช้ล้อเพื่อซูม',mobileGesture:'เลื่อน · บีบนิ้วเพื่อซูม',close:'ปิดผัง',login:'เข้าสู่ระบบ',gate:'ผังพันธมิตร 🔒',gateLead:'เฉพาะสมาชิกพันธมิตรที่เข้าสู่ระบบแล้วเท่านั้นที่ดูผังได้',guide:'คำแนะนำการจัดวาง',g1:'โปรดย้ายไปยังตำแหน่งที่กำหนดให้คุณเท่านั้น',g2:'ผังนี้จัดทำจากข้อมูลสเปกล่าสุดที่สมาชิกลงทะเบียนไว้',g3:'หากต้องการเปลี่ยนตำแหน่ง โปรดตกลงกับสมาชิกที่เกี่ยวข้องก่อน',g4:'ตำแหน่งอาจเปลี่ยนชั่วคราวในวันสังหารหรือกิจกรรมต่าง ๆ',g5a:'หากมีคำขอเกี่ยวกับการจัดวาง โปรดฝากไว้ที่',g5b:'กระดานคำขอ',g5c:'',loading:'กำลังโหลดผังพันธมิตร',empty:'ยังไม่มีผังพันธมิตรที่เผยแพร่',notFound:'ไม่พบสมาชิกที่ตรงกัน',noMe:'ไม่พบตำแหน่งของคุณในผังที่เผยแพร่ปัจจุบัน',failed:'ไม่สามารถโหลดผังได้ โปรดลองอีกครั้งในภายหลัง',retry:'โหลดอีกครั้ง',unregistered:'ยังไม่ลงทะเบียน',menu:'เมนู',account:'บัญชีของฉัน',back:'ย้อนกลับ',selected:'สมาชิกที่เลือก',building:(n,name)=>`${name} ตำแหน่ง ${n}`},
    'zh-tw':{title:'聯盟配置圖',lead:'這是目前已發布的最新聯盟配置圖。',placed:'配置人數',count:n=>`${n}人`,published:'最後發布',search:'搜尋暱稱',find:'尋找我的位置',findShort:'我的位置',map:'已發布配置圖',overview:'完整配置圖',overviewHint:'依編號確認位置',fullscreen:'全螢幕查看配置圖',gesture:'拖曳移動・滾輪縮放',mobileGesture:'移動・雙指縮放',close:'關閉配置圖',login:'登入',gate:'聯盟配置圖 🔒',gateLead:'只有已登入的聯盟成員才能查看配置圖。',guide:'配置說明',g1:'請只移動到分配給您的位置。',g2:'配置圖依據成員最新登記的規格資料製作。',g3:'如需更換位置，請先與相關成員協商。',g4:'擊殺日或其他活動期間，配置可能會暫時調整。',g5a:'如有配置相關需求，請前往',g5b:'留言板',g5c:'提出。',loading:'正在載入聯盟配置圖。',empty:'目前尚未發布聯盟配置圖。',notFound:'找不到符合的成員。',noMe:'目前發布的配置圖中找不到您的位置。',failed:'無法載入配置圖，請稍後再試。',retry:'重新載入',unregistered:'未登記',menu:'選單',account:'我的帳號',back:'返回',selected:'已選擇的成員',building:(n,name)=>`${name}，配置第${n}位`}
  };
window.EZPK_I18N_V414?.apply('allianceLayout',T);
const ALLIANCE_DYNAMIC_414={
fr:{count:n=>`${n} membres`,building:(n,name)=>`${name}, position ${n}`},
de:{count:n=>`${n} Mitglieder`,building:(n,name)=>`${name}, Position ${n}`},
es:{count:n=>`${n} miembros`,building:(n,name)=>`${name}, posición ${n}`},
tr:{count:n=>`${n} üye`,building:(n,name)=>`${name}, konum ${n}`},
it:{count:n=>`${n} membri`,building:(n,name)=>`${name}, posizione ${n}`},
id:{count:n=>`${n} anggota`,building:(n,name)=>`${name}, posisi ${n}`}
};
for(const [code,copy] of Object.entries(ALLIANCE_DYNAMIC_414))Object.assign(T[code],copy);

  const ZOOM_T={
    ko:{out:'축소',in:'확대',reset:'원래대로',controls:'배치도 확대 및 축소'},en:{out:'Zoom out',in:'Zoom in',reset:'Reset',controls:'Layout zoom controls'},pt:{out:'Reduzir',in:'Ampliar',reset:'Restaurar',controls:'Controles de zoom do mapa'},vi:{out:'Thu nhỏ',in:'Phóng to',reset:'Đặt lại',controls:'Điều khiển thu phóng sơ đồ'},ar:{out:'تصغير',in:'تكبير',reset:'إعادة',controls:'عناصر تكبير المخطط'},ja:{out:'縮小',in:'拡大',reset:'元に戻す',controls:'配置図の拡大縮小'},th:{out:'ย่อ',in:'ขยาย',reset:'คืนค่า',controls:'การซูมผัง'},'zh-tw':{out:'縮小',in:'放大',reset:'還原',controls:'配置圖縮放控制'}
  };
Object.assign(ZOOM_T,{
  fr:{out:'Réduire',in:'Agrandir',reset:'Réinitialiser',controls:'Commandes de zoom du plan'},
  de:{out:'Verkleinern',in:'Vergrößern',reset:'Zurücksetzen',controls:'Zoom-Steuerung des Allianzplans'},
  es:{out:'Alejar',in:'Acercar',reset:'Restablecer',controls:'Controles de zoom del plano'},
  tr:{out:'Uzaklaştır',in:'Yakınlaştır',reset:'Sıfırla',controls:'Yerleşim yakınlaştırma kontrolleri'},
  it:{out:'Riduci',in:'Ingrandisci',reset:'Reimposta',controls:'Controlli zoom della disposizione'},
  id:{out:'Perkecil',in:'Perbesar',reset:'Atur ulang',controls:'Kontrol zoom tata letak'}
});

  const IMAGE_T={
    ko:{view:'배치도 다운로드',title:'배치도 이미지',pc:'이미지를 마우스 오른쪽 버튼으로 클릭해 저장하세요.',mobile:'이미지를 길게 눌러 저장하세요.',loading:'배치도 이미지를 만드는 중입니다.',alt:'저장용 연맹 배치도 이미지',close:'닫기'},
    en:{view:'Download layout',title:'Layout image',pc:'Right-click the image to save it.',mobile:'Press and hold the image to save it.',loading:'Creating the layout image.',alt:'Alliance layout image for saving',close:'Close'},
    pt:{view:'Baixar mapa',title:'Imagem do mapa',pc:'Clique com o botão direito na imagem para salvá-la.',mobile:'Pressione e segure a imagem para salvá-la.',loading:'Criando a imagem do mapa.',alt:'Imagem do mapa da aliança para salvar',close:'Fechar'},
    vi:{view:'Tải sơ đồ',title:'Ảnh sơ đồ',pc:'Nhấp chuột phải vào ảnh để lưu.',mobile:'Nhấn và giữ ảnh để lưu.',loading:'Đang tạo ảnh sơ đồ.',alt:'Ảnh sơ đồ liên minh để lưu',close:'Đóng'},
    ar:{view:'تنزيل المخطط',title:'صورة المخطط',pc:'انقر بزر الفأرة الأيمن على الصورة لحفظها.',mobile:'اضغط مطولاً على الصورة لحفظها.',loading:'جارٍ إنشاء صورة المخطط.',alt:'صورة مخطط التحالف للحفظ',close:'إغلاق'},
    ja:{view:'配置図をダウンロード',title:'配置図画像',pc:'画像を右クリックして保存してください。',mobile:'画像を長押しして保存してください。',loading:'配置図画像を作成しています。',alt:'保存用の同盟配置図画像',close:'閉じる'},
    th:{view:'ดาวน์โหลดผัง',title:'รูปผัง',pc:'คลิกขวาที่รูปเพื่อบันทึก',mobile:'แตะรูปค้างไว้เพื่อบันทึก',loading:'กำลังสร้างรูปผัง',alt:'รูปผังพันธมิตรสำหรับบันทึก',close:'ปิด'},
    'zh-tw':{view:'下載配置圖',title:'配置圖圖片',pc:'在圖片上按滑鼠右鍵即可儲存。',mobile:'長按圖片即可儲存。',loading:'正在建立配置圖圖片。',alt:'可儲存的聯盟配置圖圖片',close:'關閉'}
  };
Object.assign(IMAGE_T,{
  fr:{view:'Télécharger le plan',title:'Image du plan',pc:'Faites un clic droit sur l’image pour l’enregistrer.',mobile:'Appuyez longuement sur l’image pour l’enregistrer.',loading:'Création de l’image du plan.',alt:'Image du plan de l’alliance à enregistrer',close:'Fermer'},
  de:{view:'Plan herunterladen',title:'Planbild',pc:'Klicke mit der rechten Maustaste auf das Bild, um es zu speichern.',mobile:'Halte das Bild gedrückt, um es zu speichern.',loading:'Planbild wird erstellt.',alt:'Allianzplan zum Speichern',close:'Schließen'},
  es:{view:'Descargar plano',title:'Imagen del plano',pc:'Haz clic derecho en la imagen para guardarla.',mobile:'Mantén pulsada la imagen para guardarla.',loading:'Creando la imagen del plano.',alt:'Imagen del plano de la alianza para guardar',close:'Cerrar'},
  tr:{view:'Yerleşimi indir',title:'Yerleşim görseli',pc:'Kaydetmek için görsele sağ tıklayın.',mobile:'Kaydetmek için görsele basılı tutun.',loading:'Yerleşim görseli oluşturuluyor.',alt:'Kaydetmek için ittifak yerleşim görseli',close:'Kapat'},
  it:{view:'Scarica disposizione',title:'Immagine disposizione',pc:'Fai clic con il tasto destro sull’immagine per salvarla.',mobile:'Tieni premuta l’immagine per salvarla.',loading:'Creazione dell’immagine della disposizione.',alt:'Immagine della disposizione dell’alleanza da salvare',close:'Chiudi'},
  id:{view:'Unduh tata letak',title:'Gambar tata letak',pc:'Klik kanan gambar untuk menyimpannya.',mobile:'Tekan dan tahan gambar untuk menyimpannya.',loading:'Membuat gambar tata letak.',alt:'Gambar tata letak aliansi untuk disimpan',close:'Tutup'}
});

  const tx=()=>T[lang]||T.en;
  const frame=direction=>direction==='top'?{rs:3,re:4,cs:4,ce:7}:direction==='bottom'?{rs:5,re:6,cs:4,ce:7}:direction==='left'?{rs:4,re:5,cs:3,ce:6}:{rs:4,re:5,cs:4,ce:7};

  function esc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function applyText(){
    const t=tx();document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';
    $('#pageTitle').textContent=t.title;$('#pageLead').textContent=t.lead;$('#placedLabel').textContent=t.placed;$('#publishedLabel').textContent=t.published;
    $('#overviewTitle').textContent=t.overview;$('#overviewHint').textContent=t.overviewHint;$('#openFullscreen').textContent=t.fullscreen;
    $('#mapTitle').textContent=t.map;$('#mapGestureHint').textContent=matchMedia('(max-width:700px)').matches?t.mobileGesture:t.gesture;
    $('#memberSearch').placeholder=t.search;$('#memberSearch').setAttribute('aria-label',t.search);$('#findMe').textContent=matchMedia('(max-width:700px)').matches?`◎ ${t.findShort}`:`◎ ${t.find}`;
    $('#closeFullscreen').setAttribute('aria-label',t.close);$('#gateTitle').textContent=t.gate;$('#gateLead').textContent=t.gateLead;$('#gateLogin').textContent=t.login;
    const z=ZOOM_T[lang]||ZOOM_T.en;document.querySelectorAll('[data-zoom-label="out"]').forEach(el=>el.textContent=z.out);document.querySelectorAll('[data-zoom-label="in"]').forEach(el=>el.textContent=z.in);document.querySelectorAll('[data-zoom-label="reset"]').forEach(el=>el.textContent=z.reset);document.querySelectorAll('[data-layout-zoom="out"]').forEach(el=>el.setAttribute('aria-label',z.out));document.querySelectorAll('[data-layout-zoom="in"]').forEach(el=>el.setAttribute('aria-label',z.in));document.querySelectorAll('[data-layout-zoom="reset"]').forEach(el=>el.setAttribute('aria-label',z.reset));document.querySelectorAll('.desktop-layout-zoom,.mobile-layout-zoom').forEach(el=>el.setAttribute('aria-label',z.controls));
    const imageText=IMAGE_T[lang]||IMAGE_T.en;document.querySelectorAll('[data-layout-image]').forEach(el=>el.textContent=imageText.view);$('#layoutImageTitle').textContent=imageText.title;$('#layoutImageGuide').textContent=matchMedia('(max-width:700px)').matches?imageText.mobile:imageText.pc;$('#layoutImagePreview').alt=imageText.alt;$('#layoutImageClose').setAttribute('aria-label',imageText.close);
    $('#guideTitle').textContent=t.guide;$('#guide1').textContent=t.g1;$('#guide2').textContent=t.g2;$('#guide3').textContent=t.g3;$('#guide4').textContent=t.g4;
    $('#guide5').innerHTML=`${esc(t.g5a)}<a href="../request/">${esc(t.g5b)}</a>${esc(t.g5c)}`;
    if(layout){renderMeta();renderMaps();if(selectedId)selectMember(selectedId,false);}
  }
  function formatDate(value){if(!value)return '—';try{return new Intl.DateTimeFormat(lang==='zh-tw'?'zh-TW':lang,{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));}catch(_){return String(value).slice(0,10);}}
  function renderMeta(){const count=layout?.positions?.length||0;$('#placedCount').textContent=tx().count(count);$('#publishedDate').textContent=formatDate(layout?.publishedAt);$('#fullscreenCount').textContent=String(count);}
  function roundedRect(ctx,x,y,width,height,radius){const r=Math.min(radius,width/2,height/2);ctx.beginPath();ctx.roundRect(x,y,width,height,r);}
  function fitNicknameFont(ctx,nickname,maxWidth,startSize){let size=startSize;ctx.font=`800 ${size}px Arial, sans-serif`;const measured=ctx.measureText(nickname).width;if(measured>maxWidth)size=Math.max(1,size*(maxWidth/measured));return size;}
  function drawLayoutImage(){const canvas=document.createElement('canvas'),size=2048,ctx=canvas.getContext('2d'),direction=layout?.direction||'right',positions=layout?.positions||[],f=frame(direction);canvas.width=size;canvas.height=size;ctx.fillStyle='#070b11';ctx.fillRect(0,0,size,size);ctx.textBaseline='middle';ctx.fillStyle='#f4f7fb';ctx.textAlign='left';ctx.font='900 72px Arial, sans-serif';ctx.fillText(tx().title,112,126);ctx.fillStyle='#9eacbd';ctx.font='500 30px Arial, sans-serif';ctx.fillText(`${tx().published} · ${formatDate(layout?.publishedAt)}`,112,198);
    const left=112,top=326,mapWidth=1824,gap=10,cellWidth=(mapWidth-gap*10)/11,cellHeight=119,mapHeight=cellHeight*10+gap*9;ctx.fillStyle='#0c121c';roundedRect(ctx,left-22,top-22,mapWidth+44,mapHeight+44,26);ctx.fill();
    const byCoord=new Map(positions.map(item=>[`${item.row}-${item.col}`,item])),slotKeys=new Set((layout?.slots||[]).map(item=>`${item.row}-${item.col}`));for(let row=0;row<10;row++)for(let col=0;col<11;col++){if(!slotKeys.has(`${row}-${col}`))continue;const x=left+col*(cellWidth+gap),y=top+row*(cellHeight+gap),item=byCoord.get(`${row}-${col}`);ctx.fillStyle=item?'#16263a':'#0d141e';ctx.strokeStyle=item?'#486584':'#1b2735';ctx.lineWidth=2;roundedRect(ctx,x,y,cellWidth,cellHeight,14);ctx.fill();ctx.stroke();if(item){const nickname=String(item.nickname||'');ctx.fillStyle='#f4f7fb';ctx.textAlign='center';const fontSize=fitNicknameFont(ctx,nickname,cellWidth*.9,29);ctx.font=`800 ${fontSize}px Arial, sans-serif`;ctx.fillText(nickname,x+cellWidth/2,y+cellHeight/2);}}
    const fx=left+f.cs*(cellWidth+gap),fy=top+f.rs*(cellHeight+gap),fw=cellWidth*(f.ce-f.cs+1)+gap*(f.ce-f.cs),fh=cellHeight*(f.re-f.rs+1)+gap*(f.re-f.rs);ctx.fillStyle='#9b7b38';ctx.strokeStyle='#f0cf80';ctx.lineWidth=4;roundedRect(ctx,fx,fy,fw,fh,20);ctx.fill();ctx.stroke();ctx.fillStyle='#140f06';ctx.textAlign='center';ctx.font='900 48px Arial, sans-serif';ctx.fillText('Frankie',fx+fw/2,fy+fh/2);
    ctx.fillStyle='#dce4ee';ctx.textAlign='left';ctx.font='600 30px Arial, sans-serif';ctx.fillText(tx().g1,112,1818);ctx.fillStyle='#d8b76a';ctx.textAlign='right';ctx.font='800 32px Arial, sans-serif';ctx.fillText('ezpk322.com',1936,1904);return canvas;}
  function openLayoutImage(){if(!layout)return;const dialog=$('#layoutImageDialog'),state=$('#layoutImageState'),image=$('#layoutImagePreview'),imageText=IMAGE_T[lang]||IMAGE_T.en;state.textContent=imageText.loading;image.removeAttribute('src');dialog.showModal();requestAnimationFrame(()=>{try{const canvas=drawLayoutImage();image.src=canvas.toDataURL('image/png');state.textContent='';}catch(error){state.textContent=tx().failed;}});}
  function buildingHtml(item,mini=false){return `<button type="button" class="layout-member" data-member-id="${item.memberId}" style="grid-row:${item.row+1};grid-column:${item.col+1}" aria-label="${esc(tx().building(item.rank,item.nickname))}"><span class="rank">${String(item.rank).padStart(2,'0')}</span><span class="nickname">${esc(item.nickname)}</span></button>`;}
  function emptyBuildingHtml(item){return `<span class="layout-member layout-empty" style="grid-row:${item.row+1};grid-column:${item.col+1}" aria-hidden="true"><span class="empty-label">EMPTY</span></span>`;}
  function frankieHtml(direction){const f=frame(direction);return `<div class="layout-frankie" style="grid-row:${f.rs+1}/${f.re+2};grid-column:${f.cs+1}/${f.ce+2}">Frankie</div>`;}
  function renderMaps(){if(!layout)return;const occupied=new Set(layout.positions.map(p=>`${p.row}-${p.col}`)),empties=(layout.slots||[]).filter(s=>!occupied.has(`${s.row}-${s.col}`)).map(emptyBuildingHtml).join(''),cells=layout.positions.map(p=>buildingHtml(p)).join('')+empties+frankieHtml(layout.direction);$('#layoutMap').innerHTML=cells;$('#miniLayoutMap').innerHTML=cells;bindMemberButtons();requestAnimationFrame(fitMap);}
  function bindMemberButtons(){document.querySelectorAll('.layout-member[data-member-id]').forEach(button=>button.addEventListener('click',event=>{if(suppressClick){event.preventDefault();return;}selectMember(Number(button.dataset.memberId),false);}));}
  function spec(value,type){if(value===null||value===undefined||String(value).trim()==='')return tx().unregistered;if(type==='ind'){const hit=String(value).match(/[0-9]+(?:\.[0-9]+)?/);return hit?hit[0]:String(value);}const raw=String(value).trim(),unit=raw.match(/^([0-9][0-9,.]*)\s*([MG])$/i);let numeric;if(unit){numeric=Number(unit[1].replace(/,/g,''))*(unit[2].toUpperCase()==='G'?1e9:1e6);}else if(/^[0-9][0-9,.]*$/.test(raw)){numeric=Number(raw.replace(/,/g,''));}if(Number.isFinite(numeric))return new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(Math.round(numeric));return raw;}
  function selectMember(id,move=true){const item=layout?.positions?.find(p=>Number(p.memberId)===Number(id));if(!item)return;selectedId=Number(id);document.querySelectorAll('.layout-member').forEach(el=>el.classList.toggle('is-selected',Number(el.dataset.memberId)===selectedId));$('#memberDetail').hidden=false;$('#detailNickname').textContent=item.nickname;$('#detailCp').textContent=spec(item.power,'cp');$('#detailInd').textContent=spec(item.industryLevel,'ind');$('#memberDetail').setAttribute('aria-label',`${tx().selected}: ${item.nickname}`);if(move)focusMember(item);}
  function showState(message,retry=false){$('#layoutState').innerHTML=retry?`${esc(message)} <button id="retryLayout" type="button">${esc(tx().retry)}</button>`:esc(message);$('#layoutContent').hidden=true;if(retry)$('#retryLayout').onclick=()=>loadLayout(true);}
  function clearState(){$('#layoutState').textContent='';$('#layoutContent').hidden=false;}
  async function api(path){const response=await fetch(path,{credentials:'include',headers:{accept:'application/json'},cache:'no-store'});let payload={};try{payload=await response.json();}catch(_){throw new Error('INVALID_RESPONSE');}if(!response.ok||payload.ok===false)throw new Error(payload.error||payload.code||'REQUEST_FAILED');return payload.data;}
  async function loadLayout(force=false){if(loading||loaded&&!force)return;loading=true;showState(tx().loading);try{const data=await api('/api/alliance-layout');layout=data.layout;currentMemberId=Number(data.currentMemberId||0);loaded=true;if(!layout){showState(tx().empty);return;}clearState();renderMeta();renderMaps();if(matchMedia('(max-width:700px)').matches)$('#layoutGuide').open=false;}catch(error){if(String(error.message).includes('UNAUTHORIZED')){applyAccess({authenticated:false,member:null});return;}showState(tx().failed,true);}finally{loading=false;}}
  function applyAccess(state){const previousId=Number(authState?.member?.id||0),nextId=Number(state?.member?.id||0);authState=state;const allowed=Boolean(state?.authenticated&&state?.member?.status==='active');$('#allianceLayoutGate').hidden=allowed;$('#allianceLayoutProtected').hidden=!allowed;if(!allowed){loaded=false;layout=null;currentMemberId=null;selectedId=null;closeFullscreen();return;}loadLayout(previousId>0&&previousId!==nextId);}

  function clampPan(){const viewport=$('#mapViewport'),stage=$('#mapStage');if(!viewport||!stage)return;const width=stage.offsetWidth*scale,height=stage.offsetHeight*scale,vw=viewport.clientWidth,vh=viewport.clientHeight;const minX=Math.min(12,vw-width-12),maxX=Math.max(12,(vw-width)/2),minY=Math.min(12,vh-height-12),maxY=Math.max(12,(vh-height)/2);panX=Math.max(minX,Math.min(maxX,panX));panY=Math.max(minY,Math.min(maxY,panY));}
  function paintMap(){clampPan();$('#mapStage').style.transform=`translate(${panX}px,${panY}px) scale(${scale})`;document.querySelectorAll('[data-layout-zoom-value]').forEach(el=>el.textContent=`${Math.round(scale*100)}%`);document.querySelectorAll('[data-layout-zoom="out"]').forEach(el=>el.disabled=scale<=.3501);document.querySelectorAll('[data-layout-zoom="in"]').forEach(el=>el.disabled=scale>=2.599);}
  function fitMap(){const viewport=$('#mapViewport'),stage=$('#mapStage');if(!viewport||!stage||viewport.clientWidth===0)return;scale=Math.min(1,(viewport.clientWidth-24)/stage.offsetWidth,(viewport.clientHeight-24)/stage.offsetHeight);panX=(viewport.clientWidth-stage.offsetWidth*scale)/2;panY=(viewport.clientHeight-stage.offsetHeight*scale)/2;paintMap();}
  function focusMember(item){const viewport=$('#mapViewport');const x=12+item.col*78+36,y=12+item.row*64+29;panX=viewport.clientWidth/2-x*scale;panY=viewport.clientHeight/2-y*scale;paintMap();}
  function zoomAt(nextScale,x,y){const old=scale;scale=Math.max(.35,Math.min(2.6,nextScale));panX=x-(x-panX)*(scale/old);panY=y-(y-panY)*(scale/old);paintMap();}
  function zoomStep(direction,x,y){const epsilon=.001,next=direction>0?ZOOM_STEPS.find(value=>value>scale+epsilon):[...ZOOM_STEPS].reverse().find(value=>value<scale-epsilon);zoomAt(next??(direction>0?ZOOM_STEPS.at(-1):ZOOM_STEPS[0]),x,y);}
  function setupMapControls(){const viewport=$('#mapViewport');let wheelLocked=false,wheelUnlockTimer=0;viewport.addEventListener('wheel',event=>{event.preventDefault();clearTimeout(wheelUnlockTimer);if(!wheelLocked){wheelLocked=true;const rect=viewport.getBoundingClientRect();zoomStep(event.deltaY<0?1:-1,event.clientX-rect.left,event.clientY-rect.top);}wheelUnlockTimer=setTimeout(()=>{wheelLocked=false},160);},{passive:false});
    viewport.addEventListener('pointerdown',event=>{pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});suppressClick=false;if(pointers.size===1)dragStart={x:event.clientX,y:event.clientY,panX,panY};if(pointers.size===2){const pts=[...pointers.values()];pinchStart={distance:Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y),scale};}viewport.classList.add('is-panning');});
    viewport.addEventListener('pointermove',event=>{if(!pointers.has(event.pointerId))return;pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(pointers.size===2&&pinchStart){try{if(!viewport.hasPointerCapture(event.pointerId))viewport.setPointerCapture(event.pointerId)}catch(_){}const pts=[...pointers.values()],distance=Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y),rect=viewport.getBoundingClientRect(),cx=(pts[0].x+pts[1].x)/2-rect.left,cy=(pts[0].y+pts[1].y)/2-rect.top;zoomAt(pinchStart.scale*(distance/pinchStart.distance),cx,cy);suppressClick=true;}else if(pointers.size===1&&dragStart){const dx=event.clientX-dragStart.x,dy=event.clientY-dragStart.y;if(Math.abs(dx)+Math.abs(dy)>5){suppressClick=true;try{if(!viewport.hasPointerCapture(event.pointerId))viewport.setPointerCapture(event.pointerId)}catch(_){}}panX=dragStart.panX+dx;panY=dragStart.panY+dy;paintMap();}});
    const end=event=>{pointers.delete(event.pointerId);if(pointers.size<2)pinchStart=null;if(pointers.size===1){const p=[...pointers.values()][0];dragStart={x:p.x,y:p.y,panX,panY};}else dragStart=null;viewport.classList.toggle('is-panning',pointers.size>0);setTimeout(()=>{suppressClick=false;},0);};viewport.addEventListener('pointerup',end);viewport.addEventListener('pointercancel',end);
    viewport.addEventListener('click',event=>{if(suppressClick)return;if(event.target===viewport||event.target.id==='mapStage'||event.target.id==='layoutMap'){$('#memberDetail').hidden=true;selectedId=null;document.querySelectorAll('.layout-member').forEach(el=>el.classList.remove('is-selected'));}});document.querySelectorAll('[data-layout-zoom]').forEach(button=>button.addEventListener('click',()=>{const action=button.dataset.layoutZoom;if(action==='reset'){fitMap();return}const viewportRect=viewport.getBoundingClientRect();zoomStep(action==='in'?1:-1,viewportRect.width/2,viewportRect.height/2);}));
  }
  function renderSearch(){const box=$('#searchResults'),query=$('#memberSearch').value.trim().toLocaleLowerCase(lang);if(!query){box.hidden=true;box.innerHTML='';return;}const matches=(layout?.positions||[]).filter(p=>p.nickname.toLocaleLowerCase(lang).includes(query)).slice(0,6);box.hidden=false;box.innerHTML=matches.length?matches.map(p=>`<button type="button" data-search-id="${p.memberId}">${esc(p.nickname)}</button>`).join(''):`<p>${esc(tx().notFound)}</p>`;box.querySelectorAll('button').forEach(button=>button.onclick=()=>{selectMember(Number(button.dataset.searchId),true);box.hidden=true;});}
  function openFullscreen(){$('#layoutExplorer').classList.add('is-fullscreen');document.body.classList.add('layout-fullscreen');requestAnimationFrame(fitMap);}
  function closeFullscreen(){$('#layoutExplorer').classList.remove('is-fullscreen');document.body.classList.remove('layout-fullscreen');requestAnimationFrame(fitMap);}

  document.addEventListener('DOMContentLoaded',()=>{applyText();setupMapControls();$('#allianceLayoutGate').hidden=true;$('#allianceLayoutProtected').hidden=true;$('#gateLogin').onclick=()=>window.EZPKMemberAuth?.openLogin();$('#memberSearch').addEventListener('input',renderSearch);$('#findMe').onclick=()=>{const item=layout?.positions?.find(p=>Number(p.memberId)===currentMemberId);if(item)selectMember(item.memberId,true);else showTransient(tx().noMe);};$('#openFullscreen').onclick=openFullscreen;$('#closeFullscreen').onclick=closeFullscreen;document.querySelectorAll('[data-layout-image]').forEach(button=>button.onclick=openLayoutImage);$('#layoutImageClose').onclick=()=>$('#layoutImageDialog').close();$('#layoutImageDialog').addEventListener('click',event=>{if(event.target===$('#layoutImageDialog'))$('#layoutImageDialog').close();});addEventListener('resize',()=>{applyText();if(layout)requestAnimationFrame(fitMap);});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&$('#layoutExplorer').classList.contains('is-fullscreen'))closeFullscreen();});const state=window.EZPKMemberAuth?.getState?.();if(state?.loaded)applyAccess(state);});
  function showTransient(message){const box=$('#searchResults');box.hidden=false;box.innerHTML=`<p>${esc(message)}</p>`;setTimeout(()=>{box.hidden=true;},2600);}
  window.addEventListener('ezpk-auth-ready',event=>applyAccess(event.detail));window.addEventListener('ezpk-auth-change',event=>applyAccess(event.detail));window.addEventListener('ezpk-language-change',event=>{lang=SUPPORTED.includes(event.detail?.lang)?event.detail.lang:(SUPPORTED.includes(localStorage.getItem(STORAGE_KEY))?localStorage.getItem(STORAGE_KEY):'en');applyText();renderSearch();});
})();
