const D=window.EZPK_DATA;let lang=localStorage.getItem('ezpk-lang-v5')||'en';if(!D[lang])lang='en';const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const cfg=window.EZPK_SUPABASE_CONFIG||{};let page=0;const PAGE_SIZE=20;
const T={
ko:{title:'요청 게시판',lead:'연맹 운영진에게 요청사항이나 질문을 남겨주세요.',new:'NEW REQUEST',write:'요청 작성',nickname:'닉네임',password:'삭제 비밀번호 (숫자 4자리)',message:'내용',help:'본인 확인용 비밀번호를 기억해 주세요.',submit:'등록하기',recent:'RECENT REQUESTS',list:'최근 요청',empty:'등록된 요청이 없습니다.',loading:'불러오는 중...',waiting:'답변 대기',answered:'답변 완료',admin:'관리자 답변',success:'요청이 등록되었습니다.',fail:'요청을 등록하지 못했습니다.',config:'Supabase Publishable Key가 설정되지 않았습니다.',more:'더 보기',footer:'요청과 질문을 남겨주세요.'},
en:{title:'REQUEST BOARD',lead:'Leave a request or question for the alliance leaders.',new:'NEW REQUEST',write:'Write a request',nickname:'Nickname',password:'Delete password (4 digits)',message:'Message',help:'Remember this password for ownership verification.',submit:'SUBMIT',recent:'RECENT REQUESTS',list:'Latest requests',empty:'No requests yet.',loading:'Loading...',waiting:'WAITING',answered:'ANSWERED',admin:'ADMIN REPLY',success:'Your request was submitted.',fail:'Could not submit your request.',config:'Supabase Publishable Key is not configured.',more:'LOAD MORE',footer:'Leave your requests and questions here.'},
pt:{title:'QUADRO DE PEDIDOS',lead:'Envie um pedido ou uma pergunta aos líderes da aliança.',new:'NOVO PEDIDO',write:'Enviar pedido',nickname:'Apelido',password:'Senha de exclusão (4 dígitos)',message:'Mensagem',help:'Guarde esta senha para confirmar a autoria.',submit:'ENVIAR',recent:'PEDIDOS RECENTES',list:'Últimos pedidos',empty:'Nenhum pedido ainda.',loading:'Carregando...',waiting:'AGUARDANDO',answered:'RESPONDIDO',admin:'RESPOSTA DO ADMIN',success:'Pedido enviado.',fail:'Não foi possível enviar.',config:'A chave pública do Supabase não foi configurada.',more:'VER MAIS',footer:'Envie seus pedidos e perguntas.'},
vi:{title:'BẢNG YÊU CẦU',lead:'Gửi yêu cầu hoặc câu hỏi cho ban lãnh đạo liên minh.',new:'YÊU CẦU MỚI',write:'Gửi yêu cầu',nickname:'Tên trong game',password:'Mật khẩu xóa (4 số)',message:'Nội dung',help:'Hãy nhớ mật khẩu để xác nhận bài viết.',submit:'GỬI',recent:'YÊU CẦU GẦN ĐÂY',list:'Yêu cầu mới nhất',empty:'Chưa có yêu cầu.',loading:'Đang tải...',waiting:'ĐANG CHỜ',answered:'ĐÃ TRẢ LỜI',admin:'PHẢN HỒI QUẢN TRỊ',success:'Đã gửi yêu cầu.',fail:'Không thể gửi yêu cầu.',config:'Chưa cấu hình khóa công khai Supabase.',more:'XEM THÊM',footer:'Hãy để lại yêu cầu và câu hỏi.'},
ar:{title:'لوحة الطلبات',lead:'اترك طلبًا أو سؤالًا لقادة التحالف.',new:'طلب جديد',write:'إرسال طلب',nickname:'الاسم داخل اللعبة',password:'رمز الحذف (4 أرقام)',message:'المحتوى',help:'تذكر الرمز لإثبات ملكية الطلب.',submit:'إرسال',recent:'أحدث الطلبات',list:'الطلبات الأخيرة',empty:'لا توجد طلبات بعد.',loading:'جارٍ التحميل...',waiting:'بانتظار الرد',answered:'تم الرد',admin:'رد الإدارة',success:'تم إرسال الطلب.',fail:'تعذر إرسال الطلب.',config:'لم يتم إعداد مفتاح Supabase العام.',more:'عرض المزيد',footer:'اترك طلباتك وأسئلتك هنا.'},
'zh-tw':{title:'留言板',lead:'向聯盟管理員留下請求或問題。',new:'新增留言',write:'提交留言',nickname:'遊戲暱稱',password:'刪除密碼（4位數字）',message:'內容',help:'請記住密碼以確認留言所有權。',submit:'提交',recent:'最近留言',list:'最新留言',empty:'目前沒有留言。',loading:'載入中...',waiting:'等待回覆',answered:'已回覆',admin:'管理員回覆',success:'留言已提交。',fail:'無法提交留言。',config:'尚未設定 Supabase Publishable Key。',more:'載入更多',footer:'請留下您的請求與問題。'}};
function text(){return T[lang]||T.en}function configured(){return cfg.url&&cfg.publishableKey&&!cfg.publishableKey.includes('PASTE_')}
function headers(extra={}){return{apikey:cfg.publishableKey,Authorization:`Bearer ${cfg.publishableKey}`,'Content-Type':'application/json',...extra}}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function formatDate(v){try{return new Intl.DateTimeFormat(lang==='zh-tw'?'zh-TW':lang,{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return v}}
async function hashPassword(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function renderLanguage(){const c=D[lang],t=text();document.documentElement.lang=lang;document.documentElement.dir=c.dir;document.body.classList.toggle('rtl',c.dir==='rtl');$('#flag').textContent=c.flag;$('#lname').textContent=c.name;$$('[data-k]').forEach(e=>{const k=e.dataset.k;if(c.ui[k]!=null)e.textContent=c.ui[k]});$('#requestTitle').textContent=t.title;$('#requestLead').textContent=t.lead;$('#newRequestLabel').textContent=t.new;$('#writeTitle').textContent=t.write;$('#nicknameLabel').textContent=t.nickname;$('#passwordLabel').textContent=t.password;$('#messageLabel').textContent=t.message;$('#passwordHelp').textContent=t.help;$('#requestSubmit').textContent=t.submit;$('#recentLabel').textContent=t.recent;$('#recentTitle').textContent=t.list;$('#requestMore').textContent=t.more;$('#footerText').textContent=t.footer;localStorage.setItem('ezpk-lang-v5',lang)}
async function loadRequests(reset=true){const t=text();if(reset){page=0;$('#requestList').innerHTML=`<div class="request-loading">${esc(t.loading)}</div>`}if(!configured()){ $('#requestList').innerHTML=`<div class="request-empty">${esc(t.config)}</div>`;return}const from=page*PAGE_SIZE,to=from+PAGE_SIZE-1;try{const r=await fetch(`${cfg.url}/rest/v1/requests?select=id,nickname,message,admin_reply,created_at,reply_at&order=created_at.desc&offset=${from}&limit=${PAGE_SIZE}`,{headers:headers({Prefer:'count=exact'})});if(!r.ok)throw new Error(await r.text());const rows=await r.json();if(reset)$('#requestList').innerHTML='';if(!rows.length&&page===0)$('#requestList').innerHTML=`<div class="request-empty">${esc(t.empty)}</div>`;else $('#requestList').insertAdjacentHTML('beforeend',rows.map(x=>`<article class="request-item"><div class="request-meta"><strong>${esc(x.nickname)}</strong><time>${esc(formatDate(x.created_at))}</time></div><p class="request-message">${esc(x.message)}</p><span class="request-state ${x.admin_reply?'answered':''}">${esc(x.admin_reply?t.answered:t.waiting)}</span>${x.admin_reply?`<div class="admin-reply"><b>${esc(t.admin)}</b><p>${esc(x.admin_reply)}</p></div>`:''}</article>`).join(''));$('#requestMore').hidden=rows.length<PAGE_SIZE}catch(e){$('#requestList').innerHTML=`<div class="request-empty">${esc(t.fail)}<br><small>${esc(e.message)}</small></div>`}}
$('#requestForm').addEventListener('submit',async e=>{e.preventDefault();const t=text(),nick=$('#requestNickname').value.trim(),msg=$('#requestMessage').value.trim(),pw=$('#requestPassword').value.trim(),status=$('#requestFormStatus');status.className='request-status';if(!configured()){status.textContent=t.config;status.classList.add('error');return}if(!nick||!msg||!/^[0-9]{4}$/.test(pw)){status.textContent=t.fail;status.classList.add('error');return}$('#requestSubmit').disabled=true;try{const hash=await hashPassword(pw);const payload={nickname:nick,message:msg,delete_password_hash:hash};let r=await fetch(`${cfg.url}/rest/v1/requests`,{method:'POST',headers:headers({Prefer:'return=minimal'}),body:JSON.stringify(payload)});if(!r.ok){const body=await r.text();if(body.includes('delete_password_hash')){payload.delete_password=hash;delete payload.delete_password_hash;r=await fetch(`${cfg.url}/rest/v1/requests`,{method:'POST',headers:headers({Prefer:'return=minimal'}),body:JSON.stringify(payload)})}if(!r.ok)throw new Error(await r.text())}status.textContent=t.success;status.classList.add('ok');$('#requestMessage').value='';$('#requestPassword').value='';$('#messageCount').textContent='0 / 1000';await loadRequests(true)}catch(err){status.textContent=`${t.fail} ${err.message}`;status.classList.add('error')}finally{$('#requestSubmit').disabled=false}})
$('#requestMessage').addEventListener('input',e=>$('#messageCount').textContent=`${e.target.value.length} / 1000`);$('#requestRefresh').onclick=()=>loadRequests(true);$('#requestMore').onclick=()=>{page++;loadRequests(false)};$('#langBtn').onclick=()=>$('#langMenu').hidden=!$('#langMenu').hidden;$$('#langMenu button').forEach(b=>b.onclick=()=>{lang=b.dataset.l;$('#langMenu').hidden=true;renderLanguage();loadRequests(true)});$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');$$('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));renderLanguage();loadRequests(true);
