(function(){
'use strict';
const game=document.body.dataset.game, cfg=window.EZPK_SUPABASE_CONFIG||{}, $=s=>document.querySelector(s); let score=0,start=0,timer=null,nick='';
const names={
 'treasure-hunter':['TREASURE HUNTER','Find the hidden key and treasure, then escape.','MOVES','Tap tiles to reveal the key, treasure, and exit. Collect both items before opening the exit.','Fewer moves earn a higher score. Avoid bombs.'],
 'zombie-defense':['ZOMBIE DEFENSE','Destroy the incoming zombies before they break through.','WAVE','Tap incoming zombies before they reach the defense line. Clear the required kills to advance to the next wave.','Faster kills and higher waves earn more points.'],
 'portal-escape':['PORTAL ESCAPE','Find the shortest safe route to the portal.','SCORE','Move one tile at a time and guide your unit through the open path to the portal. Walls cannot be crossed.','Reach the portal in as few moves as possible.'],
 'hero-merge':['HERO MERGE','Merge matching heroes and build the highest tier.','SCORE','Use the direction buttons to move every tile. Matching heroes merge into the next tier.','Plan each move carefully and build the highest-tier hero.']};
const n=names[game]; $('#gameTitle').textContent=n[0];$('#gameLead').textContent=n[1];$('#scoreLabel').textContent=n[2];
$('#mobileInfoTitle').textContent=n[0];$('#mobileInfoText').textContent=n[3];$('#mobileInfoControl').textContent=n[4];
const monthKey=()=>new Date().toISOString().slice(0,7),monthStartISO=()=>monthKey()+'-01T00:00:00.000Z',nextMonthISO=()=>{const d=new Date();return new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,1)).toISOString()};
function headers(extra={}){return {'apikey':cfg.anonKey,'Authorization':`Bearer ${cfg.anonKey}`,'Content-Type':'application/json',...extra}}function configured(){return cfg.url&&cfg.anonKey&&!String(cfg.url).includes('YOUR_')}
function localRows(){try{return JSON.parse(localStorage.getItem(`ezpk-ranking-${game}-${monthKey()}`)||'[]')}catch{return[]}}function saveLocal(){let r=localRows();r.push({nickname:nick,score,created_at:new Date().toISOString()});localStorage.setItem(`ezpk-ranking-${game}-${monthKey()}`,JSON.stringify(r.slice(-300)))}
async function submit(){saveLocal();if(configured())try{await fetch(`${cfg.url}/rest/v1/game_scores`,{method:'POST',headers:headers({Prefer:'return=minimal'}),body:JSON.stringify({nickname:nick,score,game_id:game})})}catch(e){console.warn(e)}await loadRanking()}
function best(rows){const m=new Map();rows.forEach(r=>{const k=String(r.nickname).toLowerCase();if(!m.has(k)||+r.score>+m.get(k).score)m.set(k,r)});return [...m.values()].sort((a,b)=>b.score-a.score).slice(0,30)}
async function loadRanking(){let rows=[],remote=false;$('#rankingStatus').textContent='Loading ranking...';if(configured())try{const q=`select=nickname,score,created_at&game_id=eq.${game}&created_at=gte.${encodeURIComponent(monthStartISO())}&created_at=lt.${encodeURIComponent(nextMonthISO())}&order=score.desc&limit=300`;const r=await fetch(`${cfg.url}/rest/v1/game_scores?${q}`,{headers:headers()});rows=await r.json();remote=r.ok}catch(e){}if(!remote)rows=localRows();rows=best(rows);window.EZPKRankingPanel.renderRows(rows);$('#rankingStatus').textContent=rows.length?'':'No scores yet.';$('#rankingTitle').textContent='Monthly '+n[0]+' Ranking';$('#rankingNote').textContent='A new ranking starts on the first day of each month. Only each nickname’s best score is shown.';$('#monthChip').textContent=monthKey();}
function update(){ $('#scoreValue').textContent=score.toLocaleString(); if(start)$('#timeValue').textContent=((Date.now()-start)/1000).toFixed(1)+'s'}function begin(){window.EZPKGameViewport?.setPlaying(true);nick=$('#nickname').value.trim();if(!nick)return alert('Enter a nickname.');localStorage.setItem('ezpk-game-nickname',nick);score=0;start=Date.now();$('#startOverlay').hidden=true;$('#resultOverlay').hidden=true;clearInterval(timer);timer=setInterval(update,100);build()}
async function finish(msg){window.EZPKGameViewport?.setPlaying(false);clearInterval(timer);update();$('#finalScore').textContent=score.toLocaleString();$('#resultText').textContent=msg;$('#resultOverlay').hidden=false;await submit()}
function treasure(){const stage=$('#stage'),size=6,total=36,key=Math.floor(Math.random()*total),treasure=(key+7+Math.floor(Math.random()*20))%total,exit=(treasure+11)%total;let gotK=false,gotT=false,moves=0;stage.innerHTML='<div class="newgame-grid"></div>';const g=stage.firstChild;for(let i=0;i<total;i++){const b=document.createElement('button');b.className='newgame-cell';b.textContent='?';b.onclick=()=>{if(b.classList.contains('revealed'))return;moves++;b.classList.add('revealed');b.textContent=i===key?'🗝':i===treasure?'💰':i===exit?'🚪':Math.random()<.12?'💣':'·';if(i===key)gotK=true;if(i===treasure)gotT=true;if(i===exit&&gotK&&gotT){score=Math.max(100,2200-moves*45);finish(`Escaped in ${moves} moves.`)}else if(b.textContent==='💣')score=Math.max(0,score-80);else score+=15;update()};g.appendChild(b)}}
function zombies(){const stage=$('#stage');stage.innerHTML='';let wave=1,kills=0,alive=true;score=0;const spawn=()=>{if(!alive)return;for(let i=0;i<Math.min(2+wave,10);i++){const z=document.createElement('button');z.className='zombie';z.textContent='🧟';z.style.left=(5+Math.random()*85)+'%';z.style.top='-10%';stage.appendChild(z);let y=-10,speed=.35+wave*.045;const id=setInterval(()=>{y+=speed;z.style.top=y+'%';if(y>92){clearInterval(id);alive=false;finish(`Defense broke at wave ${wave}.`) }},30);z.onclick=()=>{clearInterval(id);z.remove();kills++;score+=100+wave*15;update();if(kills>=wave*4){wave++;kills=0;$('#scoreLabel').textContent='WAVE '+wave;spawn()}}}};spawn()}
function portal(){const stage=$('#stage'),size=7;let cells=[],player=0,portal=size*size-1,moves=0;for(let i=0;i<size*size;i++)cells[i]=Math.random()<.18&&i!==0&&i!==portal?'wall':'open';stage.innerHTML='<div class="newgame-grid" style="grid-template-columns:repeat(7,1fr)"></div>';const g=stage.firstChild;function paint(){g.innerHTML='';cells.forEach((c,i)=>{const b=document.createElement('button');b.className='newgame-cell '+(c==='wall'?'wall ':'')+(i===player?'player ':'')+(i===portal?'portal':'');b.textContent=i===player?'🛡':i===portal?'🌀':c==='wall'?'':'·';b.onclick=()=>move(i);g.appendChild(b)})}function move(i){const a=Math.abs((i%size)-(player%size)),b=Math.abs(Math.floor(i/size)-Math.floor(player/size));if(a+b!==1||cells[i]==='wall')return;player=i;moves++;score=Math.max(0,1500-moves*25);paint();update();if(player===portal)finish(`Portal reached in ${moves} moves.`)}paint()}
function merge(){const stage=$('#stage');let board=Array(16).fill(0);function add(){const e=board.map((v,i)=>v?null:i).filter(v=>v!==null);if(e.length)board[e[Math.floor(Math.random()*e.length)]]=1}function draw(){stage.innerHTML='<div><div class="merge-board"></div><div class="merge-controls"><button data-d="left">◀</button><button data-d="up">▲</button><button data-d="down">▼</button><button data-d="right">▶</button></div></div>';const g=stage.querySelector('.merge-board');board.forEach(v=>{const t=document.createElement('div');t.className='merge-tile';t.textContent=v?['','🪖','⚔️','🛡','👑','🔥'][Math.min(v,5)]+' '+(2**v):'';g.appendChild(t)});stage.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>shift(b.dataset.d))}function line(arr){let a=arr.filter(Boolean);for(let i=0;i<a.length-1;i++)if(a[i]===a[i+1]){a[i]++;score+=2**a[i]*10;a.splice(i+1,1)}while(a.length<4)a.push(0);return a}function shift(d){let old=board.join();let nb=Array(16).fill(0);for(let k=0;k<4;k++){let arr=[];for(let j=0;j<4;j++){let r=d==='up'||d==='down'?j:k,c=d==='up'||d==='down'?k:j;arr.push(board[r*4+c])}if(d==='right'||d==='down')arr.reverse();arr=line(arr);if(d==='right'||d==='down')arr.reverse();for(let j=0;j<4;j++){let r=d==='up'||d==='down'?j:k,c=d==='up'||d==='down'?k:j;nb[r*4+c]=arr[j]}}board=nb;if(board.join()!==old)add();draw();update();if(!board.includes(0)){score+=Math.max(...board)*100;finish('Board completed.')}}add();add();draw()}
function build(){({ 'treasure-hunter':treasure,'zombie-defense':zombies,'portal-escape':portal,'hero-merge':merge}[game])()}
$('#startBtn').onclick=begin;$('#retryBtn').onclick=begin;$('#rankingBtn').onclick=()=>{window.EZPKRankingPanel.focusPlayer(nick);$('#resultOverlay').hidden=true};$('#refreshRanking').onclick=loadRanking;$('#nickname').value=localStorage.getItem('ezpk-game-nickname')||'';loadRanking();
})();
