(function(){
  'use strict';
  const PAGE_SIZE=10;
  const MAX_ROWS=30;
  const stateMap=new WeakMap();
  const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
  function markup(){return '<div class="ranking-head"><div><span id="rankingEyebrow">TOP 30</span><h2 id="rankingTitle"></h2></div><button id="refreshRanking" type="button" aria-label="Refresh">↻</button></div><div class="month-chip" id="monthChip"></div><div id="rankingStatus" class="ranking-status"></div><ol id="rankingList" class="ranking-list"></ol><nav class="ranking-pagination" aria-label="Ranking pages"><button class="ranking-page-button ranking-prev" type="button" aria-label="Previous ranking page">‹</button><span class="ranking-page-indicator" aria-live="polite">1 / 1</span><button class="ranking-page-button ranking-next" type="button" aria-label="Next ranking page">›</button></nav><p id="rankingNote" class="ranking-note"></p>'}
  function getPanel(panel){return typeof panel==='string'?document.querySelector(panel):panel||document.querySelector('.ranking-panel')}
  function getState(panel){if(!stateMap.has(panel))stateMap.set(panel,{rows:[],page:0,scoreKey:'score'});return stateMap.get(panel)}
  function init(root=document){root.querySelectorAll('[data-ranking-panel], .ranking-panel').forEach(panel=>{if(panel.dataset.rankingReady)return;panel.innerHTML=markup();panel.dataset.rankingReady='true';const state=getState(panel);panel.querySelector('.ranking-prev')?.addEventListener('click',()=>setPage(state.page-1,panel));panel.querySelector('.ranking-next')?.addEventListener('click',()=>setPage(state.page+1,panel))})}
  function rowMarkup(row,index,scoreKey){const nickname=String(row.nickname??'').trim(),key=nickname.toLowerCase(),rank=index+1,place=rank===1?'<span class="rank-medal">🥇</span>':rank===2?'<span class="rank-medal">🥈</span>':rank===3?'<span class="rank-medal">🥉</span>':rank;return `<li class="ranking-row ${rank<=3?`top-${rank}`:''}" data-player-key="${escapeHtml(key)}" data-rank="${rank}"><span class="rank-place">${place}</span><span class="rank-name">${escapeHtml(nickname)}</span><strong class="rank-score">${Number(row[scoreKey]||0).toLocaleString()}</strong></li>`}
  function paint(panel){const state=getState(panel),list=panel.querySelector('#rankingList');if(!list)return;const pageCount=Math.max(1,Math.ceil(state.rows.length/PAGE_SIZE));state.page=Math.min(Math.max(0,state.page),pageCount-1);const start=state.page*PAGE_SIZE;list.innerHTML=state.rows.slice(start,start+PAGE_SIZE).map((row,i)=>rowMarkup(row,start+i,state.scoreKey)).join('');const indicator=panel.querySelector('.ranking-page-indicator'),prev=panel.querySelector('.ranking-prev'),next=panel.querySelector('.ranking-next'),pager=panel.querySelector('.ranking-pagination');if(indicator)indicator.textContent=`${state.page+1} / ${pageCount}`;if(prev)prev.disabled=state.page===0;if(next)next.disabled=state.page>=pageCount-1;if(pager)pager.hidden=state.rows.length<=PAGE_SIZE}
  function renderRows(rows,options={}){const panel=getPanel(options.panel);if(!panel)return;init(panel.parentNode||document);const state=getState(panel);state.rows=(rows||[]).slice(0,MAX_ROWS);state.scoreKey=options.scoreKey||'score';state.page=Number.isInteger(options.page)?options.page:0;paint(panel)}
  function setPage(page,panel){const p=getPanel(panel);if(!p)return;getState(p).page=page;paint(p)}
  function setStatus(text,panel){const el=getPanel(panel)?.querySelector('#rankingStatus');if(el)el.textContent=text||''}
  function setNote(text,panel){const el=getPanel(panel)?.querySelector('#rankingNote');if(el)el.textContent=text||''}
  function setMonth(text,panel){const el=getPanel(panel)?.querySelector('#monthChip');if(el)el.textContent=text||''}
  function clearFocus(panel){const p=getPanel(panel);if(!p)return;p.classList.remove('ranking-focus');p.querySelectorAll('.ranking-row.current-player').forEach(row=>row.classList.remove('current-player'))}
  function focusPlayer(nickname,options={}){const panel=getPanel(options.panel);if(!panel)return null;const state=getState(panel),key=String(nickname||'').trim().toLowerCase(),index=state.rows.findIndex(row=>String(row.nickname??'').trim().toLowerCase()===key);if(index>=0){state.page=Math.floor(index/PAGE_SIZE);paint(panel)}clearFocus(panel);void panel.offsetWidth;panel.classList.add('ranking-focus');const row=[...panel.querySelectorAll('.ranking-row')].find(item=>item.dataset.playerKey===key);if(row)row.classList.add('current-player');if(options.scroll!==false&&matchMedia('(max-width:980px)').matches)(row||panel).scrollIntoView({behavior:'smooth',block:row?'center':'start'});setTimeout(()=>panel.classList.remove('ranking-focus'),options.panelFocusMs||1400);setTimeout(()=>row&&row.classList.remove('current-player'),options.playerFocusMs||2600);return row}
  window.EZPKRankingPanel={init,renderRows,setPage,setStatus,setNote,setMonth,clearFocus,focusPlayer,escapeHtml};
  init();
})();
