-- EZPK Survival monthly leaderboard setup
create table if not exists public.game_scores (
  id bigint generated by default as identity primary key,
  nickname varchar(16) not null check (char_length(trim(nickname)) between 1 and 16),
  score integer not null check (score >= 0 and score <= 3600000),
  created_at timestamptz not null default now()
);

create index if not exists game_scores_month_score_idx
  on public.game_scores (created_at desc, score desc);

alter table public.game_scores enable row level security;

drop policy if exists "Anyone can read game scores" on public.game_scores;
create policy "Anyone can read game scores" on public.game_scores
  for select to anon, authenticated using (true);

drop policy if exists "Anyone can submit game scores" on public.game_scores;
create policy "Anyone can submit game scores" on public.game_scores
  for insert to anon, authenticated with check (
    char_length(trim(nickname)) between 1 and 16
    and score between 0 and 3600000
  );

-- Monthly reset is automatic in the webpage: only rows from the current calendar month are queried.
-- Optional cleanup of old data can be performed later without affecting the monthly leaderboard.
