-- EZPK Mini Games monthly leaderboard setup / upgrade for v48
create table if not exists public.game_scores (
  id bigint generated by default as identity primary key,
  nickname varchar(16) not null check (char_length(trim(nickname)) between 1 and 16),
  score integer not null check (score >= 0 and score <= 3600000),
  created_at timestamptz not null default now()
);

-- v48: separate rankings for SURVIVAL, DRONE HUNTER, TANK BATTLE, and MISSILE DEFENSE.
alter table public.game_scores
  add column if not exists game_id varchar(32) not null default 'survival';

create index if not exists game_scores_game_month_score_idx
  on public.game_scores (game_id, created_at desc, score desc);

alter table public.game_scores enable row level security;

drop policy if exists "Anyone can read game scores" on public.game_scores;
create policy "Anyone can read game scores" on public.game_scores
  for select to anon, authenticated using (true);

drop policy if exists "Anyone can submit game scores" on public.game_scores;
create policy "Anyone can submit game scores" on public.game_scores
  for insert to anon, authenticated with check (
    char_length(trim(nickname)) between 1 and 16
    and score between 0 and 3600000
    and game_id in ('survival', 'drone_hunter', 'tank_battle', 'missile_defense')
  );

-- Existing v47 scores automatically remain classified as 'survival'.
-- The webpage queries only the current calendar month, so monthly reset is automatic.
