(()=>{
  'use strict';
  const KEY='ezpk-lang-v5';
  const META={ko:{flag:'🇰🇷',name:'한국어'},en:{flag:'🇺🇸',name:'English'},pt:{flag:'🇧🇷',name:'Português'},vi:{flag:'🇻🇳',name:'Tiếng Việt'},ar:{flag:'🇸🇦',name:'العربية'},ja:{flag:'🇯🇵',name:'日本語'},th:{flag:'🇹🇭',name:'ไทย'},'zh-tw':{flag:'🇹🇼',name:'繁體中文'}};
  const T={
    ko:{title:'연맹을 선택해 주세요',lead:'이용할 EZPK 연맹 사이트를 선택해 주세요.',m1:'메인 연맹',b1:'성장과 참여, 협력을 중심으로 함께 운영되는 EZPK 메인 연맹입니다.',e1:'EZPK1 입장',m2:'서브 연맹',b2:'조금 더 자유롭고 가볍게 게임을 함께 즐길 수 있는 EZPK 서브 연맹입니다.',e2:'EZPK2 입장',inactive:'EZPK2는 현재 운영하지 않습니다.',footer:'연맹을 선택하면 해당 사이트로 이동합니다.'},
    en:{title:'Choose Your Alliance',lead:'Select the EZPK alliance portal you want to enter.',m1:'Main Alliance',b1:'The EZPK main alliance focused on active growth, participation, and teamwork.',e1:'Enter EZPK1',m2:'Sub Alliance',b2:'The EZPK sub alliance for a lighter and more flexible way to play together.',e2:'Enter EZPK2',inactive:'EZPK2 is currently inactive.',footer:'Choose an alliance to continue.'},
    pt:{title:'Escolha sua Aliança',lead:'Selecione o portal EZPK que deseja acessar.',m1:'Aliança Principal',b1:'Aliança principal da EZPK com foco em crescimento, participação e cooperação.',e1:'Entrar na EZPK1',m2:'Aliança Secundária',b2:'Uma opção mais leve e flexível para jogar juntos.',e2:'Entrar na EZPK2',inactive:'A EZPK2 está inativa no momento.',footer:'Escolha uma aliança para continuar.'},
    vi:{title:'Chọn Liên minh',lead:'Chọn cổng liên minh EZPK bạn muốn truy cập.',m1:'Liên minh Chính',b1:'Liên minh chính EZPK tập trung vào phát triển, tham gia và phối hợp.',e1:'Vào EZPK1',m2:'Liên minh Phụ',b2:'Lựa chọn linh hoạt và nhẹ nhàng hơn để cùng chơi.',e2:'Vào EZPK2',inactive:'EZPK2 hiện không hoạt động.',footer:'Chọn một liên minh để tiếp tục.'},
    ar:{title:'اختر التحالف',lead:'اختر بوابة تحالف EZPK التي تريد الدخول إليها.',m1:'التحالف الرئيسي',b1:'تحالف EZPK الرئيسي للنمو والمشاركة والتعاون.',e1:'الدخول إلى EZPK1',m2:'التحالف الفرعي',b2:'خيار أكثر مرونة وخفة للاستمتاع باللعبة معًا.',e2:'الدخول إلى EZPK2',inactive:'EZPK2 غير نشط حاليًا.',footer:'اختر تحالفًا للمتابعة.'},
    ja:{title:'同盟を選択してください',lead:'利用するEZPK同盟ポータルを選択してください。',m1:'メイン同盟',b1:'成長・参加・協力を重視するEZPKのメイン同盟です。',e1:'EZPK1へ',m2:'サブ同盟',b2:'より自由で軽いスタイルで一緒に遊べるEZPKのサブ同盟です。',e2:'EZPK2へ',inactive:'EZPK2は現在運営していません。',footer:'同盟を選択して続行してください。'},
    th:{title:'เลือกพันธมิตร',lead:'เลือกเว็บไซต์พันธมิตร EZPK ที่ต้องการเข้าใช้งาน',m1:'พันธมิตรหลัก',b1:'พันธมิตรหลัก EZPK ที่เน้นการเติบโต การมีส่วนร่วม และการร่วมมือ',e1:'เข้า EZPK1',m2:'พันธมิตรรอง',b2:'รูปแบบการเล่นที่ยืดหยุ่นและสบายมากขึ้น',e2:'เข้า EZPK2',inactive:'ขณะนี้ EZPK2 ไม่ได้เปิดใช้งาน',footer:'เลือกพันธมิตรเพื่อดำเนินการต่อ'},
    'zh-tw':{title:'選擇聯盟',lead:'請選擇要進入的 EZPK 聯盟網站。',m1:'主要聯盟',b1:'重視成長、參與與合作的 EZPK 主要聯盟。',e1:'進入 EZPK1',m2:'次要聯盟',b2:'以更自由、輕鬆的方式一起遊玩的 EZPK 次要聯盟。',e2:'進入 EZPK2',inactive:'EZPK2 目前未啟用。',footer:'請選擇聯盟以繼續。'}
  };
  const $=s=>document.querySelector(s),btn=$('#gatewayLangBtn'),menu=$('#gatewayLangMenu');
  function language(){try{const x=localStorage.getItem(KEY)||'en';return T[x]?x:'en'}catch(_){return'en'}}
  function setMenu(open){menu.hidden=!open;btn.setAttribute('aria-expanded',open?'true':'false')}
  function render(){const l=language(),t=T[l],m=META[l]||META.en;document.documentElement.lang=l==='zh-tw'?'zh-Hant':l;document.documentElement.dir=l==='ar'?'rtl':'ltr';$('#gatewayTitle').textContent=t.title;$('#gatewayLead').textContent=t.lead;$('#ezpk1Title').textContent=t.m1;$('#ezpk1Body').textContent=t.b1;$('#enterEzpk1').textContent=t.e1;$('#ezpk2Title').textContent=t.m2;$('#ezpk2Body').textContent=t.b2;$('#enterEzpk2').textContent=t.e2;$('#gatewayFooter').textContent=t.footer;$('#gatewayFlag').textContent=m.flag;$('#gatewayLanguageName').textContent=m.name;window.EZPKMigrationEntry?.render('gatewayMigrationEntry',l);document.querySelectorAll('[data-lang]').forEach(el=>el.classList.toggle('is-active',el.dataset.lang===l));if(!$('#gatewayStatus').hidden)$('#gatewayStatus').textContent=t.inactive}
  btn.addEventListener('click',e=>{e.stopPropagation();setMenu(menu.hidden)});menu.addEventListener('click',e=>{const c=e.target.closest('[data-lang]');if(!c)return;try{localStorage.setItem(KEY,c.dataset.lang)}catch(_){}setMenu(false);render()});document.addEventListener('click',e=>{if(!menu.hidden&&!e.target.closest('.gateway-language'))setMenu(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape')setMenu(false)});render();
  fetch('/api/site-context',{credentials:'include',cache:'no-store'}).then(r=>r.json()).then(j=>{if(!j?.ok)return;const d=j.data||{};if(d.mode==='SINGLE'){location.replace('https://ezpk322.com/');return}const migrationEntry=$('#gatewayMigrationEntry');if(migrationEntry)migrationEntry.hidden=d.migrationIntakeEnabled===false;if(!d.ezpk2Active){$('#ezpk2Card').classList.add('is-inactive');$('#ezpk2Card').removeAttribute('href');$('#gatewayStatus').hidden=false;$('#gatewayStatus').textContent=(T[language()]||T.en).inactive}}).catch(()=>{});
})();
