(function(){
'use strict';
const D=window.EZPK_DATA||{};let lang=localStorage.getItem('ezpk-lang-v5')||'en';if(!D[lang])lang='en';
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const files={ko:'./season7-ko.webp',en:'./season7-en.webp',pt:'./season7-pt.webp',vi:'./season7-vi.webp',ar:'./season7-ar.webp',ja:'./season7-en.webp',th:'./season7-en.webp','zh-tw':'./season7-zh-tw.webp'};
const labels={
ko:{latest:'최신 정보',latestLead:'시즌7 최신정보를 확인하세요.',teams:'팀 편성',title:'팀 편성',lead:'팀 편성 현황을 확인하세요.',attack:'공격팀',defense:'방어팀',support:'지원팀',total:n=>`총 ${n}명`,empty:'현재 배정된 명단이 없습니다.',open:'팀 이미지 열기',updated:'업데이트',imageGuide:'팀 이미지 저장 안내',mobile:'📱 모바일: 이미지를 길게 눌러 저장하세요.',pc:'🖥️ PC: 이미지 위에서 마우스 오른쪽 버튼을 눌러 저장하세요.',download:'이미지 다운로드',close:'닫기',members:'팀 명단'},
en:{latest:'LATEST INFORMATION',latestLead:'Check the latest Season 7 information.',teams:'TEAM ASSIGNMENT',title:'TEAM ASSIGNMENT',lead:'Check the current team assignment status.',attack:'ATTACK TEAM',defense:'DEFENSE TEAM',support:'SUPPORT TEAM',total:n=>`Total ${n} Members`,empty:'No team members have been assigned yet.',open:'OPEN TEAM IMAGE',updated:'Updated',imageGuide:'How to save the team image',mobile:'📱 Mobile: Press and hold the image to save it.',pc:'🖥️ PC: Right-click the image and choose save.',download:'DOWNLOAD IMAGE',close:'CLOSE',members:'TEAM MEMBERS'},
vi:{latest:'THÔNG TIN MỚI NHẤT',latestLead:'Xem thông tin mới nhất của Mùa 7.',teams:'PHÂN CHIA ĐỘI',title:'PHÂN CHIA ĐỘI',lead:'Xem tình hình phân chia đội hiện tại.',attack:'ĐỘI TẤN CÔNG',defense:'ĐỘI PHÒNG THỦ',support:'ĐỘI HỖ TRỢ',total:n=>`Tổng ${n} thành viên`,empty:'Hiện chưa có thành viên nào được phân công.',open:'MỞ HÌNH ĐỘI',updated:'Cập nhật',imageGuide:'Hướng dẫn lưu hình đội',mobile:'📱 Di động: nhấn giữ hình ảnh để lưu.',pc:'🖥️ PC: nhấp chuột phải vào hình ảnh để lưu.',download:'TẢI HÌNH ẢNH',close:'ĐÓNG',members:'DANH SÁCH THÀNH VIÊN'},
pt:{latest:'ÚLTIMAS INFORMAÇÕES',latestLead:'Confira as últimas informações da Temporada 7.',teams:'FORMAÇÃO DAS EQUIPES',title:'FORMAÇÃO DAS EQUIPES',lead:'Confira a situação atual da formação das equipes.',attack:'EQUIPE DE ATAQUE',defense:'EQUIPE DE DEFESA',support:'EQUIPE DE SUPORTE',total:n=>`Total: ${n} membros`,empty:'Nenhum membro foi atribuído ainda.',open:'ABRIR IMAGEM DA EQUIPE',updated:'Atualizado',imageGuide:'Como salvar a imagem da equipe',mobile:'📱 Celular: pressione e segure a imagem para salvar.',pc:'🖥️ PC: clique com o botão direito na imagem para salvar.',download:'BAIXAR IMAGEM',close:'FECHAR',members:'MEMBROS DA EQUIPE'},
ar:{latest:'أحدث المعلومات',latestLead:'اطّلع على أحدث معلومات الموسم السابع.',teams:'توزيع الفرق',title:'توزيع الفرق',lead:'اطّلع على حالة توزيع الفرق الحالية.',attack:'فريق الهجوم',defense:'فريق الدفاع',support:'فريق الدعم',total:n=>`إجمالي ${n} عضو`,empty:'لا يوجد أعضاء تم تعيينهم حالياً.',open:'فتح صورة الفريق',updated:'آخر تحديث',imageGuide:'طريقة حفظ صورة الفريق',mobile:'📱 الجوال: اضغط مطولاً على الصورة لحفظها.',pc:'🖥️ الكمبيوتر: انقر بزر الفأرة الأيمن على الصورة لحفظها.',download:'تنزيل الصورة',close:'إغلاق',members:'أعضاء الفريق'},
'zh-tw':{latest:'最新資訊',latestLead:'查看第7賽季最新資訊。',teams:'隊伍編組',title:'隊伍編組',lead:'查看目前的隊伍編組狀況。',attack:'攻擊隊',defense:'防禦隊',support:'支援隊',total:n=>`共 ${n} 名成員`,empty:'目前尚未分配任何成員。',open:'開啟隊伍圖片',updated:'更新',imageGuide:'隊伍圖片儲存說明',mobile:'📱 手機：長按圖片即可儲存。',pc:'🖥️ 電腦：在圖片上按滑鼠右鍵儲存。',download:'下載圖片',close:'關閉',members:'隊伍成員'},
ja:{latest:'最新情報',latestLead:'シーズン7の最新情報を確認してください。',teams:'チーム編成',title:'チーム編成',lead:'現在のチーム編成状況を確認してください。',attack:'攻撃チーム',defense:'防衛チーム',support:'支援チーム',total:n=>`合計 ${n}名`,empty:'現在割り当てられたメンバーはいません。',open:'チーム画像を開く',updated:'更新',imageGuide:'チーム画像の保存方法',mobile:'📱 モバイル：画像を長押しして保存してください。',pc:'🖥️ PC：画像を右クリックして保存してください。',download:'画像をダウンロード',close:'閉じる',members:'チームメンバー'},
th:{latest:'ข้อมูลล่าสุด',latestLead:'ตรวจสอบข้อมูลล่าสุดของซีซัน 7',teams:'การจัดทีม',title:'การจัดทีม',lead:'ตรวจสอบสถานะการจัดทีมปัจจุบัน',attack:'ทีมโจมตี',defense:'ทีมป้องกัน',support:'ทีมสนับสนุน',total:n=>`ทั้งหมด ${n} คน`,empty:'ขณะนี้ยังไม่มีรายชื่อที่ได้รับมอบหมาย',open:'เปิดรูปทีม',updated:'อัปเดต',imageGuide:'วิธีบันทึกรูปทีม',mobile:'📱 มือถือ: กดรูปค้างไว้เพื่อบันทึก',pc:'🖥️ PC: คลิกขวาที่รูปเพื่อบันทึก',download:'ดาวน์โหลดรูป',close:'ปิด',members:'สมาชิกทีม'}
};
let teamData={lastUpdated:'',teams:{attack:[],defense:[],support:[]}};
function L(){return labels[lang]||labels.en}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function loadTeams(){try{const r=await fetch('../data/season7-teams.json?v='+Date.now(),{cache:'no-store'});if(r.ok)teamData=await r.json()}catch(e){}renderTeams()}
function fitNames(){requestAnimationFrame(()=>{$$('.team-member-name').forEach(el=>{let size=13;el.style.fontSize=size+'px';while(size>9&&(el.scrollHeight>el.clientHeight+1||el.scrollWidth>el.clientWidth+1)){size-=.5;el.style.fontSize=size+'px'}})})}
const teamIcons={
attack:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14.7 3.3 20.7 9.3 9.8 20.2 4.5 21.5 5.8 16.2 16.7 5.3 14.7 3.3Z"/><path d="m4 4 5 5M3 3l3.2 1.1L4.1 6.2 3 3Z"/></svg>',
defense:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2.8 20 6v5.7c0 5.1-3.2 8.1-8 9.5-4.8-1.4-8-4.4-8-9.5V6l8-3.2Z"/><path d="M12 6v11"/></svg>',
support:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9.2 3h5.6v6.2H21v5.6h-6.2V21H9.2v-6.2H3V9.2h6.2V3Z"/></svg>'
};
function renderTeams(){const l=L();$('#teamAssignmentTitle').textContent=l.title;$('#teamAssignmentLead').textContent=l.lead;const updated=$('#teamUpdated');if(teamData.lastUpdated){updated.hidden=false;updated.textContent=`${l.updated}: ${teamData.lastUpdated}`}else updated.hidden=true;$('#teamCards').innerHTML=['attack','defense','support'].map(k=>{const list=Array.isArray(teamData?.teams?.[k])?teamData.teams[k]:[];return `<article class="team-card team-card--${k}" data-team-card="${k}"><header class="team-card-head"><div class="team-card-identity"><span class="team-card-icon">${teamIcons[k]}</span><div class="team-card-title"><h3>${l[k]}</h3><span>SEASON 7</span></div></div><p>${l.total(list.length)}</p></header><div class="team-member-grid">${list.length?list.map(n=>`<div class="team-member-cell"><span class="team-member-name" title="${esc(n)}">${esc(n)}</span></div>`).join(''):`<p class="team-empty">${l.empty}</p>`}</div><div class="team-card-actions"><button class="team-open-image" type="button" data-open-team="${k}" ${list.length?'':'hidden'}>${l.open}</button></div></article>`}).join('');$$('[data-open-team]').forEach(b=>b.onclick=()=>openTeamImage(b.dataset.openTeam));fitNames()}
function createTeamImage(k){const l=L(),names=teamData?.teams?.[k]||[],accent={attack:'#d85a5a',defense:'#5f8fe5',support:'#4fbd83'}[k]||'#d9bb65',cols=5,cellW=250,cellH=92,pad=70,headerH=230,rows=Math.ceil(names.length/cols),w=pad*2+cols*cellW,h=headerH+pad+Math.max(rows,1)*cellH+pad;const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle='#070b12';x.fillRect(0,0,w,h);x.strokeStyle=accent;x.lineWidth=3;x.strokeRect(24,24,w-48,h-48);x.textAlign='center';x.fillStyle=accent;x.font='700 25px Arial';x.fillText('SERVER 322 · EZPK ALLIANCE',w/2,72);x.fillStyle=accent;x.font='800 55px Arial';x.fillText(l[k],w/2,140);x.fillStyle='#aeb8c6';x.font='600 25px Arial';x.fillText(l.total(names.length),w/2,188);names.forEach((name,i)=>{const col=i%cols,row=Math.floor(i/cols),cx=pad+col*cellW,cy=headerH+row*cellH;x.fillStyle='#101824';x.strokeStyle='#2d3a4f';x.lineWidth=2;x.beginPath();x.roundRect(cx+5,cy+5,cellW-10,cellH-10,10);x.fill();x.stroke();x.fillStyle='#f1f4f8';let fs=24;x.font=`700 ${fs}px Arial`;while(fs>15&&x.measureText(name).width>cellW-30){fs--;x.font=`700 ${fs}px Arial`}const words=String(name).split(' ');let lines=[name];if(x.measureText(name).width>cellW-30&&words.length>1){let a='',b='';for(const word of words){if(x.measureText((a+' '+word).trim()).width<=cellW-30)a=(a+' '+word).trim();else b=(b+' '+word).trim()}lines=[a,b].filter(Boolean)}if(lines.length===1)x.fillText(lines[0],cx+cellW/2,cy+56);else{const lh=fs+5;x.fillText(lines[0],cx+cellW/2,cy+45-lh/2);x.fillText(lines[1],cx+cellW/2,cy+45+lh/2)}});return c.toDataURL('image/png')}
function openTeamImage(k){const l=L(),url=createTeamImage(k);$('#teamImageTitle').textContent=l[k];$('#teamImageGuideTitle').textContent=l.imageGuide;$('#teamImageGuideMobile').textContent=l.mobile;$('#teamImageGuidePc').textContent=l.pc;$('#teamImagePreview').src=url;const a=$('#teamImageDownload');a.href=url;a.download=`EZPK-Season7-${k[0].toUpperCase()+k.slice(1)}-Team.png`;a.textContent=l.download;$('#teamImageDone').textContent=l.close;$('#teamImageModal').hidden=false;document.body.classList.add('team-modal-open');setTimeout(()=>$('#teamImageClose').focus(),0)}
function closeTeamImage(){$('#teamImageModal').hidden=true;$('#teamImagePreview').removeAttribute('src');document.body.classList.remove('team-modal-open')}
function render(){const c=D[lang]||D.en,l=L();document.documentElement.lang=lang;document.documentElement.dir=c.dir||'ltr';document.body.classList.toggle('rtl',(c.dir||'ltr')==='rtl');if($('#flag'))$('#flag').textContent=c.flag||'';if($('#lname'))$('#lname').textContent=c.name||'';$('#season7Img').src=(files[lang]||files.en)+'?v=982';$$('[data-k]').forEach(e=>{const k=e.dataset.k;if(c.ui?.[k]!=null)e.innerHTML=c.ui[k]});$('#latestInfoTitle').textContent=l.latest;$('#latestInfoLead').textContent=l.latestLead;localStorage.setItem('ezpk-lang-v5',lang);renderTeams()}
$('#langBtn').onclick=()=>$('#langMenu').hidden=!$('#langMenu').hidden;$$('#langMenu button').forEach(b=>b.onclick=()=>{lang=b.dataset.l;if(!labels[lang])lang='en';$('#langMenu').hidden=true;render()});$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');$$('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));$$('[data-team-close]').forEach(el=>el.onclick=closeTeamImage);$('#teamImageClose').onclick=closeTeamImage;$('#teamImageDone').onclick=closeTeamImage;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#teamImageModal').hidden)closeTeamImage()});render();loadTeams();
})();
