(function(){
  'use strict';
  const $=s=>document.querySelector(s);
  const TEXT={
    ko:{title:'EZPK 로고',subtitle:'연맹 공식 로고를 확인하고 저장하세요.',guideTitle:'로고 저장 안내',guideBody:'이미지를 열어 기기에 저장할 수 있습니다.',mobileGuide:'모바일: 이미지를 길게 누르기',pcGuide:'PC: 우클릭하여 저장',legacyDescription:'EZPK의 클래식 엠블럼입니다.',royalDescription:'EZPK의 로열 엠블럼입니다.',openImage:'이미지 열기',close:'닫기',footer:'Official Alliance Logo',section:'EZPK MEMBER',gateTitle:'연맹원 전용 페이지',gateLead:'로그인한 활성 연맹원만 로고를 확인하고 저장할 수 있습니다.',login:'로그인',signup:'회원가입'},
    en:{title:'EZPK LOGO',subtitle:'View and save the official alliance logos.',guideTitle:'SAVE GUIDE',guideBody:'Open an image to save it to your device.',mobileGuide:'Mobile: press and hold the image',pcGuide:'PC: right-click to save',legacyDescription:'The classic EZPK alliance emblem.',royalDescription:'The royal EZPK alliance emblem.',openImage:'OPEN IMAGE',close:'CLOSE',footer:'Official Alliance Logo',section:'EZPK MEMBER',gateTitle:'MEMBERS ONLY',gateLead:'Only signed-in active alliance members can view and save the logos.',login:'LOGIN',signup:'SIGN UP'},
    pt:{title:'LOGO EZPK',subtitle:'Veja e salve os logos oficiais da aliança.',guideTitle:'GUIA PARA SALVAR',guideBody:'Abra uma imagem para salvá-la no dispositivo.',mobileGuide:'Celular: toque e segure a imagem',pcGuide:'PC: clique com o botão direito',legacyDescription:'O emblema clássico da aliança EZPK.',royalDescription:'O emblema real da aliança EZPK.',openImage:'ABRIR IMAGEM',close:'FECHAR',footer:'Logo Oficial da Aliança',section:'MEMBRO EZPK',gateTitle:'SOMENTE MEMBROS',gateLead:'Apenas membros ativos conectados podem ver e salvar os logos.',login:'ENTRAR',signup:'CADASTRAR'},
    vi:{title:'LOGO EZPK',subtitle:'Xem và lưu logo chính thức của liên minh.',guideTitle:'HƯỚNG DẪN LƯU',guideBody:'Mở hình ảnh để lưu vào thiết bị.',mobileGuide:'Di động: nhấn giữ hình ảnh',pcGuide:'PC: nhấp chuột phải để lưu',legacyDescription:'Biểu tượng EZPK cổ điển.',royalDescription:'Biểu tượng EZPK hoàng gia.',openImage:'MỞ HÌNH ẢNH',close:'ĐÓNG',footer:'Logo Chính Thức',section:'THÀNH VIÊN EZPK',gateTitle:'CHỈ DÀNH CHO THÀNH VIÊN',gateLead:'Chỉ thành viên đang hoạt động và đã đăng nhập mới có thể xem và lưu logo.',login:'ĐĂNG NHẬP',signup:'ĐĂNG KÝ'},
    ar:{title:'شعار EZPK',subtitle:'اعرض شعارات التحالف الرسمية واحفظها.',guideTitle:'دليل الحفظ',guideBody:'افتح الصورة لحفظها على جهازك.',mobileGuide:'الهاتف: اضغط مطولًا على الصورة',pcGuide:'الكمبيوتر: انقر بزر الفأرة الأيمن',legacyDescription:'شعار تحالف EZPK الكلاسيكي.',royalDescription:'شعار تحالف EZPK الملكي.',openImage:'فتح الصورة',close:'إغلاق',footer:'شعار التحالف الرسمي',section:'عضو EZPK',gateTitle:'للأعضاء فقط',gateLead:'يمكن لأعضاء التحالف النشطين المسجلين فقط عرض الشعارات وحفظها.',login:'تسجيل الدخول',signup:'إنشاء حساب'},
    ja:{title:'EZPKロゴ',subtitle:'同盟の公式ロゴを確認して保存できます。',guideTitle:'保存ガイド',guideBody:'画像を開いて端末に保存できます。',mobileGuide:'モバイル：画像を長押し',pcGuide:'PC：右クリックで保存',legacyDescription:'EZPKのクラシックエンブレムです。',royalDescription:'EZPKのロイヤルエンブレムです。',openImage:'画像を開く',close:'閉じる',footer:'同盟公式ロゴ',section:'EZPKメンバー',gateTitle:'メンバー限定',gateLead:'ログイン中の有効な同盟メンバーのみロゴを確認・保存できます。',login:'ログイン',signup:'新規登録'},
    th:{title:'โลโก้ EZPK',subtitle:'ดูและบันทึกโลโก้อย่างเป็นทางการของพันธมิตร',guideTitle:'วิธีบันทึก',guideBody:'เปิดภาพเพื่อบันทึกลงในอุปกรณ์',mobileGuide:'มือถือ: แตะรูปภาพค้างไว้',pcGuide:'PC: คลิกขวาเพื่อบันทึก',legacyDescription:'ตราสัญลักษณ์ EZPK แบบคลาสสิก',royalDescription:'ตราสัญลักษณ์ EZPK แบบรอยัล',openImage:'เปิดรูปภาพ',close:'ปิด',footer:'โลโก้พันธมิตรอย่างเป็นทางการ',section:'สมาชิก EZPK',gateTitle:'เฉพาะสมาชิก',gateLead:'เฉพาะสมาชิกพันธมิตรที่เข้าสู่ระบบและใช้งานอยู่เท่านั้นที่ดูและบันทึกโลโก้ได้',login:'เข้าสู่ระบบ',signup:'สมัครสมาชิก'},
    'zh-tw':{title:'EZPK 標誌',subtitle:'查看並儲存聯盟官方標誌。',guideTitle:'儲存說明',guideBody:'開啟圖片後即可儲存至裝置。',mobileGuide:'手機：長按圖片',pcGuide:'電腦：按右鍵儲存',legacyDescription:'EZPK 經典聯盟徽章。',royalDescription:'EZPK 皇家聯盟徽章。',openImage:'開啟圖片',close:'關閉',footer:'聯盟官方標誌',section:'EZPK 成員',gateTitle:'成員專用',gateLead:'只有已登入的有效聯盟成員可以查看及儲存標誌。',login:'登入',signup:'註冊'}
  };
  const lang=()=>window.EZPKLanguage?.get?.()||localStorage.getItem('ezpk-lang-v5')||'en';
  const tx=()=>TEXT[lang()]||TEXT.en;
  function renderText(){const t=tx();document.querySelectorAll('[data-logo-k]').forEach(el=>{el.textContent=t[el.dataset.logoK]||''});document.querySelectorAll('[data-logo-gate]').forEach(el=>{el.textContent=t[el.dataset.logoGate]||''});$('[data-logo-login]').textContent=t.login;$('[data-logo-signup]').textContent=t.signup}
  function setAccess(state){const allowed=Boolean(state?.authenticated&&state?.member?.status==='active');$('#logoLock').hidden=allowed;$('#logoProtected').hidden=!allowed;if(allowed)document.querySelectorAll('[data-logo-src]').forEach(image=>{if(!image.src)image.src=image.dataset.logoSrc});renderText()}
  function openPreview(button){const modal=$('#logoPreviewModal');const image=$('#logoPreviewImage');const title=button.dataset.edition||'';image.src='./'+button.dataset.logoOpen;$('#logoPreviewTitle').textContent=title;$('#logoPreviewGuide').textContent=tx().guideBody;modal.hidden=false;document.body.style.overflow='hidden'}
  function closePreview(){$('#logoPreviewModal').hidden=true;document.body.style.overflow=''}
  document.querySelectorAll('[data-logo-open]').forEach(button=>button.addEventListener('click',()=>openPreview(button)));
  document.querySelectorAll('[data-logo-close],#logoPreviewClose,#logoPreviewDone').forEach(button=>button.addEventListener('click',closePreview));
  $('[data-logo-login]').addEventListener('click',()=>window.EZPKMemberAuth?.openLogin());
  window.addEventListener('ezpk-auth-ready',e=>setAccess(e.detail));window.addEventListener('ezpk-auth-change',e=>setAccess(e.detail));window.addEventListener('ezpk-language-change',renderText);
  renderText();setAccess(window.EZPKMemberAuth?.getState?.()||{});
})();
