const D=window.EZPK_DATA;
let lang=localStorage.getItem('ezpk-lang-v5')||'en';
if(!D[lang])lang='en';
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const RECORD={
ko:{recordTitle:'시즌 6 기록',recordLead:'시즌 6에서 함께 만든 순간들을 기록합니다.',finaleMessage:'<p>치열했던 모든 전투가 마침내 끝났습니다.</p><p>시즌 6을 완주한 모든 연맹과 전사들에게 축하와 경의를 보냅니다.</p><p>우리의 전투는 끝났지만, 함께 만든 이야기는 기록으로 남을 것입니다.</p><p>모두 수고하셨습니다. 다음 시즌에서 다시 만나요.</p>'},
en:{recordTitle:'Season 6 Records',recordLead:'A record of the moments we created together throughout Season 6.',finaleMessage:'<p>At last, every fierce battle has come to an end.</p><p>Congratulations and respect to every alliance and warrior who completed Season 6.</p><p>Our battles may be over, but the story we created together will remain in the records.</p><p>Great work, everyone. See you again next season.</p>'},
pt:{recordTitle:'Registros da Temporada 6',recordLead:'Um registro dos momentos que criamos juntos durante a Temporada 6.',finaleMessage:'<p>Finalmente, todas as batalhas intensas chegaram ao fim.</p><p>Parabéns e nosso respeito a todas as alianças e guerreiros que concluíram a Temporada 6.</p><p>Nossas batalhas terminaram, mas a história que criamos juntos permanecerá registrada.</p><p>Excelente trabalho a todos. Nos vemos na próxima temporada.</p>'},
vi:{recordTitle:'Kỷ niệm Mùa 6',recordLead:'Lưu lại những khoảnh khắc chúng ta đã cùng nhau tạo nên trong Mùa 6.',finaleMessage:'<p>Cuối cùng, mọi trận chiến khốc liệt đã kết thúc.</p><p>Xin chúc mừng và gửi lời kính trọng đến tất cả liên minh cùng các chiến binh đã hoàn thành Mùa 6.</p><p>Trận chiến đã khép lại, nhưng câu chuyện chúng ta cùng tạo nên sẽ còn được lưu giữ.</p><p>Mọi người đã vất vả rồi. Hẹn gặp lại ở mùa giải tiếp theo.</p>'},
ar:{recordTitle:'سجل الموسم 6',recordLead:'سجل للحظات التي صنعناها معًا طوال الموسم 6.',finaleMessage:'<p>انتهت أخيرًا جميع المعارك الشرسة.</p><p>نهنئ ونحيّي جميع التحالفات والمحاربين الذين أكملوا الموسم 6.</p><p>قد تكون معاركنا قد انتهت، لكن القصة التي صنعناها معًا ستبقى محفوظة في السجلات.</p><p>أحسنتم جميعًا. نراكم في الموسم القادم.</p>'},
ja:{recordTitle:'シーズン6 記録',recordLead:'シーズン6で共に作り上げた瞬間を記録します。',finaleMessage:'<p>激しかったすべての戦いが、ついに終わりました。</p><p>シーズン6を最後まで戦い抜いたすべての同盟と戦士たちに、祝福と敬意を送ります。</p><p>戦いは終わりましたが、共に作った物語は記録として残り続けます。</p><p>皆さん、本当にお疲れさまでした。次のシーズンでまた会いましょう。</p>'},
th:{recordTitle:'บันทึกซีซัน 6',recordLead:'บันทึกช่วงเวลาที่พวกเราร่วมกันสร้างขึ้นตลอดซีซัน 6',finaleMessage:'<p>ในที่สุด การต่อสู้อันดุเดือดทั้งหมดก็สิ้นสุดลงแล้ว</p><p>ขอแสดงความยินดีและความเคารพต่อทุกพันธมิตรและนักรบที่ผ่านซีซัน 6 จนจบ</p><p>แม้การต่อสู้ของเราจะจบลง แต่เรื่องราวที่เราสร้างร่วมกันจะยังคงถูกบันทึกไว้</p><p>ทุกคนทำได้ยอดเยี่ยมมาก แล้วพบกันใหม่ในซีซันหน้า</p>'},
'zh-tw':{recordTitle:'第 6 賽季紀錄',recordLead:'記錄我們在第 6 賽季共同創造的每一個時刻。',finaleMessage:'<p>所有激烈的戰鬥終於落下帷幕。</p><p>向完成第 6 賽季的所有聯盟與戰士致上祝賀與敬意。</p><p>戰鬥雖已結束，但我們共同創造的故事將永遠留在紀錄之中。</p><p>大家辛苦了，下個賽季再見。</p>'}
};
function render(){const c=D[lang],r=RECORD[lang]||RECORD.en;document.documentElement.lang=lang==='zh-tw'?'zh-Hant':lang;document.documentElement.dir=c.dir;document.body.classList.toggle('rtl',c.dir==='rtl');$('#flag').textContent=c.flag;$('#lname').textContent=c.name;$$('[data-k]').forEach(e=>{const k=e.dataset.k;if(c.ui[k]!=null)e.innerHTML=c.ui[k]});$$('[data-record-k]').forEach(e=>{const k=e.dataset.recordK;if(r[k]!=null)e.innerHTML=r[k]});localStorage.setItem('ezpk-lang-v5',lang)}
$('#langBtn').onclick=()=>$('#langMenu').hidden=!$('#langMenu').hidden;$$('#langMenu button').forEach(b=>b.onclick=()=>{lang=b.dataset.l;$('#langMenu').hidden=true;render()});$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');$$('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));render();
