(function(){
'use strict';
const D=window.EZPK_DATA||{};let lang=localStorage.getItem('ezpk-lang-v5')||'en';if(!D[lang])lang='en';
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const files={ko:'./season6-ko.webp',en:'./season6-en.webp',pt:'./season6-pt.webp',vi:'./season6-vi.webp',ar:'./season6-ar.webp',ja:'./season6-en.webp',th:'./season6-en.webp','zh-tw':'./season6-zh-tw.webp'};
const labels={
ko:{latest:'최신 정보',latestLead:'시즌6 최신정보를 확인하세요.',teams:'팀 편성',title:'팀 편성',lead:'팀 편성 현황을 확인하세요.',attack:'공격팀',defense:'방어팀',support:'지원팀',total:n=>`총 ${n}명`,empty:'현재 배정된 명단이 없습니다.',open:'팀 이미지 열기',updated:'업데이트',imageGuide:'팀 이미지 저장 안내',mobile:'📱 모바일: 이미지를 길게 눌러 저장하세요.',pc:'🖥️ PC: 이미지 위에서 마우스 오른쪽 버튼을 눌러 저장하세요.',close:'닫기',members:'팀 명단',strategyTitle:'팀별 세부 전략',strategyLead:'팀을 선택하여 세부 전략을 확인하세요.',attackStrategy:'공격팀 전략',defenseStrategy:'방어팀 전략',supportStrategy:'지원팀 전략',comingSoon:'준비중',commonTitle:'공통 오더',commonLead:'모든 팀원이 반드시 확인해야 할 공통 지침입니다.',battleMapTitle:'전장 맵',battleMapLead:'시즌 6 전장 맵과 주요 지역을 확인하세요.'},
en:{latest:'LATEST INFORMATION',latestLead:'Check the latest Season 6 information.',teams:'TEAM ASSIGNMENT',title:'TEAM ASSIGNMENT',lead:'Check the current team assignment status.',attack:'ATTACK TEAM',defense:'DEFENSE TEAM',support:'SUPPORT TEAM',total:n=>`Total ${n} Members`,empty:'No team members have been assigned yet.',open:'OPEN TEAM IMAGE',updated:'Updated',imageGuide:'How to save the team image',mobile:'📱 Mobile: Press and hold the image to save it.',pc:'🖥️ PC: Right-click the image and choose save.',close:'CLOSE',members:'TEAM MEMBERS',strategyTitle:'TEAM STRATEGY',strategyLead:'Select a team to view its detailed strategy.',attackStrategy:'ATTACK TEAM STRATEGY',defenseStrategy:'DEFENSE TEAM STRATEGY',supportStrategy:'SUPPORT TEAM STRATEGY',comingSoon:'COMING SOON',commonTitle:'COMMON ORDERS',commonLead:'Common instructions that every team member must check.',battleMapTitle:'BATTLEFIELD MAP',battleMapLead:'Check the Season 6 battlefield map and key areas.'},
vi:{latest:'THÔNG TIN MỚI NHẤT',latestLead:'Xem thông tin mới nhất của Mùa 7.',teams:'PHÂN CHIA ĐỘI',title:'PHÂN CHIA ĐỘI',lead:'Xem tình hình phân chia đội hiện tại.',attack:'ĐỘI TẤN CÔNG',defense:'ĐỘI PHÒNG THỦ',support:'ĐỘI HỖ TRỢ',total:n=>`Tổng ${n} thành viên`,empty:'Hiện chưa có thành viên nào được phân công.',open:'MỞ HÌNH ĐỘI',updated:'Cập nhật',imageGuide:'Hướng dẫn lưu hình đội',mobile:'📱 Di động: nhấn giữ hình ảnh để lưu.',pc:'🖥️ PC: nhấp chuột phải vào hình ảnh để lưu.',close:'ĐÓNG',members:'DANH SÁCH THÀNH VIÊN',strategyTitle:'CHIẾN THUẬT THEO ĐỘI',strategyLead:'Chọn một đội để xem chiến thuật chi tiết.',attackStrategy:'CHIẾN THUẬT ĐỘI TẤN CÔNG',defenseStrategy:'CHIẾN THUẬT ĐỘI PHÒNG THỦ',supportStrategy:'CHIẾN THUẬT ĐỘI HỖ TRỢ',comingSoon:'ĐANG CHUẨN BỊ',commonTitle:'MỆNH LỆNH CHUNG',commonLead:'Hướng dẫn chung mà mọi thành viên phải kiểm tra.',battleMapTitle:'BẢN ĐỒ CHIẾN TRƯỜNG',battleMapLead:'Xem bản đồ chiến trường Mùa 7 và các khu vực chính.'},
pt:{latest:'ÚLTIMAS INFORMAÇÕES',latestLead:'Confira as últimas informações da Temporada 7.',teams:'FORMAÇÃO DAS EQUIPES',title:'FORMAÇÃO DAS EQUIPES',lead:'Confira a situação atual da formação das equipes.',attack:'EQUIPE DE ATAQUE',defense:'EQUIPE DE DEFESA',support:'EQUIPE DE SUPORTE',total:n=>`Total: ${n} membros`,empty:'Nenhum membro foi atribuído ainda.',open:'ABRIR IMAGEM DA EQUIPE',updated:'Atualizado',imageGuide:'Como salvar a imagem da equipe',mobile:'📱 Celular: pressione e segure a imagem para salvar.',pc:'🖥️ PC: clique com o botão direito na imagem para salvar.',close:'FECHAR',members:'MEMBROS DA EQUIPE',strategyTitle:'ESTRATÉGIA POR EQUIPE',strategyLead:'Selecione uma equipe para ver a estratégia detalhada.',attackStrategy:'ESTRATÉGIA DA EQUIPE DE ATAQUE',defenseStrategy:'ESTRATÉGIA DA EQUIPE DE DEFESA',supportStrategy:'ESTRATÉGIA DA EQUIPE DE SUPORTE',comingSoon:'EM PREPARAÇÃO',commonTitle:'ORDENS GERAIS',commonLead:'Instruções gerais que todos os membros devem verificar.',battleMapTitle:'MAPA DO CAMPO DE BATALHA',battleMapLead:'Confira o mapa da Temporada 7 e as principais áreas.'},
ar:{latest:'أحدث المعلومات',latestLead:'اطّلع على أحدث معلومات الموسم السابع.',teams:'توزيع الفرق',title:'توزيع الفرق',lead:'اطّلع على حالة توزيع الفرق الحالية.',attack:'فريق الهجوم',defense:'فريق الدفاع',support:'فريق الدعم',total:n=>`إجمالي ${n} عضو`,empty:'لا يوجد أعضاء تم تعيينهم حالياً.',open:'فتح صورة الفريق',updated:'آخر تحديث',imageGuide:'طريقة حفظ صورة الفريق',mobile:'📱 الجوال: اضغط مطولاً على الصورة لحفظها.',pc:'🖥️ الكمبيوتر: انقر بزر الفأرة الأيمن على الصورة لحفظها.',close:'إغلاق',members:'أعضاء الفريق',strategyTitle:'الاستراتيجية التفصيلية لكل فريق',strategyLead:'اختر فريقاً لعرض استراتيجيته التفصيلية.',attackStrategy:'استراتيجية فريق الهجوم',defenseStrategy:'استراتيجية فريق الدفاع',supportStrategy:'استراتيجية فريق الدعم',comingSoon:'قيد الإعداد',commonTitle:'الأوامر العامة',commonLead:'تعليمات عامة يجب على جميع أعضاء الفرق مراجعتها.',battleMapTitle:'خريطة ساحة المعركة',battleMapLead:'اطّلع على خريطة الموسم السابع والمناطق الرئيسية.'},
'zh-tw':{latest:'最新資訊',latestLead:'查看第7賽季最新資訊。',teams:'隊伍編組',title:'隊伍編組',lead:'查看目前的隊伍編組狀況。',attack:'攻擊隊',defense:'防禦隊',support:'支援隊',total:n=>`共 ${n} 名成員`,empty:'目前尚未分配任何成員。',open:'開啟隊伍圖片',updated:'更新',imageGuide:'隊伍圖片儲存說明',mobile:'📱 手機：長按圖片即可儲存。',pc:'🖥️ 電腦：在圖片上按滑鼠右鍵儲存。',close:'關閉',members:'隊伍成員',strategyTitle:'各隊詳細戰略',strategyLead:'選擇隊伍以查看詳細戰略。',attackStrategy:'攻擊隊戰略',defenseStrategy:'防禦隊戰略',supportStrategy:'支援隊戰略',comingSoon:'準備中',commonTitle:'共同指令',commonLead:'所有隊員都必須確認的共同指引。',battleMapTitle:'戰場地圖',battleMapLead:'查看第7賽季戰場地圖與主要區域。'},
ja:{latest:'最新情報',latestLead:'シーズン6の最新情報を確認してください。',teams:'チーム編成',title:'チーム編成',lead:'現在のチーム編成状況を確認してください。',attack:'攻撃チーム',defense:'防衛チーム',support:'支援チーム',total:n=>`合計 ${n}名`,empty:'現在割り当てられたメンバーはいません。',open:'チーム画像を開く',updated:'更新',imageGuide:'チーム画像の保存方法',mobile:'📱 モバイル：画像を長押しして保存してください。',pc:'🖥️ PC：画像を右クリックして保存してください。',close:'閉じる',members:'チームメンバー',strategyTitle:'チーム別詳細戦略',strategyLead:'チームを選択して詳細戦略を確認してください。',attackStrategy:'攻撃チーム戦略',defenseStrategy:'防衛チーム戦略',supportStrategy:'支援チーム戦略',comingSoon:'準備中',commonTitle:'共通指令',commonLead:'全チームメンバーが必ず確認する共通指針です。',battleMapTitle:'戦場マップ',battleMapLead:'シーズン6の戦場マップと主要エリアを確認してください。'},
th:{latest:'ข้อมูลล่าสุด',latestLead:'ตรวจสอบข้อมูลล่าสุดของซีซัน 6',teams:'การจัดทีม',title:'การจัดทีม',lead:'ตรวจสอบสถานะการจัดทีมปัจจุบัน',attack:'ทีมโจมตี',defense:'ทีมป้องกัน',support:'ทีมสนับสนุน',total:n=>`ทั้งหมด ${n} คน`,empty:'ขณะนี้ยังไม่มีรายชื่อที่ได้รับมอบหมาย',open:'เปิดรูปทีม',updated:'อัปเดต',imageGuide:'วิธีบันทึกรูปทีม',mobile:'📱 มือถือ: กดรูปค้างไว้เพื่อบันทึก',pc:'🖥️ PC: คลิกขวาที่รูปเพื่อบันทึก',close:'ปิด',members:'สมาชิกทีม',strategyTitle:'กลยุทธ์แยกตามทีม',strategyLead:'เลือกทีมเพื่อดูรายละเอียดกลยุทธ์',attackStrategy:'กลยุทธ์ทีมโจมตี',defenseStrategy:'กลยุทธ์ทีมป้องกัน',supportStrategy:'กลยุทธ์ทีมสนับสนุน',comingSoon:'กำลังเตรียม',commonTitle:'คำสั่งร่วม',commonLead:'แนวทางร่วมที่สมาชิกทุกทีมต้องตรวจสอบ',battleMapTitle:'แผนที่สนามรบ',battleMapLead:'ตรวจสอบแผนที่สนามรบซีซัน 6 และพื้นที่สำคัญ'}
};

const heroInfo={
  ko:{
    title:'시즌 6 S 영웅 최신정보',lead:'영웅 카드를 선택하여 역할과 투자 우선순위를 간단히 확인하세요.',quickTitle:'빠른 선택 가이드',quick:'보스와 PvE는 사우스, PvP와 광역 전투는 엘라, 팀 지원과 장기전은 메이슨을 추천합니다.',
    labels:{role:'주요 역할',content:'추천 콘텐츠',strengths:'핵심 장점',caution:'주의할 점',priority:'투자 추천'},
    heroes:{
      south:{name:'사우스',role:'메인 DPS',card:'보스전에 강한 단일 딜러',summary:'강력한 단일 대상 화력을 가진 시즌 6 핵심 딜러입니다.',tags:['보스','레이드','PvE'],content:'시즌 보스 · 레이드 · PvE',strengths:['높은 단일 대상 화력','보스 콘텐츠 활용도 우수','안정적인 딜 성능'],caution:'광역 전투에서는 효율이 상대적으로 낮을 수 있습니다.',rating:'★★★★★ 최우선 투자',priority:'시즌 6 주력 딜러가 필요하다면 가장 먼저 육성하세요.'},
      ella:{name:'엘라',role:'광역 DPS',card:'PvP에 강한 광역 딜러',summary:'다수의 적을 상대하는 전투와 PvP에 유리한 광역 딜러입니다.',tags:['PvP','광역 전투','시즌 사냥'],content:'PvP · 다수 전투 · 시즌 사냥',strengths:['광역 공격 능력이 우수함','다수의 적을 빠르게 처리','PvP 활용도가 높음'],caution:'단일 보스 화력은 사우스보다 낮을 수 있습니다.',rating:'★★★★☆ 적극 투자',priority:'PvP와 광역 전투를 중시한다면 우선적으로 육성하세요.'},
      mason:{name:'메이슨',role:'서포터',card:'팀을 강화하는 지원형 영웅',summary:'아군의 전투 효율과 안정성을 높여주는 시즌 6 지원형 영웅입니다.',tags:['팀 전투','장기전','보스'],content:'팀 전투 · 장기전 · 보스',strengths:['아군 지원 효과 제공','팀 전체의 전투 안정성 향상','장기전 활용도 우수'],caution:'단독 공격 성능은 낮고 조합에 따라 효율 차이가 있습니다.',rating:'★★★★☆ 조합형 투자',priority:'팀 지원이 필요하거나 장기전 조합을 운영할 때 육성하세요.'}
    }
  },
  en:{
    title:'SEASON 6 S HERO INFORMATION',lead:'Select a hero card to quickly check their role and investment priority.',quickTitle:'QUICK PICK GUIDE',quick:'Choose South for bosses and PvE, Ella for PvP and area damage, and Mason for team support and long battles.',
    labels:{role:'PRIMARY ROLE',content:'RECOMMENDED CONTENT',strengths:'KEY STRENGTHS',caution:'THINGS TO NOTE',priority:'INVESTMENT PRIORITY'},
    heroes:{
      south:{name:'South',role:'Main DPS',card:'Single-target boss specialist',summary:'A core Season 6 damage dealer with powerful single-target damage.',tags:['Boss','Raid','PvE'],content:'Season Boss · Raid · PvE',strengths:['High single-target damage','Excellent value in boss content','Stable damage performance'],caution:'His efficiency may be lower in large-scale area battles.',rating:'★★★★★ TOP PRIORITY',priority:'Build him first if you need a primary Season 6 damage dealer.'},
      ella:{name:'Ella',role:'Area DPS',card:'Powerful PvP area attacker',summary:'An area damage dealer suited for PvP and battles against multiple enemies.',tags:['PvP','Area Battle','Season Hunt'],content:'PvP · Multi-target battles · Season hunting',strengths:['Excellent area damage','Clears multiple enemies quickly','Strong PvP utility'],caution:'Her single-target boss damage may be lower than South’s.',rating:'★★★★☆ HIGH PRIORITY',priority:'Prioritize her if PvP and area combat are your main focus.'},
      mason:{name:'Mason',role:'Support',card:'Team-focused support hero',summary:'A Season 6 support hero who improves team efficiency and stability.',tags:['Team Battle','Long Battle','Boss'],content:'Team battles · Long battles · Boss',strengths:['Provides team support effects','Improves overall team stability','Strong in prolonged battles'],caution:'His solo damage is low and his value depends on the team composition.',rating:'★★★★☆ TEAM-BASED',priority:'Build him when your lineup needs stronger support or long-battle stability.'}
    }
  },
  vi:{
    title:'THÔNG TIN TƯỚNG S MÙA 6',lead:'Chọn thẻ tướng để xem nhanh vai trò và mức ưu tiên đầu tư.',quickTitle:'HƯỚNG DẪN CHỌN NHANH',quick:'Chọn South cho Boss và PvE, Ella cho PvP và sát thương diện rộng, Mason cho hỗ trợ đội và trận đấu dài.',
    labels:{role:'VAI TRÒ CHÍNH',content:'NỘI DUNG ĐỀ XUẤT',strengths:'ƯU ĐIỂM CHÍNH',caution:'LƯU Ý',priority:'ƯU TIÊN ĐẦU TƯ'},
    heroes:{
      south:{name:'South',role:'DPS chính',card:'Chuyên gia Boss đơn mục tiêu',summary:'DPS chủ lực Mùa 6 với sát thương đơn mục tiêu mạnh.',tags:['Boss','Đột kích','PvE'],content:'Boss Mùa · Đột kích · PvE',strengths:['Sát thương đơn mục tiêu cao','Rất hiệu quả trong nội dung Boss','Sát thương ổn định'],caution:'Hiệu quả có thể thấp hơn trong các trận đánh diện rộng.',rating:'★★★★★ ƯU TIÊN CAO NHẤT',priority:'Nên nâng trước nếu cần DPS chủ lực cho Mùa 6.'},
      ella:{name:'Ella',role:'DPS diện rộng',card:'DPS diện rộng mạnh trong PvP',summary:'Tướng gây sát thương diện rộng phù hợp PvP và chiến đấu với nhiều mục tiêu.',tags:['PvP','Diện rộng','Săn Mùa'],content:'PvP · Đa mục tiêu · Săn Mùa',strengths:['Sát thương diện rộng tốt','Hạ nhiều mục tiêu nhanh','Hữu dụng cao trong PvP'],caution:'Sát thương Boss đơn mục tiêu có thể thấp hơn South.',rating:'★★★★☆ ƯU TIÊN CAO',priority:'Ưu tiên nếu tập trung vào PvP và chiến đấu diện rộng.'},
      mason:{name:'Mason',role:'Hỗ trợ',card:'Tướng hỗ trợ tăng sức mạnh đội',summary:'Tướng hỗ trợ Mùa 6 giúp tăng hiệu quả và độ ổn định của đội.',tags:['Đội hình','Trận dài','Boss'],content:'Chiến đấu đội · Trận dài · Boss',strengths:['Cung cấp hiệu ứng hỗ trợ','Tăng độ ổn định của đội','Mạnh trong trận kéo dài'],caution:'Sát thương đơn lẻ thấp và phụ thuộc vào đội hình.',rating:'★★★★☆ THEO ĐỘI HÌNH',priority:'Nâng khi đội hình cần hỗ trợ hoặc khả năng đánh lâu dài.'}
    }
  },
  pt:{
    title:'INFORMAÇÕES DOS HERÓIS S DA TEMPORADA 6',lead:'Selecione um herói para conferir rapidamente sua função e prioridade de investimento.',quickTitle:'GUIA DE ESCOLHA RÁPIDA',quick:'Escolha South para chefes e PvE, Ella para PvP e dano em área, e Mason para suporte e batalhas longas.',
    labels:{role:'FUNÇÃO PRINCIPAL',content:'CONTEÚDO RECOMENDADO',strengths:'PONTOS FORTES',caution:'ATENÇÃO',priority:'PRIORIDADE DE INVESTIMENTO'},
    heroes:{
      south:{name:'South',role:'DPS principal',card:'Especialista em alvo único',summary:'DPS central da Temporada 6 com forte dano em alvo único.',tags:['Chefe','Raid','PvE'],content:'Chefe da temporada · Raid · PvE',strengths:['Alto dano em alvo único','Excelente em conteúdo de chefe','Dano estável'],caution:'Pode ter menor eficiência em batalhas de área.',rating:'★★★★★ PRIORIDADE MÁXIMA',priority:'Evolua primeiro se precisar de um DPS principal para a Temporada 6.'},
      ella:{name:'Ella',role:'DPS em área',card:'Atacante em área forte no PvP',summary:'DPS em área ideal para PvP e combates contra vários inimigos.',tags:['PvP','Área','Caça'],content:'PvP · Múltiplos alvos · Caça da temporada',strengths:['Ótimo dano em área','Elimina vários inimigos rapidamente','Alta utilidade no PvP'],caution:'O dano em chefe único pode ser menor que o de South.',rating:'★★★★☆ ALTA PRIORIDADE',priority:'Priorize se PvP e combate em área forem seu foco.'},
      mason:{name:'Mason',role:'Suporte',card:'Herói de suporte para a equipe',summary:'Herói de suporte da Temporada 6 que melhora a eficiência e a estabilidade da equipe.',tags:['Equipe','Batalha longa','Chefe'],content:'Batalha em equipe · Batalha longa · Chefe',strengths:['Oferece efeitos de suporte','Melhora a estabilidade da equipe','Bom em batalhas prolongadas'],caution:'Seu dano solo é baixo e depende da composição.',rating:'★★★★☆ DEPENDE DA EQUIPE',priority:'Evolua quando a equipe precisar de suporte ou mais estabilidade.'}
    }
  },
  ar:{
    title:'معلومات أبطال الفئة S للموسم 6',lead:'اختر بطاقة البطل لعرض دوره وأولوية تطويره بسرعة.',quickTitle:'دليل الاختيار السريع',quick:'اختر South للزعماء وPvE، وElla لـPvP والضرر الجماعي، وMason لدعم الفريق والمعارك الطويلة.',
    labels:{role:'الدور الرئيسي',content:'المحتوى الموصى به',strengths:'أهم المميزات',caution:'ملاحظات',priority:'أولوية التطوير'},
    heroes:{
      south:{name:'South',role:'مهاجم رئيسي',card:'متخصص في ضرر الهدف الواحد',summary:'مهاجم أساسي في الموسم 6 يتميز بضرر قوي على هدف واحد.',tags:['زعيم','غارة','PvE'],content:'زعيم الموسم · الغارات · PvE',strengths:['ضرر مرتفع على هدف واحد','ممتاز ضد الزعماء','أداء هجومي ثابت'],caution:'قد تكون كفاءته أقل في المعارك الجماعية واسعة النطاق.',rating:'★★★★★ أولوية قصوى',priority:'طوّره أولاً إذا كنت تحتاج إلى مهاجم رئيسي للموسم 6.'},
      ella:{name:'Ella',role:'ضرر جماعي',card:'مهاجمة جماعية قوية في PvP',summary:'بطلة ضرر جماعي مناسبة لـPvP ومواجهة عدة أعداء.',tags:['PvP','ضرر جماعي','صيد الموسم'],content:'PvP · قتال متعدد الأهداف · صيد الموسم',strengths:['ضرر جماعي ممتاز','تهزم عدة أعداء بسرعة','فعالة جداً في PvP'],caution:'قد يكون ضررها ضد زعيم واحد أقل من South.',rating:'★★★★☆ أولوية عالية',priority:'أعطها الأولوية إذا كان تركيزك على PvP والقتال الجماعي.'},
      mason:{name:'Mason',role:'دعم',card:'بطل دعم لتعزيز الفريق',summary:'بطل دعم في الموسم 6 يرفع كفاءة الفريق واستقراره.',tags:['فريق','معركة طويلة','زعيم'],content:'قتال جماعي · معارك طويلة · زعماء',strengths:['يوفر تأثيرات دعم للفريق','يرفع استقرار التشكيلة','ممتاز في المعارك الطويلة'],caution:'ضرره الفردي منخفض وتعتمد فعاليته على التشكيلة.',rating:'★★★★☆ حسب التشكيلة',priority:'طوّره عندما يحتاج فريقك إلى دعم أو ثبات في المعارك الطويلة.'}
    }
  },
  'zh-tw':{
    title:'第6賽季 S 級英雄最新資訊',lead:'選擇英雄卡片，快速查看定位與培養優先度。',quickTitle:'快速選擇指南',quick:'Boss與PvE選South，PvP與範圍戰鬥選Ella，團隊支援與長時間戰鬥選Mason。',
    labels:{role:'主要定位',content:'推薦內容',strengths:'核心優點',caution:'注意事項',priority:'培養優先度'},
    heroes:{
      south:{name:'South',role:'主力輸出',card:'Boss單體輸出專家',summary:'擁有強大單體傷害的第6賽季核心輸出英雄。',tags:['Boss','團隊副本','PvE'],content:'賽季Boss · 團隊副本 · PvE',strengths:['單體傷害高','Boss內容表現優秀','輸出穩定'],caution:'在大範圍群體戰鬥中的效率可能較低。',rating:'★★★★★ 最優先',priority:'需要第6賽季主力輸出時，建議最先培養。'},
      ella:{name:'Ella',role:'範圍輸出',card:'PvP強力範圍攻擊手',summary:'適合PvP與多目標戰鬥的範圍輸出英雄。',tags:['PvP','範圍戰鬥','賽季狩獵'],content:'PvP · 多目標戰鬥 · 賽季狩獵',strengths:['範圍傷害優秀','能快速處理多個敵人','PvP實用性高'],caution:'單體Boss傷害可能低於South。',rating:'★★★★☆ 積極培養',priority:'重視PvP與範圍戰鬥時可優先培養。'},
      mason:{name:'Mason',role:'輔助',card:'強化隊伍的支援英雄',summary:'提升隊伍效率與穩定性的第6賽季輔助英雄。',tags:['團隊戰鬥','持久戰','Boss'],content:'團隊戰鬥 · 持久戰 · Boss',strengths:['提供隊伍支援效果','提升整體穩定性','持久戰表現優秀'],caution:'單獨輸出較低，效果會受到隊伍配置影響。',rating:'★★★★☆ 視隊伍培養',priority:'隊伍需要支援或持久戰能力時再培養。'}
    }
  }
};
heroInfo.ja=heroInfo.en;heroInfo.th=heroInfo.en;
const heroImages={south:'south',ella:'ella',mason:'mason'};
let activeHero='south';

let teamData={lastUpdated:'',teams:{attack:[],defense:[],support:[]}};
let activeStrategyTeam='attack';
function L(){return labels[lang]||labels.en}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function loadTeams(){try{const r=await fetch('../data/season6-teams.json?v='+Date.now(),{cache:'no-store'});if(r.ok)teamData=await r.json()}catch(e){}renderTeams()}
function fitNames(){requestAnimationFrame(()=>{$$('.team-member-name').forEach(el=>{let size=13;el.style.fontSize=size+'px';while(size>9&&(el.scrollHeight>el.clientHeight+1||el.scrollWidth>el.clientWidth+1)){size-=.5;el.style.fontSize=size+'px'}})})}
const teamIcons={
attack:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14.7 3.3 20.7 9.3 9.8 20.2 4.5 21.5 5.8 16.2 16.7 5.3 14.7 3.3Z"/><path d="m4 4 5 5M3 3l3.2 1.1L4.1 6.2 3 3Z"/></svg>',
defense:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2.8 20 6v5.7c0 5.1-3.2 8.1-8 9.5-4.8-1.4-8-4.4-8-9.5V6l8-3.2Z"/><path d="M12 6v11"/></svg>',
support:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9.2 3h5.6v6.2H21v5.6h-6.2V21H9.2v-6.2H3V9.2h6.2V3Z"/></svg>'
};

function H(){return heroInfo[lang]||heroInfo.en}
function renderHeroes(){
  const h=H(),keys=['south','ella','mason'];
  $('#heroInfoTitle').textContent=h.title;
  $('#heroInfoLead').textContent=h.lead;
  $('#heroQuickTitle').textContent=h.quickTitle;
  $('#heroQuickText').textContent=h.quick;
  $('#heroCards').innerHTML=keys.map(k=>{const x=h.heroes[k],active=k===activeHero;return `<button class="hero-card hero-card--${k}${active?' is-active':''}" type="button" role="tab" aria-selected="${active}" data-hero="${k}"><span class="hero-card-media"><img src="./assets/heroes/${heroImages[k]}-card.webp?v=1090" alt="${esc(x.name)}" loading="lazy"></span><span class="hero-card-copy"><h3>${esc(x.name)}</h3><p>${esc(x.card)}</p><span class="hero-card-rank">${esc(x.rating)}</span></span></button>`}).join('');
  const x=h.heroes[activeHero],l=h.labels;
  $('#heroDetail').className=`hero-detail hero-detail--${activeHero}`;
  $('#heroDetail').innerHTML=`<div class="hero-detail-media"><img src="./assets/heroes/${heroImages[activeHero]}.webp?v=1090" alt="${esc(x.name)}" loading="lazy"></div><div class="hero-detail-content"><span class="hero-detail-kicker">SEASON 6 · S HERO</span><h3>${esc(x.name)}</h3><p class="hero-summary">${esc(x.summary)}</p><div class="hero-tags">${x.tags.map(t=>`<span class="hero-tag">${esc(t)}</span>`).join('')}</div><div class="hero-facts"><section class="hero-fact"><h4>${esc(l.role)}</h4><p>${esc(x.role)}</p></section><section class="hero-fact"><h4>${esc(l.content)}</h4><p>${esc(x.content)}</p></section><section class="hero-fact"><h4>${esc(l.strengths)}</h4><ul>${x.strengths.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></section><section class="hero-fact"><h4>${esc(l.caution)}</h4><p>${esc(x.caution)}</p></section><section class="hero-fact hero-priority"><h4>${esc(l.priority)}</h4><strong>${esc(x.rating)}</strong><span>${esc(x.priority)}</span></section></div></div>`;
  $$('[data-hero]').forEach(btn=>btn.onclick=()=>{activeHero=btn.dataset.hero;renderHeroes();if(window.matchMedia('(max-width:820px)').matches)$('#heroDetail').scrollIntoView({behavior:'smooth',block:'start'})});
}

function renderTeams(){const l=L();$('#teamAssignmentTitle').textContent=l.title;$('#teamAssignmentLead').textContent=l.lead;const updated=$('#teamUpdated');if(teamData.lastUpdated){updated.hidden=false;updated.textContent=`${l.updated}: ${teamData.lastUpdated}`}else updated.hidden=true;$('#teamCards').innerHTML=['attack','defense','support'].map(k=>{const list=Array.isArray(teamData?.teams?.[k])?teamData.teams[k]:[];return `<article class="team-card team-card--${k}" data-team-card="${k}"><header class="team-card-head"><div class="team-card-identity"><span class="team-card-icon">${teamIcons[k]}</span><div class="team-card-title"><h3>${l[k]}</h3><span>SEASON 6</span></div></div><p>${l.total(list.length)}</p></header><div class="team-member-grid">${list.length?list.map(n=>`<div class="team-member-cell"><span class="team-member-name" title="${esc(n)}">${esc(n)}</span></div>`).join(''):`<p class="team-empty">${l.empty}</p>`}</div><div class="team-card-actions"><button class="team-open-image" type="button" data-open-team="${k}" ${list.length?'':'hidden'}>${l.open}</button></div></article>`}).join('');$$('[data-open-team]').forEach(b=>b.onclick=()=>openTeamImage(b.dataset.openTeam));fitNames()}
function renderStrategy(){const l=L(),k=activeStrategyTeam,panel=$('#strategyPanel');if(!panel)return;panel.classList.remove('strategy-panel--attack','strategy-panel--defense','strategy-panel--support');panel.classList.add(`strategy-panel--${k}`);$$('[data-strategy-team]').forEach(btn=>{const active=btn.dataset.strategyTeam===k;btn.classList.toggle('is-active',active);btn.setAttribute('aria-selected',String(active));btn.textContent=l[btn.dataset.strategyTeam]});$('#teamStrategyTitle').textContent=l.strategyTitle;$('#teamStrategyLead').textContent=l.strategyLead;$('#strategyContentTitle').textContent=l[`${k}Strategy`];$('#strategyComingSoon').textContent=l.comingSoon;$('#strategyIcon').innerHTML=teamIcons[k];$('#commonOrdersTitle').textContent=l.commonTitle;$('#commonOrdersLead').textContent=l.commonLead;$('#commonOrdersBoxTitle').textContent=l.commonTitle;$('#commonOrdersComingSoon').textContent=l.comingSoon}
function createTeamImage(k){const l=L(),names=teamData?.teams?.[k]||[],accent={attack:'#d85a5a',defense:'#5f8fe5',support:'#4fbd83'}[k]||'#d9bb65',cols=5,cellW=250,cellH=92,pad=70,headerH=230,rows=Math.ceil(names.length/cols),w=pad*2+cols*cellW,h=headerH+pad+Math.max(rows,1)*cellH+pad;const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle='#070b12';x.fillRect(0,0,w,h);x.strokeStyle=accent;x.lineWidth=3;x.strokeRect(24,24,w-48,h-48);x.textAlign='center';x.fillStyle=accent;x.font='700 25px Arial';x.fillText('SERVER 322 · EZPK ALLIANCE',w/2,72);x.fillStyle=accent;x.font='800 55px Arial';x.fillText(l[k],w/2,140);x.fillStyle='#aeb8c6';x.font='600 25px Arial';x.fillText(l.total(names.length),w/2,188);names.forEach((name,i)=>{const col=i%cols,row=Math.floor(i/cols),cx=pad+col*cellW,cy=headerH+row*cellH;x.fillStyle='#101824';x.strokeStyle='#2d3a4f';x.lineWidth=2;x.beginPath();x.roundRect(cx+5,cy+5,cellW-10,cellH-10,10);x.fill();x.stroke();x.fillStyle='#f1f4f8';let fs=24;x.font=`700 ${fs}px Arial`;while(fs>15&&x.measureText(name).width>cellW-30){fs--;x.font=`700 ${fs}px Arial`}const words=String(name).split(' ');let lines=[name];if(x.measureText(name).width>cellW-30&&words.length>1){let a='',b='';for(const word of words){if(x.measureText((a+' '+word).trim()).width<=cellW-30)a=(a+' '+word).trim();else b=(b+' '+word).trim()}lines=[a,b].filter(Boolean)}if(lines.length===1)x.fillText(lines[0],cx+cellW/2,cy+56);else{const lh=fs+5;x.fillText(lines[0],cx+cellW/2,cy+45-lh/2);x.fillText(lines[1],cx+cellW/2,cy+45+lh/2)}});return c.toDataURL('image/png')}
function openTeamImage(k){const l=L(),url=createTeamImage(k);$('#teamImageTitle').textContent=l[k];$('#teamImageGuideTitle').textContent=l.imageGuide;$('#teamImageGuideMobile').textContent=l.mobile;$('#teamImageGuidePc').textContent=l.pc;$('#teamImagePreview').src=url;$('#teamImageDone').textContent=l.close;$('#teamImageModal').hidden=false;document.body.classList.add('team-modal-open');setTimeout(()=>$('#teamImageClose').focus(),0)}
function closeTeamImage(){$('#teamImageModal').hidden=true;$('#teamImagePreview').removeAttribute('src');document.body.classList.remove('team-modal-open')}
function render(){const c=D[lang]||D.en,l=L();document.documentElement.lang=lang;document.documentElement.dir=c.dir||'ltr';document.body.classList.toggle('rtl',(c.dir||'ltr')==='rtl');if($('#flag'))$('#flag').textContent=c.flag||'';if($('#lname'))$('#lname').textContent=c.name||'';$('#season6Img').src=(files[lang]||files.en)+'?v=982';$$('[data-k]').forEach(e=>{const k=e.dataset.k;if(c.ui?.[k]!=null)e.innerHTML=c.ui[k]});$('#latestInfoTitle').textContent=l.latest;$('#latestInfoLead').textContent=l.latestLead;$('#battleMapTitle').textContent=l.battleMapTitle;$('#battleMapLead').textContent=l.battleMapLead;$('#battleMapComingSoon').textContent=l.comingSoon;localStorage.setItem('ezpk-lang-v5',lang);renderHeroes();renderTeams();renderStrategy()}
$$('[data-strategy-team]').forEach(btn=>btn.onclick=()=>{activeStrategyTeam=btn.dataset.strategyTeam;renderStrategy()});
$('#langBtn').onclick=()=>$('#langMenu').hidden=!$('#langMenu').hidden;$$('#langMenu button').forEach(b=>b.onclick=()=>{lang=b.dataset.l;if(!labels[lang])lang='en';$('#langMenu').hidden=true;render()});$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');$$('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));$$('[data-team-close]').forEach(el=>el.onclick=closeTeamImage);$('#teamImageClose').onclick=closeTeamImage;$('#teamImageDone').onclick=closeTeamImage;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#teamImageModal').hidden)closeTeamImage()});render();loadTeams();
})();
