const D=window.EZPK_DATA;const PASSWORD='322EZPK';let lang=localStorage.getItem('ezpk-lang-v5')||'en',team='tower';if(!D[lang])lang='en';const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const LINEUP={
 tower:[],
 a:['Horang','Bot','Purple','Pro','Shindol','Lajin','Katreeya'],
 b:['GB MURAD1907','GB SIWOO','GB Bongluxury','SOS Luu Dan','nup di','GB Long Huy Diet','GB Trung Hi','GBmt nhokkk','GB i`m ok','Lu','GB Kit Kat'],
 support:['NOX','LoKi','FoxxyScorpio','Just A','Selenn£']
};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){const c=D[lang];document.documentElement.lang=lang==='zh-tw'?'zh-Hant':lang;document.documentElement.dir=c.dir;document.body.classList.toggle('rtl',c.dir==='rtl');$('#flag').textContent=c.flag;$('#lname').textContent=c.name;$$('[data-k]').forEach(e=>{const k=e.dataset.k;if(c.ui[k]!=null)e.innerHTML=c.ui[k]});$$('[data-placeholder-k]').forEach(e=>e.placeholder=c.ui[e.dataset.placeholderK]||'');$('#overall').innerHTML=c.overall.map(x=>`<li>${x}</li>`).join('');$('#ordersGrid').innerHTML=c.orders.map((x,i)=>`<div class="order"><div class="num">${i+1}</div><div>${x}</div></div>`).join('');renderLineup();renderTeam();localStorage.setItem('ezpk-lang-v5',lang)}
function renderLineup(){const c=D[lang],defs=[['tower',c.ui.tower,'#1d8cff'],['a',c.ui.a,'#e24335'],['b',c.ui.b,'#2ab94c'],['support',c.ui.support,'#e1a916']];$('#lineupGrid').innerHTML=defs.map(([key,title,accent])=>{const names=LINEUP[key];const body=key==='tower'?`<div class="tower-all"><strong>${c.ui.allAllianceMembers}</strong><p>${c.ui.towerRule}</p></div>`:`<div class="member-list">${names.map((n,i)=>`<div class="lineup-member" dir="ltr"><span>${String(i+1).padStart(2,'0')}</span><strong>${esc(n)}</strong></div>`).join('')}</div>`;return `<article class="lineup-card lineup-${key}" style="--team-accent:${accent}"><header><span class="team-dot"></span><h3>${title}</h3><small>${key==='tower'?c.ui.allAllianceMembers:`${c.ui.teamMembers} · ${names.length}`}</small></header>${body}</article>`}).join('')}
function renderTeam(){const t=D[lang].teams[team];$('#team').innerHTML=`<div class="teamcard" style="--accent:${t.accent}"><aside class="quick"><small>${D[lang].ui.quickSummary||'QUICK SUMMARY'}</small><h3>${t.title}</h3><ul>${t.quick.map(x=>`<li>${x}</li>`).join('')}</ul></aside><div class="details">${t.sections.map(([h,b])=>`<div class="detail"><h4>${h}</h4>${Array.isArray(b)?`<ul>${b.map(x=>`<li>${x}</li>`).join('')}</ul>`:`<p>${b}</p>`}</div>`).join('')}</div></div>`}
function unlock(){sessionStorage.setItem('ezpk-season6-auth','1');$('#seasonLock').hidden=true;$('#seasonContent').hidden=false;window.scrollTo({top:0})}function lock(){sessionStorage.removeItem('ezpk-season6-auth');$('#seasonContent').hidden=true;$('#seasonLock').hidden=false;$('#seasonPassword').value=''}
$('#lockForm').addEventListener('submit',e=>{e.preventDefault();if($('#seasonPassword').value===PASSWORD){$('#lockError').textContent='';unlock()}else $('#lockError').textContent=D[lang].ui.wrongPassword});$('#lockPageBtn').onclick=lock;$('#langBtn').onclick=()=>$('#langMenu').hidden=!$('#langMenu').hidden;$$('#langMenu button').forEach(b=>b.onclick=()=>{lang=b.dataset.l;$('#langMenu').hidden=true;render()});$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');team=b.dataset.t;renderTeam()});$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');$$('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));render();if(sessionStorage.getItem('ezpk-season6-auth')==='1')unlock();
