const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let data={lastUpdated:'',members:[]},sha='';
const cfg=()=>({owner:$('#owner').value.trim(),repo:$('#repo').value.trim(),branch:$('#branch').value.trim()||'main',path:$('#path').value.trim(),token:$('#token').value.trim()});
function setStatus(msg,type=''){const e=$('#status');e.textContent=msg;e.className='status '+type}
function normalizeMember(m){return{rank:String(m.rank||m.Rank||'R1').toUpperCase(),nickname:String(m.nickname||m.Nickname||'').trim(),ind:Number(m.ind??m.IND??m['Shelter Level']??0),power:Number(String(m.power??m['Combat Power']??0).replaceAll(',',''))}}
async function loadLocal(){const r=await fetch('../data/members.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('로컬 데이터를 불러오지 못했습니다.');data=await r.json();data.members=(data.members||[]).map(normalizeMember);$('#lastUpdated').value=data.lastUpdated||'';render()}
function filtered(){const q=$('#search').value.trim().toLowerCase(),rank=$('#rank').value;return data.members.map((m,i)=>({...m,_i:i})).filter(m=>(rank==='ALL'||m.rank===rank)&&m.nickname.toLowerCase().includes(q))}
function render(){const list=filtered();$('#count').textContent=`표시 ${list.length}명 / 전체 ${data.members.length}명`;$('#memberRows').innerHTML=list.map(m=>`<tr data-i="${m._i}"><td class="rank-cell"><select data-f="rank">${['R5','R4','R3','R2','R1'].map(r=>`<option ${r===m.rank?'selected':''}>${r}</option>`).join('')}</select></td><td><input data-f="nickname" value="${esc(m.nickname)}"></td><td class="ind-cell"><input data-f="ind" type="number" min="0" value="${m.ind}"></td><td class="power-cell"><input data-f="power" inputmode="numeric" value="${m.power}"></td><td><button class="remove">삭제</button></td></tr>`).join('');$$('#memberRows tr').forEach(tr=>{const i=Number(tr.dataset.i);tr.querySelectorAll('[data-f]').forEach(el=>el.oninput=()=>{const f=el.dataset.f;data.members[i][f]=(f==='ind'||f==='power')?Number(String(el.value).replaceAll(',','')):el.value;tr.classList.add('dirty')});tr.querySelector('.remove').onclick=()=>{if(confirm(`${data.members[i].nickname} 멤버를 삭제할까요?`)){data.members.splice(i,1);render()}}})}
function $$(s){return document.querySelectorAll(s)}
function payload(){return{lastUpdated:$('#lastUpdated').value.trim(),members:data.members.map(normalizeMember)}}
function b64EncodeUnicode(str){const bytes=new TextEncoder().encode(str);let bin='';bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin)}
function b64DecodeUnicode(b64){const bin=atob(b64.replace(/\n/g,''));const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
async function githubGet(){const c=cfg();if(!c.token)throw new Error('GitHub Token을 입력하세요.');const url=`https://api.github.com/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}/contents/${c.path}?ref=${encodeURIComponent(c.branch)}`;const r=await fetch(url,{headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${c.token}`,'X-GitHub-Api-Version':'2022-11-28'}});if(!r.ok)throw new Error(`GitHub 불러오기 실패 (${r.status})`);const j=await r.json();sha=j.sha;data=JSON.parse(b64DecodeUnicode(j.content));data.members=(data.members||[]).map(normalizeMember);$('#lastUpdated').value=data.lastUpdated||'';render()}
async function githubSave(){const c=cfg();if(!c.token)throw new Error('GitHub Token을 입력하세요.');if(!sha)await githubGet();const body=payload();body.lastUpdated=body.lastUpdated||new Date().toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).replace(/\. /g,'.').replace('.','').replace(/\.$/,'');const content=JSON.stringify(body,null,2);const url=`https://api.github.com/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}/contents/${c.path}`;const r=await fetch(url,{method:'PUT',headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${c.token}`,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'},body:JSON.stringify({message:`Update EZPK members ${body.lastUpdated}`,content:b64EncodeUnicode(content),sha,branch:c.branch})});if(!r.ok){const err=await r.text();throw new Error(`GitHub 저장 실패 (${r.status}) ${err.slice(0,160)}`)}const j=await r.json();sha=j.content.sha;data=body;setStatus('저장 완료. GitHub Pages 반영까지 보통 1~3분 정도 걸립니다.','ok')}
function exportExcel(){if(!window.XLSX){alert('Excel 라이브러리를 불러오지 못했습니다.');return}const rows=data.members.map((m,i)=>({No:i+1,Rank:m.rank,Nickname:m.nickname,IND:m.ind,'Combat Power':m.power}));const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'EZPK Members');XLSX.writeFile(wb,`EZPK_Member_List_${($('#lastUpdated').value||'backup').replaceAll('.','-')}.xlsx`)}
function importExcel(file){const reader=new FileReader();reader.onload=e=>{const wb=XLSX.read(e.target.result,{type:'array'}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});const members=rows.map(normalizeMember).filter(m=>m.nickname);if(!members.length){alert('유효한 멤버 데이터가 없습니다.');return}data.members=members;render();setStatus(`Excel에서 ${members.length}명을 불러왔습니다. 저장 버튼을 눌러 GitHub에 반영하세요.`,'ok')};reader.readAsArrayBuffer(file)}
function downloadJson(){const blob=new Blob([JSON.stringify(payload(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='members.json';a.click();URL.revokeObjectURL(a.href)}
$('#search').oninput=render;$('#rank').onchange=render;$('#addMember').onclick=()=>{data.members.unshift({rank:'R1',nickname:'New Member',ind:0,power:0});render()};$('#exportExcel').onclick=exportExcel;$('#importExcel').onclick=()=>$('#excelFile').click();$('#excelFile').onchange=e=>e.target.files[0]&&importExcel(e.target.files[0]);$('#downloadJson').onclick=downloadJson;$('#loadGithub').onclick=async()=>{try{setStatus('GitHub 데이터를 불러오는 중...');await githubGet();setStatus('GitHub 데이터 불러오기 완료.','ok')}catch(e){setStatus(e.message,'error')}};$('#saveGithub').onclick=async()=>{try{setStatus('GitHub에 저장하는 중...');await githubSave()}catch(e){setStatus(e.message,'error')}};
loadLocal().then(()=>setStatus('현재 홈페이지 데이터를 불러왔습니다.')).catch(e=>setStatus(e.message,'error'));
