const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const LOCATIONS=[['R1','REFINERY 1'],['R2','REFINERY 2'],['R3','REFINERY 3'],['R4','REFINERY 4'],['R5','REFINERY 5'],['R6','REFINERY 6'],['M1','MILITARY BASE 1'],['M2','MILITARY BASE 2'],['H1','HOSPITAL 1'],['H2','HOSPITAL 2'],['CENTER','ALLOY FACTORY']];
let membersData={lastUpdated:'',members:[]},bgbData={lastUpdated:'',locations:{}},memberSha='',bgbSha='',selectedLocation='R1';
function cfg(){return{owner:$('#owner').value.trim(),repo:$('#repo').value.trim(),branch:$('#branch').value.trim()||'main',token:$('#token').value.trim()}}
function setStatus(msg,type=''){const e=$('#status');e.textContent=msg;e.className='status '+type}
function normalizeMember(m){return{rank:String(m.rank||m.Rank||'R1').toUpperCase(),nickname:String(m.nickname||m.Nickname||'').trim(),ind:Number(m.ind??m.IND??m['Shelter Level']??0),power:Number(String(m.power??m['Combat Power']??0).replaceAll(',',''))}}
function normalizeBgb(d){const out={lastUpdated:String(d?.lastUpdated||''),locations:{}};LOCATIONS.forEach(([code])=>out.locations[code]=Array.isArray(d?.locations?.[code])?[...new Set(d.locations[code].map(String))]:[]);return out}
function rememberToken(){const key='ezpk-admin-token';if($('#rememberToken').checked)localStorage.setItem(key,$('#token').value.trim());else localStorage.removeItem(key)}
function restoreToken(){const token=localStorage.getItem('ezpk-admin-token');if(token){$('#token').value=token;$('#rememberToken').checked=true}}
async function loadLocal(){const [mr,br]=await Promise.all([fetch('../data/members.json?v='+Date.now(),{cache:'no-store'}),fetch('../data/bgb.json?v='+Date.now(),{cache:'no-store'})]);if(!mr.ok||!br.ok)throw new Error('현재 홈페이지 데이터를 불러오지 못했습니다.');membersData=await mr.json();membersData.members=(membersData.members||[]).map(normalizeMember);bgbData=normalizeBgb(await br.json());syncInputs();renderAll()}
function syncInputs(){$('#lastUpdated').value=membersData.lastUpdated||'';$('#bgbLastUpdated').value=bgbData.lastUpdated||''}
function filteredMembers(){const q=$('#search').value.trim().toLowerCase(),rank=$('#rank').value;return membersData.members.map((m,i)=>({...m,_i:i})).filter(m=>(rank==='ALL'||m.rank===rank)&&m.nickname.toLowerCase().includes(q))}
function renderMembers(){const list=filteredMembers();$('#count').textContent=`표시 ${list.length}명 / 전체 ${membersData.members.length}명`;$('#memberRows').innerHTML=list.map(m=>`<tr data-i="${m._i}"><td class="rank-cell"><select data-f="rank">${['R5','R4','R3','R2','R1'].map(r=>`<option ${r===m.rank?'selected':''}>${r}</option>`).join('')}</select></td><td><input data-f="nickname" value="${esc(m.nickname)}"></td><td class="ind-cell"><input data-f="ind" type="number" min="0" value="${m.ind}"></td><td class="power-cell"><input data-f="power" inputmode="numeric" value="${m.power}"></td><td><button class="remove">삭제</button></td></tr>`).join('');$$('#memberRows tr').forEach(tr=>{const i=Number(tr.dataset.i);tr.querySelectorAll('[data-f]').forEach(el=>el.onchange=()=>{const f=el.dataset.f,old=membersData.members[i][f],val=(f==='ind'||f==='power')?Number(String(el.value).replaceAll(',','')):el.value.trim();membersData.members[i][f]=val;if(f==='nickname'&&old!==val){for(const code in bgbData.locations)bgbData.locations[code]=bgbData.locations[code].map(n=>n===old?val:n)}tr.classList.add('dirty');renderAssignments()});tr.querySelector('.remove').onclick=()=>{const name=membersData.members[i].nickname;if(confirm(`${name} 멤버를 삭제할까요?`)){membersData.members.splice(i,1);for(const code in bgbData.locations)bgbData.locations[code]=bgbData.locations[code].filter(n=>n!==name);renderAll()}}})}
function renderLocationButtons(){$('#locationButtons').innerHTML=LOCATIONS.map(([code,name])=>`<button data-code="${code}" class="${code===selectedLocation?'active':''}"><span>${code}</span><small>${(bgbData.locations[code]||[]).length}</small></button>`).join('');$$('#locationButtons button').forEach(b=>b.onclick=()=>{selectedLocation=b.dataset.code;renderLocationButtons();renderAssignments()})}
function assignmentVisibleMembers(){const q=$('#assignmentSearch').value.trim().toLowerCase();return membersData.members.filter(m=>m.nickname.toLowerCase().includes(q)).sort((a,b)=>b.power-a.power)}
function renderAssignments(){const [,name]=LOCATIONS.find(x=>x[0]===selectedLocation)||['R1','REFINERY 1'];$('#selectedLocation').textContent=selectedLocation;$('#selectedLocationName').textContent=name;const assigned=bgbData.locations[selectedLocation]||[];const list=assignmentVisibleMembers();$('#assignmentCount').textContent=`${assigned.length}명 배정`;$('#assignmentMembers').innerHTML=list.map(m=>`<label class="member-check"><input type="checkbox" value="${esc(m.nickname)}" ${assigned.includes(m.nickname)?'checked':''}><span><strong>${esc(m.nickname)}</strong><small>${m.rank} · IND. ${m.ind} · ${Number(m.power).toLocaleString()}</small></span></label>`).join('');$$('#assignmentMembers input').forEach(cb=>cb.onchange=()=>{const set=new Set(bgbData.locations[selectedLocation]||[]);cb.checked?set.add(cb.value):set.delete(cb.value);bgbData.locations[selectedLocation]=[...set];renderLocationButtons();$('#assignmentCount').textContent=`${set.size}명 배정`})}
function renderAll(){renderMembers();renderLocationButtons();renderAssignments()}
function membersPayload(){return{lastUpdated:$('#lastUpdated').value.trim(),members:membersData.members.map(normalizeMember)}}
function bgbPayload(){return{lastUpdated:$('#bgbLastUpdated').value.trim(),locations:normalizeBgb(bgbData).locations}}
function todayKst(){return new Date().toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).replace(/\. /g,'.').replace(/\.$/,'')}
function b64EncodeUnicode(str){const bytes=new TextEncoder().encode(str);let bin='';bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin)}
function b64DecodeUnicode(b64){const bin=atob(b64.replace(/\n/g,''));return new TextDecoder().decode(Uint8Array.from(bin,c=>c.charCodeAt(0)))}
async function githubGetFile(path){const c=cfg();if(!c.token)throw new Error('GitHub Token을 입력하세요.');const url=`https://api.github.com/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}/contents/${path}?ref=${encodeURIComponent(c.branch)}`;const r=await fetch(url,{headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${c.token}`,'X-GitHub-Api-Version':'2022-11-28'}});if(!r.ok)throw new Error(`GitHub 불러오기 실패: ${path} (${r.status})`);const j=await r.json();return{sha:j.sha,data:JSON.parse(b64DecodeUnicode(j.content))}}
async function githubPutFile(path,payload,sha,message){const c=cfg(),url=`https://api.github.com/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}/contents/${path}`;const body={message,content:b64EncodeUnicode(JSON.stringify(payload,null,2)),branch:c.branch};if(sha)body.sha=sha;const r=await fetch(url,{method:'PUT',headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${c.token}`,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){const err=await r.text();throw new Error(`GitHub 저장 실패: ${path} (${r.status}) ${err.slice(0,180)}`)}return(await r.json()).content.sha}
async function loadGithub(){rememberToken();const [m,b]=await Promise.all([githubGetFile('data/members.json'),githubGetFile('data/bgb.json')]);memberSha=m.sha;bgbSha=b.sha;membersData=m.data;membersData.members=(membersData.members||[]).map(normalizeMember);bgbData=normalizeBgb(b.data);syncInputs();renderAll()}
async function saveAllGithub(){rememberToken();if(!memberSha||!bgbSha)await loadGithub();const date=todayKst();const mp=membersPayload(),bp=bgbPayload();if(!mp.lastUpdated)mp.lastUpdated=date;if(!bp.lastUpdated)bp.lastUpdated=date;memberSha=await githubPutFile('data/members.json',mp,memberSha,`Update EZPK members ${mp.lastUpdated}`);bgbSha=await githubPutFile('data/bgb.json',bp,bgbSha,`Update EZPK BGB assignments ${bp.lastUpdated}`);membersData=mp;bgbData=normalizeBgb(bp);syncInputs();setStatus('멤버 정보와 BGB 배치 저장 완료. GitHub Pages 반영까지 보통 1~3분 정도 걸립니다.','ok')}
function exportExcel(){if(!window.XLSX){alert('Excel 라이브러리를 불러오지 못했습니다.');return}const rows=membersData.members.map((m,i)=>({No:i+1,Rank:m.rank,Nickname:m.nickname,IND:m.ind,'Combat Power':m.power}));const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'EZPK Members');XLSX.writeFile(wb,`EZPK_Member_List_${($('#lastUpdated').value||'backup').replaceAll('.','-')}.xlsx`)}
function importExcel(file){const reader=new FileReader();reader.onload=e=>{const wb=XLSX.read(e.target.result,{type:'array'}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});const members=rows.map(normalizeMember).filter(m=>m.nickname);if(!members.length){alert('유효한 멤버 데이터가 없습니다.');return}membersData.members=members;for(const code in bgbData.locations)bgbData.locations[code]=bgbData.locations[code].filter(n=>members.some(m=>m.nickname===n));renderAll();setStatus(`Excel에서 ${members.length}명을 불러왔습니다. 모든 변경사항 저장을 눌러 GitHub에 반영하세요.`,'ok')};reader.readAsArrayBuffer(file)}
function downloadJson(obj,name){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
$$('.admin-tabs button').forEach(btn=>btn.onclick=()=>{$$('.admin-tabs button').forEach(b=>b.classList.remove('active'));$$('.admin-panel').forEach(p=>p.classList.remove('active'));btn.classList.add('active');$('#'+btn.dataset.panel).classList.add('active')});
$('#search').oninput=renderMembers;$('#rank').onchange=renderMembers;$('#assignmentSearch').oninput=renderAssignments;$('#addMember').onclick=()=>{membersData.members.unshift({rank:'R1',nickname:'New Member',ind:0,power:0});renderAll()};$('#exportExcel').onclick=exportExcel;$('#importExcel').onclick=()=>$('#excelFile').click();$('#excelFile').onchange=e=>e.target.files[0]&&importExcel(e.target.files[0]);$('#downloadJson').onclick=()=>downloadJson(membersPayload(),'members.json');$('#downloadBgbJson').onclick=()=>downloadJson(bgbPayload(),'bgb.json');$('#selectAllVisible').onclick=()=>{const set=new Set(bgbData.locations[selectedLocation]||[]);assignmentVisibleMembers().forEach(m=>set.add(m.nickname));bgbData.locations[selectedLocation]=[...set];renderLocationButtons();renderAssignments()};$('#clearLocation').onclick=()=>{if(confirm(`${selectedLocation} 배정을 모두 해제할까요?`)){bgbData.locations[selectedLocation]=[];renderLocationButtons();renderAssignments()}};$('#loadGithub').onclick=async()=>{try{setStatus('GitHub 데이터를 불러오는 중...');await loadGithub();setStatus('GitHub 데이터 불러오기 완료.','ok')}catch(e){setStatus(e.message,'error')}};$('#saveAllGithub').onclick=async()=>{try{setStatus('GitHub에 저장하는 중...');await saveAllGithub()}catch(e){setStatus(e.message,'error')}};$('#rememberToken').onchange=rememberToken;
restoreToken();loadLocal().then(()=>setStatus('현재 홈페이지 데이터를 불러왔습니다.')).catch(e=>setStatus(e.message,'error'));
