(() => {
  'use strict';
  const $=s=>document.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const STATUS_KO={received:'접수됨',reviewing:'검토 중',approved:'승인',rejected:'거절'};
  const STATUS_EN={received:'Received',reviewing:'Reviewing',approved:'Approved',rejected:'Rejected'};
  const CONTACT_KO={not_contacted:'미연락',contacted:'연락 완료'};
  const CONTACT_EN={not_contacted:'Not Contacted',contacted:'Contacted'};
  const TIER_KO={gray:'회색',blue:'파랑',purple:'보라',gold:'골드'};
  const TIER_EN={gray:'Gray',blue:'Blue',purple:'Purple',gold:'Gold'};
  const FIELD_KO={playerName:'게임 닉네임',gameUid:'게임 UID',discord:'Discord',currentState:'현재 서버',currentAlliance:'현재 연맹',vehicle1PowerValue:'1번 차량 파워',vehicle1PowerUnit:'1번 차량 단위',vehicle2PowerValue:'2번 차량 파워',vehicle2PowerUnit:'2번 차량 단위',industryLevel:'산업 레벨',spendingLevel:'과금 타입',migrationTier:'이민 등급',migrationReason:'이민 신청 사유',additionalNotes:'추가 전달사항',migrationGroup:'함께 이민하는 그룹',referrer:'추천인',applicationStatus:'신청 상태',contactStatus:'연락 상태',adminMemo:'관리자 메모',rejectionReason:'거절 사유',deleted:'삭제 상태'};
  const ACTION_KO={application_status_changed:'신청 상태 변경',contact_status_changed:'연락 상태 변경',admin_memo_changed:'관리자 메모 변경',application_content_edited:'신청 내용 수정',application_deleted:'신청서 삭제',application_restored:'신청서 복구'};
  const state={items:[],status:'',search:'',current:null,history:[],initialized:false,loading:false,deletedItems:[],view:'list'};

  function isSuper(){return String(window.EZPKAdminAccess?.state?.adminLevel||'').toLowerCase()==='super'}
  function dateTime(v){if(!v)return'-';const d=new Date(String(v).replace(' ','T')+'Z');return Number.isNaN(d.getTime())?String(v):d.toLocaleString('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});}
  function dateOnly(v){if(!v)return'-';const d=new Date(String(v).replace(' ','T')+'Z');return Number.isNaN(d.getTime())?String(v).slice(0,10):d.toLocaleDateString('ko-KR',{year:'2-digit',month:'2-digit',day:'2-digit'});}
  function power(v,u){return v!=null&&u?`${v} ${u}`:'미입력'}
  function spendingKo(v){v=Number(v);return v<=3?'무과금 / 소과금':v<=6?'중과금':v<=8?'고과금':'핵과금'}
  function spendingEn(v){v=Number(v);return v<=3?'Free / Light Spender':v<=6?'Moderate Spender':v<=8?'Heavy Spender':'Whale'}
  function badgeStatus(v){return `<span class="migration-status-badge ${esc(v)}">${esc(STATUS_KO[v]||v)}</span>`}
  function badgeTier(v){return `<span class="migration-tier-badge ${esc(v)}">${esc(TIER_KO[v]||v)}</span>`}
  function badgeContact(v){return `<span class="migration-contact-badge ${esc(v)}">${esc(CONTACT_KO[v]||v)}</span>`}
  async function api(url,options={}){const r=await fetch(url,{credentials:'include',cache:'no-store',headers:{accept:'application/json',...(options.body?{'content-type':'application/json'}:{})},...options});const p=await r.json().catch(()=>null);if(!r.ok||!p?.ok){const e=new Error(p?.code||'REQUEST_FAILED');e.code=p?.code||'REQUEST_FAILED';e.status=r.status;throw e;}return p.data;}
  function errorMessage(error){const map={MIGRATION_APPLICATION_EXISTS:'같은 UID의 활성 이민 신청이 이미 존재합니다.',MIGRATION_REJECTION_REASON_REQUIRED:'거절 사유를 입력해 주세요.',MIGRATION_APPLICATION_NOT_FOUND:'이민 신청을 찾을 수 없습니다.',SUPER_ADMIN_REQUIRED:'최고관리자만 사용할 수 있습니다.',ADMIN_MENU_FORBIDDEN:'이민 신청 메뉴 권한이 없습니다.',VALIDATION_ERROR:'입력 내용을 다시 확인해 주세요.'};return map[error?.code]||error?.message||'처리 중 오류가 발생했습니다.'}
  function toast(msg,type='ok'){if(window.showAdminToast)window.showAdminToast(msg,type);else alert(msg)}

  async function loadList(){if(state.loading)return;state.loading=true;$('#migrationListStatus').textContent='불러오는 중...';try{const p=new URLSearchParams({limit:'500'});if(state.status)p.set('status',state.status);if(state.search)p.set('search',state.search);const data=await api(`/api/admin/migration?${p}`);state.items=data.items||[];renderList();}catch(e){$('#migrationListStatus').textContent='이민 신청 목록을 불러오지 못했습니다.';$('#migrationRows').innerHTML='<tr><td colspan="5">목록을 불러오지 못했습니다.</td></tr>';toast(errorMessage(e),'error')}finally{state.loading=false}}
  function renderList(){state.view='list';$('#migrationListView').hidden=false;$('#migrationDetailView').hidden=true;$('#migrationDeletedView').hidden=true;$('#migrationDeletedOpen').hidden=!isSuper();const items=state.items;$('#migrationListStatus').textContent=items.length?`총 ${items.length}건`:(state.search?'검색 결과가 없습니다.':'접수된 이민 신청이 없습니다.');$('#migrationRows').innerHTML=items.map(x=>`<tr data-migration-id="${x.id}"><td>${esc(dateOnly(x.createdAt))}</td><td><strong>${esc(x.playerName)}</strong></td><td>${esc(x.currentState)}</td><td>${badgeTier(x.migrationTier)}</td><td>${badgeStatus(x.applicationStatus)}</td></tr>`).join('')||'<tr><td colspan="5">표시할 신청이 없습니다.</td></tr>';$('#migrationCards').innerHTML=items.map(x=>`<article class="migration-card" data-migration-id="${x.id}"><div class="migration-card-top"><strong>${esc(x.playerName)}</strong>${badgeStatus(x.applicationStatus)}</div><div class="migration-card-meta"><span>${esc(dateOnly(x.createdAt))}</span><span>서버 ${esc(x.currentState)}</span>${badgeTier(x.migrationTier)}</div></article>`).join('')}
  async function openDetail(id){try{const data=await api(`/api/admin/migration/${id}`);state.current=data.application;state.history=data.history||[];state.view='detail';renderDetail(data);}catch(e){toast(errorMessage(e),'error')}}
  function detailRow(label,value,full=false){return `<div class="migration-detail-row${full?' full':''}"><dt>${esc(label)}</dt><dd>${esc(value==null||value===''?'미입력':value)}</dd></div>`}
  function detailCard(title,rows){return `<section class="migration-detail-card"><h4>${esc(title)}</h4><dl class="migration-detail-grid">${rows}</dl></section>`}
  function renderHistory(){const first=`<div class="migration-history-item"><strong>신청 접수</strong><small>${esc(dateTime(state.current.createdAt))}</small></div>`;const logs=state.history.map(h=>{const before=h.before||{},after=h.after||{};const keys=[...new Set([...Object.keys(before),...Object.keys(after)])];const changes=keys.map(k=>`${FIELD_KO[k]||k}: ${formatAuditValue(k,before[k])} → ${formatAuditValue(k,after[k])}`).join('\n');return `<div class="migration-history-item"><strong>${esc(ACTION_KO[h.action]||h.action)}</strong><small>${esc(dateTime(h.createdAt))} · ${esc(h.actorNickname||'-')}</small>${changes?`<div class="migration-history-change">${esc(changes)}</div>`:''}</div>`}).join('');return first+logs}
  function formatAuditValue(key,value){if(value==null||value==='')return '미입력';if(key==='applicationStatus')return STATUS_KO[value]||value;if(key==='contactStatus')return CONTACT_KO[value]||value;if(key==='migrationTier')return TIER_KO[value]||value;return String(value)}
  function renderDetail(data){const a=state.current;$('#migrationListView').hidden=true;$('#migrationDeletedView').hidden=true;const host=$('#migrationDetailView');host.hidden=false;const deleted=Boolean(a.deletedAt);host.innerHTML=`<div class="migration-detail-toolbar"><button class="migration-back-button" type="button" data-migration-back>${deleted?'삭제된 신청':'목록'}으로 돌아가기</button></div><section class="migration-detail-hero"><div><h3>${esc(a.playerName)}</h3><div class="migration-detail-meta">서버 ${esc(a.currentState)} · ${esc(TIER_KO[a.migrationTier]||a.migrationTier)} · ${esc(dateTime(a.createdAt))} 신청</div></div><div class="migration-detail-badges">${badgeStatus(a.applicationStatus)}${badgeContact(a.contactStatus)}${badgeTier(a.migrationTier)}</div></section>${deleted?renderDeletedControls(a):renderAdminControls(a)}<div class="migration-detail-sections">${detailCard('신청자 정보',detailRow('게임 닉네임',a.playerName)+detailRow('게임 UID',a.gameUid)+detailRow('Discord',a.discord))}${detailCard('현재 정보',detailRow('현재 서버',a.currentState)+detailRow('현재 연맹',a.currentAlliance))}${detailCard('이민 프로필',detailRow('1번 차량 파워',power(a.vehicle1PowerValue,a.vehicle1PowerUnit))+detailRow('2번 차량 파워',power(a.vehicle2PowerValue,a.vehicle2PowerUnit))+detailRow('산업 레벨',`${a.industryLevel} / 10`)+detailRow('과금 타입',`${a.spendingLevel} / 10 · ${spendingKo(a.spendingLevel)}`))}${detailCard('이민 등급',detailRow('이민 등급',TIER_KO[a.migrationTier]||a.migrationTier))}${detailCard('이민 사유',detailRow('이민 신청 사유',a.migrationReason,true)+detailRow('추가 전달사항',a.additionalNotes,true))}${detailCard('동반 이민',detailRow('함께 이민하는 그룹',a.migrationGroup)+detailRow('추천인',a.referrer))}<section class="migration-detail-card"><h4>처리 이력</h4><div class="migration-history">${renderHistory()}</div></section></div>${!deleted&&isSuper()?`<div class="migration-super-actions"><section class="migration-super-card"><h4>최고관리자 관리</h4><button class="secondary" type="button" data-migration-edit>신청 내용 수정</button></section><section class="migration-super-card migration-danger-zone"><h4>위험 작업</h4><button class="danger" type="button" data-migration-delete>신청서 삭제</button></section></div>`:''}`;bindDetailEvents();}
  function renderAdminControls(a){return `<section class="migration-admin-controls"><div class="migration-admin-control"><label>신청 상태</label><select id="migrationDetailStatus"><option value="received" ${a.applicationStatus==='received'?'selected':''}>접수됨</option><option value="reviewing" ${a.applicationStatus==='reviewing'?'selected':''}>검토 중</option><option value="approved" ${a.applicationStatus==='approved'?'selected':''}>승인</option><option value="rejected" ${a.applicationStatus==='rejected'?'selected':''}>거절</option></select><textarea id="migrationRejectionReason" placeholder="거절 사유" ${a.applicationStatus==='rejected'?'':'hidden'}>${esc(a.rejectionReason||'')}</textarea><div class="migration-admin-control-actions"><button class="primary" type="button" data-migration-status-save>상태 저장</button></div></div><div class="migration-admin-control"><label>연락 상태</label><select id="migrationDetailContact"><option value="not_contacted" ${a.contactStatus==='not_contacted'?'selected':''}>미연락</option><option value="contacted" ${a.contactStatus==='contacted'?'selected':''}>연락 완료</option></select><div class="migration-admin-control-actions"><button class="primary" type="button" data-migration-contact-save>연락 상태 저장</button></div></div><div class="migration-admin-control full"><label>관리자 메모</label><textarea id="migrationAdminMemo" maxlength="2000" placeholder="운영진 내부 메모">${esc(a.adminMemo||'')}</textarea><div class="migration-admin-control-actions"><button class="primary" type="button" data-migration-memo-save>메모 저장</button></div></div></section>`}
  function renderDeletedControls(a){return `<section class="migration-admin-controls"><div class="migration-admin-control full"><label>삭제 정보</label><div class="migration-detail-meta">삭제 처리자: ${esc(a.deletedByNickname||'-')} · 삭제 일시: ${esc(dateTime(a.deletedAt))}</div><div class="migration-admin-control-actions"><button class="primary" type="button" data-migration-restore>복구</button></div></div></section>`}
  function bindDetailEvents(){const status=$('#migrationDetailStatus');status?.addEventListener('change',()=>{$('#migrationRejectionReason').hidden=status.value!=='rejected'});$('[data-migration-back]')?.addEventListener('click',()=>state.current?.deletedAt?renderDeletedList():renderList());$('[data-migration-status-save]')?.addEventListener('click',saveStatus);$('[data-migration-contact-save]')?.addEventListener('click',saveContact);$('[data-migration-memo-save]')?.addEventListener('click',saveMemo);$('[data-migration-edit]')?.addEventListener('click',renderEdit);$('[data-migration-delete]')?.addEventListener('click',deleteCurrent);$('[data-migration-restore]')?.addEventListener('click',restoreCurrent)}
  async function saveStatus(){const status=$('#migrationDetailStatus').value,reason=$('#migrationRejectionReason').value.trim();if(status==='rejected'&&!reason){toast('거절 사유를 입력해 주세요.','error');return}if(['approved','rejected'].includes(status)){const ok=await confirmAction(status==='approved'?'이 신청을 승인하시겠습니까?':'이 신청을 거절하시겠습니까?',status==='approved'?'승인 처리 후에도 연락 상태는 자동 변경되지 않습니다.':'거절 사유는 관리자 내부 기록으로 저장됩니다.',status==='approved'?'승인':'거절',status==='rejected');if(!ok)return}try{await api(`/api/admin/migration/${state.current.id}/status`,{method:'PUT',body:JSON.stringify({status,rejectionReason:reason})});toast('신청 상태를 저장했습니다.');await loadList();await openDetail(state.current.id);}catch(e){toast(errorMessage(e),'error')}}
  async function saveContact(){try{await api(`/api/admin/migration/${state.current.id}/contact`,{method:'PUT',body:JSON.stringify({status:$('#migrationDetailContact').value})});toast('연락 상태를 저장했습니다.');await loadList();await openDetail(state.current.id);}catch(e){toast(errorMessage(e),'error')}}
  async function saveMemo(){try{await api(`/api/admin/migration/${state.current.id}/memo`,{method:'PUT',body:JSON.stringify({memo:$('#migrationAdminMemo').value})});toast('관리자 메모를 저장했습니다.');await openDetail(state.current.id);}catch(e){toast(errorMessage(e),'error')}}
  function renderEdit(){if(!isSuper())return;const a=state.current,host=$('#migrationDetailView');host.innerHTML=`<div class="migration-detail-toolbar"><button class="migration-back-button" type="button" data-migration-edit-cancel>취소</button><strong>신청 내용 수정</strong></div><section class="migration-detail-card"><div class="migration-edit-grid">${editField('playerName','게임 닉네임',a.playerName)}${editField('gameUid','게임 UID',a.gameUid,'text','16')}${editField('discord','Discord',a.discord||'')}${editField('currentState','현재 서버',a.currentState)}${editField('currentAlliance','현재 연맹',a.currentAlliance||'')}${editPower('vehicle1','1번 차량 파워',a.vehicle1PowerValue,a.vehicle1PowerUnit)}${editPower('vehicle2','2번 차량 파워',a.vehicle2PowerValue??'',a.vehicle2PowerUnit||'')}${editSelect('industryLevel','산업 레벨',a.industryLevel,Array.from({length:10},(_,i)=>[i+1,String(i+1)]))}${editSelect('spendingLevel','과금 타입',a.spendingLevel,Array.from({length:10},(_,i)=>[i+1,`${i+1} · ${spendingKo(i+1)}`]))}${editSelect('migrationTier','이민 등급',a.migrationTier,Object.entries(TIER_KO))}${editArea('migrationReason','이민 신청 사유',a.migrationReason,true)}${editArea('additionalNotes','추가 전달사항',a.additionalNotes||'',true)}${editField('migrationGroup','함께 이민하는 그룹',a.migrationGroup||'')}${editField('referrer','추천인',a.referrer||'')}</div><div class="migration-admin-control-actions" style="margin-top:18px"><button class="secondary" type="button" data-migration-edit-cancel>취소</button><button class="primary" type="button" data-migration-edit-save>변경사항 저장</button></div></section>`;host.querySelectorAll('[data-migration-edit-cancel]').forEach(b=>b.onclick=()=>openDetail(a.id));$('[data-migration-edit-save]').onclick=saveEdit;}
  function editField(key,label,value,type='text',maxlength=''){return `<div class="migration-edit-field"><label>${esc(label)}</label><input data-edit-field="${key}" type="${type}" value="${esc(value)}" ${maxlength?`maxlength="${maxlength}"`:''}></div>`}
  function editArea(key,label,value,full=false){return `<div class="migration-edit-field${full?' full':''}"><label>${esc(label)}</label><textarea data-edit-field="${key}" maxlength="2000">${esc(value)}</textarea></div>`}
  function editPower(prefix,label,value,unit){return `<div class="migration-edit-field"><label>${esc(label)}</label><div class="migration-power-edit"><input data-edit-field="${prefix}PowerValue" type="text" inputmode="decimal" value="${esc(value)}"><select data-edit-field="${prefix}PowerUnit"><option value="" ${!unit?'selected':''}>-</option><option value="G" ${unit==='G'?'selected':''}>G</option><option value="M" ${unit==='M'?'selected':''}>M</option></select></div></div>`}
  function editSelect(key,label,value,options){return `<div class="migration-edit-field"><label>${esc(label)}</label><select data-edit-field="${key}">${options.map(([v,l])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select></div>`}
  async function saveEdit(){const payload={};document.querySelectorAll('[data-edit-field]').forEach(el=>payload[el.dataset.editField]=el.value.trim());payload.industryLevel=Number(payload.industryLevel);payload.spendingLevel=Number(payload.spendingLevel);payload.vehicle2PowerValue=payload.vehicle2PowerValue||null;payload.vehicle2PowerUnit=payload.vehicle2PowerUnit||null;const ok=await confirmAction('신청 내용을 수정하시겠습니까?','변경 전/후 값과 수정자, 시각이 처리 이력에 기록됩니다.','저장');if(!ok)return;try{await api(`/api/admin/migration/${state.current.id}`,{method:'PUT',body:JSON.stringify(payload)});toast('신청 내용을 수정했습니다.');await loadList();await openDetail(state.current.id);}catch(e){toast(errorMessage(e),'error')}}
  async function deleteCurrent(){const ok=await confirmAction('이 신청서를 삭제하시겠습니까?','신청서는 영구 삭제되지 않으며 최고관리자가 삭제된 신청에서 복구할 수 있습니다.','삭제',true);if(!ok)return;try{await api(`/api/admin/migration/${state.current.id}`,{method:'DELETE'});toast('신청서를 삭제했습니다.');await loadList();renderList();}catch(e){toast(errorMessage(e),'error')}}
  async function restoreCurrent(){const ok=await confirmAction('이 신청서를 복구하시겠습니까?','복구하면 삭제 전 신청 상태와 연락 상태가 그대로 유지됩니다.','복구');if(!ok)return;try{await api(`/api/admin/migration/${state.current.id}/restore`,{method:'POST',body:'{}'});toast('신청서를 복구했습니다.');await loadDeleted();}catch(e){toast(errorMessage(e),'error')}}
  function confirmAction(title,message,confirmText,danger=false){return new Promise(resolve=>{const host=$('#migrationConfirmModal');host.hidden=false;host.innerHTML=`<div class="migration-confirm-backdrop" data-confirm-cancel></div><section class="migration-confirm-card"><h3>${esc(title)}</h3><p>${esc(message)}</p><div class="migration-confirm-actions"><button class="secondary" type="button" data-confirm-cancel>취소</button><button class="${danger?'danger':'primary'}" type="button" data-confirm-ok>${esc(confirmText)}</button></div></section>`;const done=v=>{host.hidden=true;host.innerHTML='';resolve(v)};host.querySelectorAll('[data-confirm-cancel]').forEach(b=>b.onclick=()=>done(false));host.querySelector('[data-confirm-ok]').onclick=()=>done(true);});}

  async function loadDeleted(){try{const data=await api('/api/admin/migration/deleted');state.deletedItems=data.items||[];renderDeletedList();}catch(e){toast(errorMessage(e),'error')}}
  function renderDeletedList(){state.view='deleted';$('#migrationListView').hidden=true;$('#migrationDetailView').hidden=true;const host=$('#migrationDeletedView');host.hidden=false;host.innerHTML=`<div class="migration-deleted-toolbar"><button class="migration-back-button" type="button" data-deleted-back>목록으로 돌아가기</button><strong>삭제된 신청</strong></div><div class="migration-deleted-list">${state.deletedItems.map(x=>`<article class="migration-deleted-item" data-deleted-id="${x.id}"><span>${esc(dateOnly(x.deletedAt))}</span><strong>${esc(x.playerName)}</strong><span>서버 ${esc(x.currentState)}</span><span>${esc(STATUS_KO[x.applicationStatus]||x.applicationStatus)}</span></article>`).join('')||'<div class="migration-empty">삭제된 신청이 없습니다.</div>'}</div>`;host.querySelector('[data-deleted-back]').onclick=()=>renderList();host.querySelectorAll('[data-deleted-id]').forEach(el=>el.onclick=()=>openDetail(Number(el.dataset.deletedId)));}

  async function exportExcel(){if(!window.XLSX){toast('Excel 라이브러리를 불러오지 못했습니다.','error');return}try{const p=new URLSearchParams({limit:'1000',detail:'1'});if(state.status)p.set('status',state.status);if(state.search)p.set('search',state.search);const data=await api(`/api/admin/migration?${p}`);const rows=(data.items||[]).map(a=>({'Application Date':a.createdAt,'Player Name':a.playerName,'UID':a.gameUid,'Discord':a.discord||'','Current State':a.currentState,'Current Alliance':a.currentAlliance||'','Vehicle 1 Power':power(a.vehicle1PowerValue,a.vehicle1PowerUnit).replace('미입력',''),'Vehicle 2 Power':power(a.vehicle2PowerValue,a.vehicle2PowerUnit).replace('미입력',''),'Industry Level':`${a.industryLevel} / 10`,'Spending Type':`${a.spendingLevel} / 10 · ${spendingEn(a.spendingLevel)}`,'Migration Tier':TIER_EN[a.migrationTier]||a.migrationTier,'Migration Reason':a.migrationReason,'Additional Notes':a.additionalNotes||'','Group / Friends':a.migrationGroup||'','Referrer':a.referrer||'','Application Status':STATUS_EN[a.applicationStatus]||a.applicationStatus,'Contact Status':CONTACT_EN[a.contactStatus]||a.contactStatus}));const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(rows);XLSX.utils.book_append_sheet(wb,ws,'Migration Applications');XLSX.writeFile(wb,`EZPK_Migration_Applications_${new Date().toISOString().slice(0,10)}.xlsx`);}catch(e){toast(errorMessage(e),'error')}}
  function imageDate(v){const d=new Date(String(v).replace(' ','T')+'Z');if(Number.isNaN(d.getTime()))return String(v).slice(0,10);return d.toLocaleDateString('en-US',{month:'short',day:'2-digit',year:'numeric'})}
  function imageDownload(){const items=state.items;if(!items.length){toast('이미지로 만들 신청 목록이 없습니다.','error');return}const width=1400,rowH=58,headH=190,height=headH+rowH*(items.length+1)+70,canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const c=canvas.getContext('2d');c.fillStyle='#070a0f';c.fillRect(0,0,width,height);c.fillStyle='#e2bb64';c.font='700 42px Arial, sans-serif';c.fillText('EZPK Migration Applications',70,75);c.fillStyle='#9fa9b8';c.font='22px Arial, sans-serif';const filter=state.status?STATUS_EN[state.status]:'All';c.fillText(`Status: ${filter}   ·   Applications: ${items.length}   ·   Generated: ${new Date().toLocaleString('en-US')}`,70,118);const cols=[['Date',70,210],['Player',280,390],['State',670,160],['Tier',830,190],['Status',1020,260]];c.fillStyle='#111822';c.fillRect(55,150,width-110,rowH);c.fillStyle='#e2bb64';c.font='700 22px Arial, sans-serif';cols.forEach(([name,x])=>c.fillText(name,x,187));c.font='21px Arial, sans-serif';items.forEach((a,i)=>{const y=150+rowH*(i+1);c.fillStyle=i%2?'#0b1017':'#0e141d';c.fillRect(55,y,width-110,rowH);c.fillStyle='#e8edf4';c.fillText(imageDate(a.createdAt),70,y+37);c.fillText(String(a.playerName).slice(0,26),280,y+37);c.fillText(String(a.currentState),670,y+37);c.fillText(TIER_EN[a.migrationTier]||a.migrationTier,830,y+37);c.fillText(STATUS_EN[a.applicationStatus]||a.applicationStatus,1020,y+37);});c.fillStyle='#737e8c';c.font='18px Arial, sans-serif';c.fillText('EZPK · State #322',70,height-28);const img=$('#migrationImagePreview');img.src=canvas.toDataURL('image/png');$('#migrationImageModal').hidden=false;}
  function closeImage(){const modal=$('#migrationImageModal');modal.hidden=true;$('#migrationImagePreview').removeAttribute('src')}

  function bind(){if(state.initialized)return;state.initialized=true;$('#migrationStatusTabs').addEventListener('click',e=>{const b=e.target.closest('[data-migration-status]');if(!b)return;state.status=b.dataset.migrationStatus;$('#migrationStatusTabs').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));loadList()});let timer;$('#migrationSearch').addEventListener('input',e=>{state.search=e.target.value.trim();clearTimeout(timer);timer=setTimeout(loadList,250)});$('#migrationRefresh').onclick=loadList;$('#migrationRows').addEventListener('click',e=>{const row=e.target.closest('[data-migration-id]');if(row)openDetail(Number(row.dataset.migrationId))});$('#migrationCards').addEventListener('click',e=>{const row=e.target.closest('[data-migration-id]');if(row)openDetail(Number(row.dataset.migrationId))});$('#migrationExcelExport').onclick=exportExcel;$('#migrationImageDownload').onclick=imageDownload;$('#migrationDeletedOpen').onclick=loadDeleted;document.querySelectorAll('[data-migration-image-close]').forEach(b=>b.onclick=closeImage);document.querySelector('[data-panel="migrationPanel"]')?.addEventListener('click',()=>loadList());window.addEventListener('ezpk-admin-ready',()=>{setTimeout(()=>{$('#migrationDeletedOpen').hidden=!isSuper();if(window.EZPKAdminAccess?.has?.('migration'))loadList()},0)});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();
