(() => {
  'use strict';
  const $=s=>document.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const STATUS_KO={received:'접수됨',reviewing:'검토 중',approved:'승인',rejected:'거절'};
  const STATUS_EN={received:'Received',reviewing:'Reviewing',approved:'Approved',rejected:'Rejected'};
  const CONTACT_KO={not_contacted:'미연락',contacted:'연락 완료'};
  const CONTACT_EN={not_contacted:'Not Contacted',contacted:'Contacted'};
  const TIER_KO={gray:'일반',blue:'중급',purple:'고급',gold:'특급'};
  const TIER_EN={gray:'Normal',blue:'Intermediate',purple:'Advanced',gold:'Special'};
  const FIELD_KO={playerName:'게임 닉네임',gameUid:'게임 UID',discord:'Discord',currentState:'현재 서버',currentAlliance:'현재 연맹',vehicle1PowerValue:'1번 차량 파워',vehicle1PowerUnit:'1번 차량 단위',vehicle2PowerValue:'2번 차량 파워',vehicle2PowerUnit:'2번 차량 단위',industryLevel:'산업 레벨',spendingLevel:'과금 타입',migrationTier:'이민 등급',migrationReason:'이민 신청 사유',additionalNotes:'추가 전달사항',migrationGroup:'함께 이민하는 그룹',referrer:'추천인',applicationStatus:'신청 상태',contactStatus:'연락 상태',adminMemo:'관리자 메모',rejectionReason:'거절 사유',deleted:'삭제 상태'};
  const ACTION_KO={application_status_changed:'신청 상태 변경',contact_status_changed:'연락 상태 변경',admin_memo_changed:'관리자 메모 변경',application_content_edited:'신청 내용 수정',application_deleted:'신청서 삭제',application_restored:'신청서 복구'};
  const state={items:[],status:'',search:'',current:null,history:[],initialized:false,loading:false,deletedItems:[],view:'list',importData:null};

  function isSuper(){return String(window.EZPKAdminAccess?.state?.adminLevel||'').toLowerCase()==='super'}
  function dateTime(v){if(!v)return'-';const d=new Date(String(v).replace(' ','T')+'Z');return Number.isNaN(d.getTime())?String(v):d.toLocaleString('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});}
  function dateOnly(v){if(!v)return'-';const d=new Date(String(v).replace(' ','T')+'Z');return Number.isNaN(d.getTime())?String(v).slice(0,10):d.toLocaleDateString('ko-KR',{year:'2-digit',month:'2-digit',day:'2-digit'});}
  function power(v,u){return v!=null&&u?`${v} ${u}`:'미입력'}
  function spendingKo(v){v=Number(v);return v<=3?'무과금 / 소과금':v<=6?'중과금':v<=8?'고과금':'핵과금'}
  function spendingEn(v){v=Number(v);return v<=3?'Free / Light Spender':v<=6?'Moderate Spender':v<=8?'Heavy Spender':'Whale'}
  function badgeStatus(v){return `<span class="migration-status-badge ${esc(v)}">${esc(STATUS_KO[v]||v)}</span>`}
  function badgeTier(v){return `<span class="migration-tier-badge ${esc(v)}">${esc(TIER_KO[v]||v)}</span>`}
  function badgeContact(v){return `<span class="migration-contact-badge ${esc(v)}">${esc(CONTACT_KO[v]||v)}</span>`}
  async function api(url,options={}){const r=await fetch(url,{credentials:'include',cache:'no-store',headers:{accept:'application/json',...(options.body?{'content-type':'application/json'}:{})},...options});const p=await r.json().catch(()=>null);if(!r.ok||!p?.ok){const e=new Error(p?.code||'REQUEST_FAILED');e.code=p?.code||'REQUEST_FAILED';e.status=r.status;throw e;}return p.data;}
  function errorMessage(error){const map={MIGRATION_APPLICATION_EXISTS:'같은 UID의 활성 이민 신청이 이미 존재합니다.',MIGRATION_REJECTION_REASON_REQUIRED:'거절 사유를 입력해 주세요.',MIGRATION_APPLICATION_NOT_FOUND:'이민 신청을 찾을 수 없습니다.',SUPER_ADMIN_REQUIRED:'최고관리자만 사용할 수 있습니다.',ADMIN_MENU_FORBIDDEN:'이민 신청 메뉴 권한이 없습니다.',VALIDATION_ERROR:'입력 내용을 다시 확인해 주세요.',MIGRATION_IMPORT_ROW_LIMIT:'한 번에 최대 500건까지 업로드할 수 있습니다.',MIGRATION_IMPORT_INVALID_META:'공식 업로드 양식을 사용해 주세요.',PAYLOAD_TOO_LARGE:'업로드 데이터가 너무 큽니다.',MIGRATION_IMPORT_IDEMPOTENCY_CONFLICT:'같은 업로드 작업 키에 다른 파일이 사용되었습니다. 파일을 다시 선택해 주세요.'};return map[error?.code]||error?.message||'처리 중 오류가 발생했습니다.'}
  function toast(msg,type='ok'){if(window.showAdminToast)window.showAdminToast(msg,type);else alert(msg)}

  async function loadList(){if(state.loading)return;state.loading=true;$('#migrationListStatus').textContent='불러오는 중...';try{const p=new URLSearchParams({limit:'500'});if(state.status)p.set('status',state.status);if(state.search)p.set('search',state.search);const data=await api(`/api/admin/migration?${p}`);state.items=data.items||[];renderList();}catch(e){$('#migrationListStatus').textContent='이민 신청 목록을 불러오지 못했습니다.';$('#migrationRows').innerHTML='<tr><td colspan="5">목록을 불러오지 못했습니다.</td></tr>';toast(errorMessage(e),'error')}finally{state.loading=false}}
  function renderList(){state.view='list';$('#migrationListView').hidden=false;$('#migrationDetailView').hidden=true;$('#migrationDeletedView').hidden=true;$('#migrationDeletedOpen').hidden=!isSuper();const items=state.items;$('#migrationListStatus').textContent=items.length?`총 ${items.length}건`:(state.search?'검색 결과가 없습니다.':'접수된 이민 신청이 없습니다.');$('#migrationRows').innerHTML=items.map(x=>`<tr data-migration-id="${x.id}"><td>${esc(dateOnly(x.createdAt))}</td><td><strong>${esc(x.playerName)}</strong></td><td>${esc(x.currentState)}</td><td>${badgeTier(x.migrationTier)}</td><td>${badgeStatus(x.applicationStatus)}</td></tr>`).join('')||'<tr><td colspan="5">표시할 신청이 없습니다.</td></tr>';$('#migrationCards').innerHTML=items.map(x=>`<article class="migration-card" data-migration-id="${x.id}"><div class="migration-card-top"><strong>${esc(x.playerName)}</strong>${badgeStatus(x.applicationStatus)}</div><div class="migration-card-meta"><span>${esc(dateOnly(x.createdAt))}</span><span>서버 ${esc(x.currentState)}</span>${badgeTier(x.migrationTier)}</div></article>`).join('')}
  async function openDetail(id){try{const data=await api(`/api/admin/migration/${id}`);state.current=data.application;state.history=data.history||[];state.view='detail';renderDetail(data);}catch(e){toast(errorMessage(e),'error')}}
  function detailRow(label,value,full=false){return `<div class="migration-detail-row${full?' full':''}"><dt>${esc(label)}</dt><dd>${esc(value==null||value===''?'미입력':value)}</dd></div>`}
  function detailCard(title,rows){return `<section class="migration-detail-card"><h4>${esc(title)}</h4><dl class="migration-detail-grid">${rows}</dl></section>`}
  function renderHistory(){const first=`<div class="migration-history-item"><strong>신청 접수</strong><small>${esc(dateTime(state.current.createdAt))}</small></div>`;const logs=state.history.map(h=>{const before=h.before||{},after=h.after||{};const keys=[...new Set([...Object.keys(before),...Object.keys(after)])];const changes=keys.map(k=>`${FIELD_KO[k]||k}: ${formatAuditValue(k,before[k])} → ${formatAuditValue(k,after[k])}`).join('\n');return `<div class="migration-history-item"><strong>${esc(ACTION_KO[h.action]||h.action)}</strong><small>${esc(dateTime(h.createdAt))} · ${esc(h.actorNickname||'-')}</small>${changes?`<div class="migration-history-change">${esc(changes)}</div>`:''}</div>`}).join('');return first+logs}
  function formatAuditValue(key,value){if(value==null||value==='')return '미입력';if(key==='applicationStatus')return STATUS_KO[value]||value;if(key==='contactStatus')return CONTACT_KO[value]||value;if(key==='migrationTier')return TIER_KO[value]||value;return String(value)}
  function renderDetail(data){const a=state.current;$('#migrationListView').hidden=true;$('#migrationDeletedView').hidden=true;const host=$('#migrationDetailView');host.hidden=false;const deleted=Boolean(a.deletedAt);host.innerHTML=`<div class="migration-detail-toolbar"><button class="migration-back-button" type="button" data-migration-back>${deleted?'삭제된 신청':'목록'}으로 돌아가기</button></div><section class="migration-detail-hero"><div><h3>${esc(a.playerName)}</h3><div class="migration-detail-meta">서버 ${esc(a.currentState)} · ${esc(TIER_KO[a.migrationTier]||a.migrationTier)} · ${esc(dateTime(a.createdAt))} 신청</div></div><div class="migration-detail-badges">${badgeStatus(a.applicationStatus)}${badgeContact(a.contactStatus)}${badgeTier(a.migrationTier)}</div></section>${deleted?renderDeletedControls(a):renderAdminControls(a)}<div class="migration-detail-sections">${detailCard('신청자 정보',detailRow('게임 닉네임',a.playerName)+detailRow('게임 UID',a.gameUid)+detailRow('Discord',a.discord))}${detailCard('현재 정보',detailRow('현재 서버',a.currentState)+detailRow('현재 연맹',a.currentAlliance))}${detailCard('이민 프로필',detailRow('1번 차량 파워',power(a.vehicle1PowerValue,a.vehicle1PowerUnit))+detailRow('2번 차량 파워',power(a.vehicle2PowerValue,a.vehicle2PowerUnit))+detailRow('산업 레벨',`${a.industryLevel} / 10`)+detailRow('과금 타입',`${a.spendingLevel} / 10 · ${spendingKo(a.spendingLevel)}`))}${detailCard('이민 등급',detailRow('이민 등급',TIER_KO[a.migrationTier]||a.migrationTier))}${detailCard('이민 사유',detailRow('이민 신청 사유',a.migrationReason,true)+detailRow('추가 전달사항',a.additionalNotes,true))}${detailCard('동반 이민',detailRow('함께 이민하는 그룹',a.migrationGroup)+detailRow('추천인',a.referrer))}<section class="migration-detail-card"><h4>처리 이력</h4><div class="migration-history">${renderHistory()}</div></section></div>${!deleted&&isSuper()?`<div class="migration-super-actions"><section class="migration-super-card"><h4>최고관리자 관리</h4><button class="secondary" type="button" data-migration-edit>신청 내용 수정</button></section><section class="migration-super-card migration-danger-zone"><h4>위험 작업</h4><button class="danger" type="button" data-migration-delete>신청서 삭제</button></section></div>`:''}`;bindDetailEvents();}
  function renderAdminControls(a){return `<section class="migration-admin-controls"><div class="migration-admin-control"><label>신청 상태</label><select id="migrationDetailStatus"><option value="received" ${a.applicationStatus==='received'?'selected':''}>접수됨</option><option value="reviewing" ${a.applicationStatus==='reviewing'?'selected':''}>검토 중</option><option value="approved" ${a.applicationStatus==='approved'?'selected':''}>승인</option><option value="rejected" ${a.applicationStatus==='rejected'?'selected':''}>거절</option></select><textarea id="migrationRejectionReason" placeholder="거절 사유" ${a.applicationStatus==='rejected'?'':'hidden'}>${esc(a.rejectionReason||'')}</textarea><div class="migration-admin-control-actions"><button class="primary" type="button" data-migration-status-save>상태 저장</button></div></div><div class="migration-admin-control"><label>연락 상태</label><select id="migrationDetailContact"><option value="not_contacted" ${a.contactStatus==='not_contacted'?'selected':''}>미연락</option><option value="contacted" ${a.contactStatus==='contacted'?'selected':''}>연락 완료</option></select><div class="migration-admin-control-actions"><button class="primary" type="button" data-migration-contact-save>연락 상태 저장</button></div></div><div class="migration-admin-control full"><label>관리자 메모</label><textarea id="migrationAdminMemo" maxlength="2000" placeholder="운영진 내부 메모">${esc(a.adminMemo||'')}</textarea><div class="migration-admin-control-actions"><button class="primary" type="button" data-migration-memo-save>메모 저장</button></div></div></section>`}
  function renderDeletedControls(a){return `<section class="migration-admin-controls"><div class="migration-admin-control full"><label>삭제 정보</label><div class="migration-detail-meta">삭제 처리자: ${esc(a.deletedByNickname||'-')} · 삭제 일시: ${esc(dateTime(a.deletedAt))}</div><div class="migration-admin-control-actions"><button class="primary" type="button" data-migration-restore>복구</button></div></div></section>`}
  function bindDetailEvents(){const status=$('#migrationDetailStatus');status?.addEventListener('change',()=>{$('#migrationRejectionReason').hidden=status.value!=='rejected'});$('[data-migration-back]')?.addEventListener('click',()=>state.current?.deletedAt?renderDeletedList():renderList());$('[data-migration-status-save]')?.addEventListener('click',saveStatus);$('[data-migration-contact-save]')?.addEventListener('click',saveContact);$('[data-migration-memo-save]')?.addEventListener('click',saveMemo);$('[data-migration-edit]')?.addEventListener('click',renderEdit);$('[data-migration-delete]')?.addEventListener('click',deleteCurrent);$('[data-migration-restore]')?.addEventListener('click',restoreCurrent)}
  async function saveStatus(){const status=$('#migrationDetailStatus').value,reason=$('#migrationRejectionReason').value.trim();if(status==='rejected'&&!reason){toast('거절 사유를 입력해 주세요.','error');return}if(['approved','rejected'].includes(status)){const ok=await confirmAction(status==='approved'?'이 신청을 승인하시겠습니까?':'이 신청을 거절하시겠습니까?',status==='approved'?'승인 처리 후에도 연락 상태는 자동 변경되지 않습니다.':'거절 사유는 관리자 내부 기록으로 저장됩니다.',status==='approved'?'승인':'거절',status==='rejected');if(!ok)return}try{await api(`/api/admin/migration/${state.current.id}/status`,{method:'PUT',body:JSON.stringify({status,rejectionReason:reason})});toast('신청 상태를 저장했습니다.');await loadList();await openDetail(state.current.id);}catch(e){toast(errorMessage(e),'error')}}
  async function saveContact(){try{await api(`/api/admin/migration/${state.current.id}/contact`,{method:'PUT',body:JSON.stringify({status:$('#migrationDetailContact').value})});toast('연락 상태를 저장했습니다.');await loadList();await openDetail(state.current.id);}catch(e){toast(errorMessage(e),'error')}}
  async function saveMemo(){try{await api(`/api/admin/migration/${state.current.id}/memo`,{method:'PUT',body:JSON.stringify({memo:$('#migrationAdminMemo').value})});toast('관리자 메모를 저장했습니다.');await openDetail(state.current.id);}catch(e){toast(errorMessage(e),'error')}}
  function renderEdit(){if(!isSuper())return;const a=state.current,host=$('#migrationDetailView');host.innerHTML=`<div class="migration-detail-toolbar"><button class="migration-back-button" type="button" data-migration-edit-cancel>취소</button><strong>신청 내용 수정</strong></div><section class="migration-detail-card"><div class="migration-edit-grid">${editField('playerName','게임 닉네임',a.playerName)}${editField('gameUid','게임 UID',a.gameUid,'text','16')}${editField('discord','Discord',a.discord||'')}${editField('currentState','현재 서버',a.currentState)}${editField('currentAlliance','현재 연맹',a.currentAlliance||'')}${editPower('vehicle1','1번 차량 파워',a.vehicle1PowerValue,a.vehicle1PowerUnit)}${editPower('vehicle2','2번 차량 파워',a.vehicle2PowerValue??'',a.vehicle2PowerUnit||'')}${editSelect('industryLevel','산업 레벨',a.industryLevel,Array.from({length:10},(_,i)=>[i+1,String(i+1)]))}${editSelect('spendingLevel','과금 타입',a.spendingLevel,Array.from({length:10},(_,i)=>[i+1,`${i+1} · ${spendingKo(i+1)}`]))}${editSelect('migrationTier','이민 등급',a.migrationTier,Object.entries(TIER_KO))}${editArea('migrationReason','이민 신청 사유',a.migrationReason,true)}${editArea('additionalNotes','추가 전달사항',a.additionalNotes||'',true)}${editField('migrationGroup','함께 이민하는 그룹',a.migrationGroup||'')}${editField('referrer','추천인',a.referrer||'')}</div><div class="migration-admin-control-actions" style="margin-top:18px"><button class="secondary" type="button" data-migration-edit-cancel>취소</button><button class="primary" type="button" data-migration-edit-save>변경사항 저장</button></div></section>`;host.querySelectorAll('[data-migration-edit-cancel]').forEach(b=>b.onclick=()=>openDetail(a.id));$('[data-migration-edit-save]').onclick=saveEdit;}
  function editField(key,label,value,type='text',maxlength=''){return `<div class="migration-edit-field"><label>${esc(label)}</label><input data-edit-field="${key}" type="${type}" value="${esc(value)}" ${maxlength?`maxlength="${maxlength}"`:''}></div>`}
  function editArea(key,label,value,full=false){return `<div class="migration-edit-field${full?' full':''}"><label>${esc(label)}</label><textarea data-edit-field="${key}" maxlength="2000">${esc(value)}</textarea></div>`}
  function editPower(prefix,label,value,unit){return `<div class="migration-edit-field"><label>${esc(label)}</label><div class="migration-power-edit"><input data-edit-field="${prefix}PowerValue" type="text" inputmode="decimal" value="${esc(value)}"><select data-edit-field="${prefix}PowerUnit"><option value="" ${!unit?'selected':''}>-</option><option value="G" ${unit==='G'?'selected':''}>G</option><option value="M" ${unit==='M'?'selected':''}>M</option></select></div></div>`}
  function editSelect(key,label,value,options){return `<div class="migration-edit-field"><label>${esc(label)}</label><select data-edit-field="${key}">${options.map(([v,l])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select></div>`}
  async function saveEdit(){const payload={};document.querySelectorAll('[data-edit-field]').forEach(el=>payload[el.dataset.editField]=el.value.trim());payload.industryLevel=Number(payload.industryLevel);payload.spendingLevel=Number(payload.spendingLevel);payload.vehicle2PowerValue=payload.vehicle2PowerValue||null;payload.vehicle2PowerUnit=payload.vehicle2PowerUnit||null;const ok=await confirmAction('신청 내용을 수정하시겠습니까?','변경 전/후 값과 수정자, 시각이 처리 이력에 기록됩니다.','저장');if(!ok)return;try{await api(`/api/admin/migration/${state.current.id}`,{method:'PUT',body:JSON.stringify(payload)});toast('신청 내용을 수정했습니다.');await loadList();await openDetail(state.current.id);}catch(e){toast(errorMessage(e),'error')}}
  async function deleteCurrent(){const ok=await confirmAction('이 신청서를 삭제하시겠습니까?','신청서는 영구 삭제되지 않으며 최고관리자가 삭제된 신청에서 복구할 수 있습니다.','삭제',true);if(!ok)return;try{await api(`/api/admin/migration/${state.current.id}`,{method:'DELETE'});toast('신청서를 삭제했습니다.');await loadList();renderList();}catch(e){toast(errorMessage(e),'error')}}
  async function restoreCurrent(){const ok=await confirmAction('이 신청서를 복구하시겠습니까?','복구하면 삭제 전 신청 상태와 연락 상태가 그대로 유지됩니다.','복구');if(!ok)return;try{await api(`/api/admin/migration/${state.current.id}/restore`,{method:'POST',body:'{}'});toast('신청서를 복구했습니다.');await loadDeleted();}catch(e){toast(errorMessage(e),'error')}}
  function confirmAction(title,message,confirmText,danger=false){return new Promise(resolve=>{const host=$('#migrationConfirmModal');host.hidden=false;host.innerHTML=`<div class="migration-confirm-backdrop" data-confirm-cancel></div><section class="migration-confirm-card"><h3>${esc(title)}</h3><p>${esc(message)}</p><div class="migration-confirm-actions"><button class="secondary" type="button" data-confirm-cancel>취소</button><button class="${danger?'danger':'primary'}" type="button" data-confirm-ok>${esc(confirmText)}</button></div></section>`;const done=v=>{host.hidden=true;host.innerHTML='';resolve(v)};host.querySelectorAll('[data-confirm-cancel]').forEach(b=>b.onclick=()=>done(false));host.querySelector('[data-confirm-ok]').onclick=()=>done(true);});}

  async function loadDeleted(){try{const data=await api('/api/admin/migration/deleted');state.deletedItems=data.items||[];renderDeletedList();}catch(e){toast(errorMessage(e),'error')}}
  function renderDeletedList(){state.view='deleted';$('#migrationListView').hidden=true;$('#migrationDetailView').hidden=true;const host=$('#migrationDeletedView');host.hidden=false;host.innerHTML=`<div class="migration-deleted-toolbar"><button class="migration-back-button" type="button" data-deleted-back>목록으로 돌아가기</button><strong>삭제된 신청</strong></div><div class="migration-deleted-list">${state.deletedItems.map(x=>`<article class="migration-deleted-item" data-deleted-id="${x.id}"><span>${esc(dateOnly(x.deletedAt))}</span><strong>${esc(x.playerName)}</strong><span>서버 ${esc(x.currentState)}</span><span>${esc(STATUS_KO[x.applicationStatus]||x.applicationStatus)}</span></article>`).join('')||'<div class="migration-empty">삭제된 신청이 없습니다.</div>'}</div>`;host.querySelector('[data-deleted-back]').onclick=()=>renderList();host.querySelectorAll('[data-deleted-id]').forEach(el=>el.onclick=()=>openDetail(Number(el.dataset.deletedId)));}

  const IMPORT_TEMPLATE_VERSION='EZPK Migration Import v1';
  const IMPORT_TEMPLATE_FILE='EZPK_이민신청_업로드양식_v1.xlsx';
  const IMPORT_MAX_FILE_BYTES=5*1024*1024;
  const IMPORT_HEADERS=['게임 닉네임','UID','Discord','현재 서버','현재 연맹','1번 차량 파워','1번 차량 단위','2번 차량 파워','2번 차량 단위','산업 레벨','과금 타입','이민 등급','이민 신청 사유','추가 전달사항','함께 이민하는 그룹','추천인'];

  function syncImportAccess(){const superAdmin=isSuper();const t=$('#migrationImportTemplate'),i=$('#migrationExcelImport');if(t)t.hidden=!superAdmin;if(i)i.hidden=!superAdmin;}
  function downloadImportTemplate(){if(!isSuper()){toast('최고관리자만 사용할 수 있습니다.','error');return}const a=document.createElement('a');a.href=`./${encodeURIComponent(IMPORT_TEMPLATE_FILE)}`;a.download=IMPORT_TEMPLATE_FILE;document.body.appendChild(a);a.click();a.remove();}
  function closeImport(){const host=$('#migrationImportModal');host.hidden=true;host.innerHTML='';state.importData=null;}
  function importStatusBadge(row){const label=row.status==='ready'?'등록 가능':row.status==='duplicate'?'중복':'오류';return `<span class="migration-import-status ${esc(row.status)}">${label}</span>`}
  function importSummaryCards(summary={}){return `<div class="migration-import-summary"><article><span>전체</span><strong>${Number(summary.total||0)}</strong></article><article><span>등록 가능</span><strong>${Number(summary.ready||0)}</strong></article><article><span>중복</span><strong>${Number(summary.duplicate||0)}</strong></article><article><span>오류</span><strong>${Number(summary.invalid||0)}</strong></article></div>`}
  async function loadImportHistory(){const host=$('#migrationImportHistory');if(!host)return;host.innerHTML='<div class="migration-import-muted">최근 업로드 이력을 불러오는 중...</div>';try{const data=await api('/api/admin/migration/import/batches');const items=data.items||[];host.innerHTML=items.length?items.map(x=>`<div class="migration-import-history-item"><div><strong>${esc(x.fileName)}</strong><small>${esc(dateTime(x.committedAt||x.createdAt))} · ${esc(x.actorNickname||'-')}</small></div><div><span>등록 ${Number(x.imported||0)}</span><span>제외 ${Number(x.skipped||0)}</span><span>실패 ${Number(x.failed||0)}</span></div></div>`).join(''):'<div class="migration-import-muted">업로드 이력이 없습니다.</div>';}catch(e){host.innerHTML='<div class="migration-import-muted">업로드 이력을 불러오지 못했습니다.</div>';}}
  function openImport(){if(!isSuper()){toast('최고관리자만 사용할 수 있습니다.','error');return}const host=$('#migrationImportModal');host.hidden=false;host.innerHTML=`<div class="migration-import-backdrop" data-import-close></div><section class="migration-import-card"><header><div><h3>이민 신청 엑셀 업로드</h3><p>공식 양식의 신규 신청을 검토한 뒤 등록합니다.</p></div><button type="button" data-import-close aria-label="닫기">×</button></header><div class="migration-import-guide"><strong>업로드 전 확인</strong><span>.xlsx 파일만 가능 · 최대 500건</span><span>UID는 16자리 숫자의 텍스트 셀이어야 합니다.</span><span>중복 또는 오류 행은 등록에서 제외됩니다.</span></div><div id="migrationImportStage"><label class="migration-import-file"><span>파일 선택</span><input id="migrationImportFile" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"></label><div id="migrationImportFileStatus" class="migration-import-muted">업로드 양식을 선택해 주세요.</div><div class="migration-import-actions"><button class="secondary" type="button" data-import-close>취소</button><button id="migrationImportPreviewButton" class="primary" type="button" disabled>업로드 검토</button></div></div><section class="migration-import-history"><h4>최근 업로드 이력</h4><div id="migrationImportHistory"></div></section></section>`;host.querySelectorAll('[data-import-close]').forEach(b=>b.onclick=closeImport);$('#migrationImportFile').onchange=handleImportFile;$('#migrationImportPreviewButton').onclick=previewImport;loadImportHistory();}
  async function sha256File(buffer){const hash=await crypto.subtle.digest('SHA-256',buffer);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}
  function cellRaw(sheet,r,c){const cell=sheet[XLSX.utils.encode_cell({r,c})];return cell?cell.v:''}
  function cellType(sheet,r,c){const cell=sheet[XLSX.utils.encode_cell({r,c})];return cell?.t||''}
  function parseImportWorkbook(buffer,file){if(!window.XLSX)throw new Error('Excel 라이브러리를 불러오지 못했습니다.');const wb=XLSX.read(buffer,{type:'array',cellDates:false,cellText:false});const guide=wb.Sheets['안내'];const version=String(guide?.B2?.v||'').trim();if(version!==IMPORT_TEMPLATE_VERSION){const e=new Error('공식 업로드 양식이 아니거나 양식 버전이 다릅니다.');e.code='MIGRATION_IMPORT_INVALID_META';throw e}const sheet=wb.Sheets['이민신청 업로드'];if(!sheet)throw new Error('이민신청 업로드 시트를 찾을 수 없습니다.');const range=XLSX.utils.decode_range(sheet['!ref']||'A1:P1');const headers=IMPORT_HEADERS.map((_,c)=>String(cellRaw(sheet,0,c)??'').trim());if(IMPORT_HEADERS.some((h,i)=>headers[i]!==h))throw new Error('업로드 양식의 열 제목이 변경되었습니다. 공식 양식을 다시 내려받아 주세요.');const rows=[];for(let r=1;r<=range.e.r;r++){const values=IMPORT_HEADERS.map((_,c)=>cellRaw(sheet,r,c));if(values.every(v=>String(v??'').trim()===''))continue;rows.push({rowNumber:r+1,playerName:values[0],gameUid:values[1],uidCellType:cellType(sheet,r,1),discord:values[2],currentState:values[3],currentAlliance:values[4],vehicle1PowerValue:values[5],vehicle1PowerUnit:values[6],vehicle2PowerValue:values[7],vehicle2PowerUnit:values[8],industryLevel:values[9],spendingLevel:values[10],migrationTier:values[11],migrationReason:values[12],additionalNotes:values[13],migrationGroup:values[14],referrer:values[15]});}if(!rows.length)throw new Error('등록할 신청 데이터가 없습니다.');if(rows.length>500)throw new Error('한 번에 최대 500건까지 업로드할 수 있습니다.');return rows;}
  async function handleImportFile(e){const file=e.target.files?.[0];const status=$('#migrationImportFileStatus'),button=$('#migrationImportPreviewButton');state.importData=null;button.disabled=true;if(!file){status.textContent='업로드 양식을 선택해 주세요.';return}if(!/\.xlsx$/i.test(file.name)){status.textContent='.xlsx 파일만 업로드할 수 있습니다.';return}if(file.size>IMPORT_MAX_FILE_BYTES){status.textContent='파일 크기는 5MB 이하여야 합니다.';return}try{const buffer=await file.arrayBuffer();const rows=parseImportWorkbook(buffer,file);const fileSha256=await sha256File(buffer);state.importData={fileName:file.name,fileSha256,rows,idempotencyKey:(crypto.randomUUID?crypto.randomUUID():`${Date.now()}_${Math.random().toString(36).slice(2)}`).replace(/[^A-Za-z0-9_-]/g,'_')};status.textContent=`${file.name} · ${rows.length}건을 확인했습니다.`;button.disabled=false;}catch(err){status.textContent=errorMessage(err);toast(errorMessage(err),'error')}}
  async function previewImport(){if(!state.importData)return;const button=$('#migrationImportPreviewButton');button.disabled=true;button.textContent='검토 중...';try{const data=await api('/api/admin/migration/import/preview',{method:'POST',body:JSON.stringify({templateVersion:IMPORT_TEMPLATE_VERSION,...state.importData})});renderImportPreview(data);}catch(e){toast(errorMessage(e),'error');button.disabled=false;button.textContent='업로드 검토'}}
  function renderImportPreview(data){const stage=$('#migrationImportStage');const s=data.summary||{},rows=data.rows||[];stage.innerHTML=`<div class="migration-import-preview-head"><div><strong>업로드 검토 결과</strong><span>${esc(state.importData?.fileName||'')}</span></div><button id="migrationImportChangeFile" class="secondary" type="button">파일 다시 선택</button></div>${importSummaryCards(s)}<div class="migration-import-preview-table-wrap"><table class="migration-import-preview-table"><thead><tr><th>행</th><th>닉네임</th><th>UID</th><th>결과</th><th>확인 내용</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${Number(r.rowNumber||0)}</td><td>${esc(r.playerName||'-')}</td><td>${esc(r.gameUid||'-')}</td><td>${importStatusBadge(r)}</td><td>${esc((r.errors||[]).join(' / ')||'등록 가능')}</td></tr>`).join('')}</tbody></table></div><div class="migration-import-actions"><button id="migrationImportCancelPreview" class="secondary" type="button">취소</button><button id="migrationImportCommit" class="primary" type="button" ${Number(s.ready||0)<1?'disabled':''}>신청서 ${Number(s.ready||0)}건 등록</button></div>`;$('#migrationImportChangeFile').onclick=()=>{closeImport();openImport()};$('#migrationImportCancelPreview').onclick=closeImport;$('#migrationImportCommit').onclick=commitImport;}
  async function commitImport(){if(!state.importData)return;const btn=$('#migrationImportCommit');const ok=await confirmAction('검토된 신청서를 등록하시겠습니까?',`${btn?.textContent||'신청서 등록'} 후에는 일반 이민 신청과 동일하게 관리자 페이지에서 관리됩니다.`,'등록');if(!ok)return;btn.disabled=true;btn.textContent='등록 중...';try{const data=await api('/api/admin/migration/import/commit',{method:'POST',body:JSON.stringify({templateVersion:IMPORT_TEMPLATE_VERSION,...state.importData})});renderImportComplete(data);await loadList();}catch(e){toast(errorMessage(e),'error');btn.disabled=false;btn.textContent='신청서 등록'}}
  function renderImportComplete(data){const s=data.summary||{},stage=$('#migrationImportStage');stage.innerHTML=`<div class="migration-import-complete"><div class="migration-import-complete-icon">✓</div><h4>엑셀 업로드가 완료되었습니다.</h4><p>등록된 신청은 즉시 이민 신청 목록과 UID 조회에 반영됩니다.</p><div class="migration-import-result-grid"><span>전체 <strong>${Number(s.total||0)}</strong></span><span>등록 <strong>${Number(s.imported||0)}</strong></span><span>제외 <strong>${Number(s.skipped||0)}</strong></span><span>실패 <strong>${Number(s.failed||0)}</strong></span></div><button id="migrationImportDone" class="primary" type="button">확인</button></div>`;$('#migrationImportDone').onclick=closeImport;loadImportHistory();}

  async function exportExcel(){if(!window.XLSX){toast('Excel 라이브러리를 불러오지 못했습니다.','error');return}try{const p=new URLSearchParams({limit:'1000',detail:'1'});if(state.status)p.set('status',state.status);if(state.search)p.set('search',state.search);const data=await api(`/api/admin/migration?${p}`);const rows=(data.items||[]).map(a=>({'Application Date':a.createdAt,'Player Name':a.playerName,'UID':a.gameUid,'Discord':a.discord||'','Current State':a.currentState,'Current Alliance':a.currentAlliance||'','Vehicle 1 Power':power(a.vehicle1PowerValue,a.vehicle1PowerUnit).replace('미입력',''),'Vehicle 2 Power':power(a.vehicle2PowerValue,a.vehicle2PowerUnit).replace('미입력',''),'Industry Level':`${a.industryLevel} / 10`,'Spending Type':`${a.spendingLevel} / 10 · ${spendingEn(a.spendingLevel)}`,'Migration Tier':TIER_EN[a.migrationTier]||a.migrationTier,'Migration Reason':a.migrationReason,'Additional Notes':a.additionalNotes||'','Group / Friends':a.migrationGroup||'','Referrer':a.referrer||'','Application Status':STATUS_EN[a.applicationStatus]||a.applicationStatus,'Contact Status':CONTACT_EN[a.contactStatus]||a.contactStatus}));const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(rows);XLSX.utils.book_append_sheet(wb,ws,'Migration Applications');XLSX.writeFile(wb,`EZPK_Migration_Applications_${new Date().toISOString().slice(0,10)}.xlsx`);}catch(e){toast(errorMessage(e),'error')}}
  function imageDate(v){const d=new Date(String(v).replace(' ','T')+'Z');if(Number.isNaN(d.getTime()))return String(v).slice(0,10);return d.toLocaleDateString('en-US',{month:'short',day:'2-digit',year:'numeric'})}
  function imageDownload(){const items=state.items;if(!items.length){toast('이미지로 만들 신청 목록이 없습니다.','error');return}const width=1400,rowH=58,headH=190,height=headH+rowH*(items.length+1)+70,canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const c=canvas.getContext('2d');c.fillStyle='#070a0f';c.fillRect(0,0,width,height);c.fillStyle='#e2bb64';c.font='700 42px Arial, sans-serif';c.fillText('EZPK Migration Applications',70,75);c.fillStyle='#9fa9b8';c.font='22px Arial, sans-serif';const filter=state.status?STATUS_EN[state.status]:'All';c.fillText(`Status: ${filter}   ·   Applications: ${items.length}   ·   Generated: ${new Date().toLocaleString('en-US')}`,70,118);const cols=[['Date',70,210],['Player',280,390],['State',670,160],['Tier',830,190],['Status',1020,260]];c.fillStyle='#111822';c.fillRect(55,150,width-110,rowH);c.fillStyle='#e2bb64';c.font='700 22px Arial, sans-serif';cols.forEach(([name,x])=>c.fillText(name,x,187));c.font='21px Arial, sans-serif';items.forEach((a,i)=>{const y=150+rowH*(i+1);c.fillStyle=i%2?'#0b1017':'#0e141d';c.fillRect(55,y,width-110,rowH);c.fillStyle='#e8edf4';c.fillText(imageDate(a.createdAt),70,y+37);c.fillText(String(a.playerName).slice(0,26),280,y+37);c.fillText(String(a.currentState),670,y+37);c.fillText(TIER_EN[a.migrationTier]||a.migrationTier,830,y+37);c.fillText(STATUS_EN[a.applicationStatus]||a.applicationStatus,1020,y+37);});c.fillStyle='#737e8c';c.font='18px Arial, sans-serif';c.fillText('EZPK · State #322',70,height-28);const img=$('#migrationImagePreview');img.src=canvas.toDataURL('image/png');$('#migrationImageModal').hidden=false;}
  function closeImage(){const modal=$('#migrationImageModal');modal.hidden=true;$('#migrationImagePreview').removeAttribute('src')}

  function bind(){if(state.initialized)return;state.initialized=true;$('#migrationStatusTabs').addEventListener('click',e=>{const b=e.target.closest('[data-migration-status]');if(!b)return;state.status=b.dataset.migrationStatus;$('#migrationStatusTabs').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));loadList()});let timer;$('#migrationSearch').addEventListener('input',e=>{state.search=e.target.value.trim();clearTimeout(timer);timer=setTimeout(loadList,250)});$('#migrationRefresh').onclick=loadList;$('#migrationRows').addEventListener('click',e=>{const row=e.target.closest('[data-migration-id]');if(row)openDetail(Number(row.dataset.migrationId))});$('#migrationCards').addEventListener('click',e=>{const row=e.target.closest('[data-migration-id]');if(row)openDetail(Number(row.dataset.migrationId))});$('#migrationExcelExport').onclick=exportExcel;$('#migrationImportTemplate').onclick=downloadImportTemplate;$('#migrationExcelImport').onclick=openImport;$('#migrationImageDownload').onclick=imageDownload;$('#migrationDeletedOpen').onclick=loadDeleted;syncImportAccess();document.querySelectorAll('[data-migration-image-close]').forEach(b=>b.onclick=closeImage);document.querySelector('[data-panel="migrationPanel"]')?.addEventListener('click',()=>loadList());window.addEventListener('ezpk-admin-ready',()=>{setTimeout(()=>{$('#migrationDeletedOpen').hidden=!isSuper();syncImportAccess();if(window.EZPKAdminAccess?.has?.('migration'))loadList()},0)});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();
