(() => {
  'use strict';
  const $=s=>document.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const STATUS_KO={received:'접수됨',reviewing:'검토 중',approved:'승인',rejected:'거절'};
  const STATUS_EN={received:'Received',reviewing:'Reviewing',approved:'Approved',rejected:'Rejected'};
  const CONTACT_KO={not_contacted:'미연락',contacted:'연락 완료'};
  const CONTACT_EN={not_contacted:'Not Contacted',contacted:'Contacted'};
  const TIER_KO={gray:'일반',blue:'중급',purple:'고급',gold:'특급'};
  const TIER_EN={gray:'Normal',blue:'Intermediate',purple:'Advanced',gold:'Special'};
  const FIELD_KO={playerName:'게임 닉네임',gameUid:'게임 UID',discord:'Discord',currentState:'현재 서버',currentAlliance:'현재 연맹',vehicle1PowerValue:'1번 차량 파워',vehicle1PowerUnit:'1번 차량 단위',vehicle2PowerValue:'2번 차량 파워',vehicle2PowerUnit:'2번 차량 단위',industryLevel:'산업 레벨',spendingLevel:'과금 타입',migrationTier:'이민 등급',migrationReason:'이민 신청 사유',additionalNotes:'추가 전달사항',migrationGroup:'함께 이민하는 그룹',referrer:'추천인',applicationStatus:'신청 상태',contactStatus:'연락 상태',adminMemo:'관리자 메모',rejectionReason:'거절 사유',deleted:'삭제 상태'};
  const ACTION_KO={application_status_changed:'신청 상태 변경',application_status_bulk_changed:'신청 상태 일괄 변경',contact_status_changed:'연락 상태 변경',admin_memo_changed:'관리자 메모 변경',application_content_edited:'신청 내용 수정',application_deleted:'신청서 삭제',application_restored:'신청서 복구'};
  const TIER_ORDER={gold:4,purple:3,blue:2,gray:1};
  const state={items:[],status:'',search:'',sort:'tier',selected:new Set(),bulkStatus:'',current:null,history:[],initialized:false,loading:false,deletedItems:[],view:'list',importData:null};

  function isSuper(){return String(window.EZPKAdminAccess?.state?.adminLevel||'').toLowerCase()==='super'}
  function dateTime(v){if(!v)return'-';const d=new Date(String(v).replace(' ','T')+'Z');return Number.isNaN(d.getTime())?String(v):d.toLocaleString('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});}
  function dateOnly(v){if(!v)return'-';const d=new Date(String(v).replace(' ','T')+'Z');return Number.isNaN(d.getTime())?String(v).slice(0,10):d.toLocaleDateString('ko-KR',{year:'2-digit',month:'2-digit',day:'2-digit'});}
  function power(v,u){return v!=null&&u?`${v} ${u}`:'미입력'}
  function spendingKo(v){v=Number(v);return v<=3?'무과금 / 소과금':v<=6?'중과금':v<=8?'고과금':'핵과금'}
  function spendingEn(v){v=Number(v);return v<=3?'Free / Light Spender':v<=6?'Moderate Spender':v<=8?'Heavy Spender':'Whale'}
  function badgeStatus(v){return `<span class="migration-status-badge ${esc(v)}">${esc(STATUS_KO[v]||v)}</span>`}
  function badgeTier(v){return `<span class="migration-tier-badge ${esc(v)}">${esc(TIER_KO[v]||v)}</span>`}
  function badgeContact(v){return `<span class="migration-contact-badge ${esc(v)}">${esc(CONTACT_KO[v]||v)}</span>`}
  async function api(url,options={}){const r=await fetch(url,{credentials:'include',cache:'no-store',headers:{accept:'application/json',...(options.body?{'content-type':'application/json'}:{})},...options});const p=await r.json().catch(()=>null);if(!r.ok||!p?.ok){const e=new Error(p?.code||`HTTP_${r.status||0}`);e.code=p?.code||'REQUEST_FAILED';e.status=r.status;e.details=p?.details||null;throw e;}return p.data;}
  function errorMessage(error){const map={MIGRATION_APPLICATION_EXISTS:'같은 UID의 활성 이민 신청이 이미 존재합니다.',MIGRATION_REJECTION_REASON_REQUIRED:'거절 사유를 입력해 주세요.',MIGRATION_APPLICATION_NOT_FOUND:'이민 신청을 찾을 수 없습니다.',SUPER_ADMIN_REQUIRED:'최고관리자만 사용할 수 있습니다.',ADMIN_MENU_FORBIDDEN:'이민 신청 메뉴 권한이 없습니다.',VALIDATION_ERROR:'입력 내용을 다시 확인해 주세요.',MIGRATION_IMPORT_ROW_LIMIT:'한 번에 최대 500건까지 업로드할 수 있습니다.',MIGRATION_IMPORT_INVALID_META:'공식 업로드 양식을 사용해 주세요.',PAYLOAD_TOO_LARGE:'업로드 데이터가 너무 큽니다.',MIGRATION_IMPORT_IDEMPOTENCY_CONFLICT:'같은 업로드 작업 키에 다른 파일이 사용되었습니다. 파일을 다시 선택해 주세요.',INTERNAL_ERROR:'서버 처리 중 오류가 발생했습니다. 배포 또는 데이터베이스 상태를 확인해 주세요.',REQUEST_FAILED:'서버 요청에 실패했습니다. 네트워크 또는 배포 상태를 확인해 주세요.'};return map[error?.code]||error?.message||'처리 중 오류가 발생했습니다.'}
  function showImportServerError(message){const stage=$('#migrationImportStage');if(!stage)return;let box=stage.querySelector('.migration-import-server-error');if(!box){box=document.createElement('div');box.className='migration-import-server-error';stage.prepend(box)}box.textContent=message;}
  function toast(msg,type='ok'){if(window.showAdminToast)window.showAdminToast(msg,type);else alert(msg)}

  function listCreatedAt(a){const raw=String(a?.createdAt||'').trim(),iso=/Z$|[+-]\d{2}:?\d{2}$/.test(raw)?raw:`${raw.replace(' ','T')}Z`,t=Date.parse(iso);return Number.isFinite(t)?t:Number.NEGATIVE_INFINITY}
  function listStable(a,b){return listCreatedAt(b)-listCreatedAt(a)||Number(b.id||0)-Number(a.id||0)}
  function sortMigrationListItems(items){return [...items].sort((a,b)=>{if(state.sort==='application')return listStable(a,b);if(state.sort==='server')return serverNumber(a.currentState)-serverNumber(b.currentState)||listStable(a,b);if(state.sort==='vehicle1')return exportPowerNormalized(b,'vehicle1')-exportPowerNormalized(a,'vehicle1')||exportPowerNormalized(b,'vehicle2')-exportPowerNormalized(a,'vehicle2')||exportIndustry(b)-exportIndustry(a)||listStable(a,b);if(state.sort==='industry')return exportIndustry(b)-exportIndustry(a)||listStable(a,b);if(state.sort==='nickname')return String(a.playerName||'').localeCompare(String(b.playerName||''),'ko',{numeric:true,sensitivity:'base'})||listStable(a,b);return (TIER_ORDER[b.migrationTier]||0)-(TIER_ORDER[a.migrationTier]||0)||exportPowerNormalized(b,'vehicle1')-exportPowerNormalized(a,'vehicle1')||exportPowerNormalized(b,'vehicle2')-exportPowerNormalized(a,'vehicle2')||exportIndustry(b)-exportIndustry(a)||listStable(a,b)})}
  function clearSelection(){state.selected.clear();state.bulkStatus='';renderSelectionState()}
  function renderSortMenu(){document.querySelectorAll('[data-migration-sort]').forEach(b=>{const on=b.dataset.migrationSort===state.sort;b.classList.toggle('selected',on);b.setAttribute('aria-checked',on?'true':'false');const mark=b.querySelector('.migration-sort-check');if(mark)mark.textContent=on?'✓':''})}
  function renderSelectionState(){const items=sortMigrationListItems(state.items),ids=items.map(x=>Number(x.id)),selectedIds=ids.filter(id=>state.selected.has(id)),all=ids.length>0&&selectedIds.length===ids.length,master=$('#migrationSelectAll'),count=$('#migrationSelectedCount'),actions=$('#migrationBulkActions'),bulk=$('#migrationBulkStatus'),apply=$('#migrationBulkApply');if(master){master.checked=all;master.indeterminate=selectedIds.length>0&&!all;master.disabled=!ids.length}if(count)count.textContent=`${selectedIds.length}명 선택됨`;if(actions)actions.hidden=selectedIds.length===0;if(bulk)bulk.value=state.bulkStatus||'';if(apply)apply.disabled=selectedIds.length===0||!state.bulkStatus;document.querySelectorAll('[data-migration-select]').forEach(input=>{const id=Number(input.value);input.checked=state.selected.has(id);input.closest('[data-migration-id]')?.classList.toggle('selected',input.checked)})}
  async function loadList(){if(state.loading)return;state.loading=true;$('#migrationListStatus').textContent='불러오는 중...';try{const p=new URLSearchParams({limit:'500',detail:'1'});if(state.status)p.set('status',state.status);if(state.search)p.set('search',state.search);const data=await api(`/api/admin/migration?${p}`);state.items=data.items||[];const valid=new Set(state.items.map(x=>Number(x.id)));[...state.selected].forEach(id=>{if(!valid.has(id))state.selected.delete(id)});renderList();}catch(e){$('#migrationListStatus').textContent='이민 신청 목록을 불러오지 못했습니다.';$('#migrationRows').innerHTML='<tr><td colspan="6">목록을 불러오지 못했습니다.</td></tr>';toast(errorMessage(e),'error')}finally{state.loading=false}}
  function renderList(){state.view='list';$('#migrationListView').hidden=false;$('#migrationDetailView').hidden=true;$('#migrationDeletedView').hidden=true;$('#migrationDeletedOpen').hidden=!isSuper();const items=sortMigrationListItems(state.items);$('#migrationListStatus').textContent=items.length?`총 ${items.length}건`:(state.search?'검색 결과가 없습니다.':'접수된 이민 신청이 없습니다.');$('#migrationRows').innerHTML=items.map(x=>`<tr data-migration-id="${x.id}"><td class="migration-select-cell"><input type="checkbox" data-migration-select value="${x.id}" aria-label="${esc(x.playerName)} 선택"></td><td>${esc(dateOnly(x.createdAt))}</td><td><strong>${esc(x.playerName)}</strong></td><td>${esc(x.currentState)}</td><td>${badgeTier(x.migrationTier)}</td><td>${badgeStatus(x.applicationStatus)}</td></tr>`).join('')||'<tr><td colspan="6">표시할 신청이 없습니다.</td></tr>';$('#migrationCards').innerHTML=items.map(x=>`<article class="migration-card" data-migration-id="${x.id}"><div class="migration-card-top"><label class="migration-card-select"><input type="checkbox" data-migration-select value="${x.id}" aria-label="${esc(x.playerName)} 선택"><span></span></label><strong>${esc(x.playerName)}</strong>${badgeStatus(x.applicationStatus)}</div><div class="migration-card-meta"><span>${esc(dateOnly(x.createdAt))}</span><span>서버 ${esc(x.currentState)}</span>${badgeTier(x.migrationTier)}</div></article>`).join('');renderSortMenu();renderSelectionState()}
  function selectedApplications(){const selected=state.selected;return state.items.filter(x=>selected.has(Number(x.id)))}
  function bulkStatusDistribution(items){const c={received:0,reviewing:0,approved:0,rejected:0};items.forEach(x=>{if(c[x.applicationStatus]!=null)c[x.applicationStatus]++});return Object.entries(c).filter(([,n])=>n).map(([k,n])=>`${STATUS_KO[k]||k} ${n}건`).join(' · ')}
  function confirmBulkStatus(status){return new Promise(resolve=>{const items=selectedApplications(),host=$('#migrationConfirmModal'),label=STATUS_KO[status]||status;host.hidden=false;host.innerHTML=`<div class="migration-confirm-backdrop" data-confirm-cancel></div><section class="migration-confirm-card"><h3>선택한 ${items.length}건을 ${esc(label)} 상태로 변경하시겠습니까?</h3><p>${esc(bulkStatusDistribution(items))} → ${esc(label)}</p>${status==='rejected'?'<label class="migration-bulk-reason"><span>거절 사유</span><textarea id="migrationBulkRejectionReason" maxlength="2000" placeholder="선택한 신청에 공통으로 기록할 거절 사유"></textarea><small id="migrationBulkReasonError" hidden>거절 사유를 입력해 주세요.</small></label>':''}<div class="migration-confirm-actions"><button class="secondary" type="button" data-confirm-cancel>취소</button><button class="${status==='rejected'?'danger':'primary'}" type="button" data-confirm-ok>${items.length}건 ${esc(label)}으로 변경</button></div></section>`;const done=v=>{host.hidden=true;host.innerHTML='';resolve(v)};host.querySelectorAll('[data-confirm-cancel]').forEach(b=>b.onclick=()=>done(null));host.querySelector('[data-confirm-ok]').onclick=()=>{const reason=status==='rejected'?String($('#migrationBulkRejectionReason')?.value||'').trim():'';if(status==='rejected'&&!reason){const e=$('#migrationBulkReasonError');if(e)e.hidden=false;return}done({reason})}})}
  function showBulkResult(data){const host=$('#migrationConfirmModal'),failures=data.failures||[];host.hidden=false;host.innerHTML=`<div class="migration-confirm-backdrop" data-bulk-result-close></div><section class="migration-confirm-card"><h3>대량 상태 변경 결과</h3><p>${Number(data.succeeded||0)}건 변경 완료 / ${Number(data.failed||0)}건 실패</p>${failures.length?`<div class="migration-bulk-failures">${failures.map(x=>`<div><strong>${esc(x.playerName||`ID ${x.id}`)}</strong><span>${esc(x.message||'변경하지 못했습니다.')}</span></div>`).join('')}</div>`:''}<div class="migration-confirm-actions"><button class="primary" type="button" data-bulk-result-close>확인</button></div></section>`;host.querySelectorAll('[data-bulk-result-close]').forEach(b=>b.onclick=()=>{host.hidden=true;host.innerHTML=''})}
  async function applyBulkStatus(){const ids=[...state.selected],status=state.bulkStatus;if(!ids.length||!status)return;const confirmed=await confirmBulkStatus(status);if(!confirmed)return;const button=$('#migrationBulkApply');button.disabled=true;button.textContent='변경 중...';try{const versions=selectedApplications().map(x=>({id:Number(x.id),updatedAt:x.updatedAt||null,applicationStatus:x.applicationStatus||null}));const data=await api('/api/admin/migration/bulk-status',{method:'POST',body:JSON.stringify({ids,versions,status,rejectionReason:confirmed.reason||''})});toast(`${Number(data.succeeded||0)}건 변경 완료${Number(data.failed||0)?` / ${Number(data.failed)}건 실패`:''}`,Number(data.failed||0)?'error':'ok');state.selected.clear();state.bulkStatus='';await loadList();if(Number(data.failed||0)>0)showBulkResult(data);}catch(e){toast(errorMessage(e),'error')}finally{if(button){button.textContent='적용';button.disabled=false}renderSelectionState()}}
  async function openDetail(id){try{const data=await api(`/api/admin/migration/${id}`);state.current=data.application;state.history=data.history||[];state.view='detail';renderDetail(data);}catch(e){toast(errorMessage(e),'error')}}
  function detailRow(label,value,full=false){return `<div class="migration-detail-row${full?' full':''}"><dt>${esc(label)}</dt><dd>${esc(value==null||value===''?'미입력':value)}</dd></div>`}
  function detailCard(title,rows){return `<section class="migration-detail-card"><h4>${esc(title)}</h4><dl class="migration-detail-grid">${rows}</dl></section>`}
  function renderHistory(){const first=`<div class="migration-history-item"><strong>신청 접수</strong><small>${esc(dateTime(state.current.createdAt))}</small></div>`;const logs=state.history.map(h=>{const before=h.before||{},after=h.after||{};const keys=[...new Set([...Object.keys(before),...Object.keys(after)])];const changes=keys.map(k=>`${FIELD_KO[k]||k}: ${formatAuditValue(k,before[k])} → ${formatAuditValue(k,after[k])}`).join('\n');return `<div class="migration-history-item"><strong>${esc(ACTION_KO[h.action]||h.action)}</strong><small>${esc(dateTime(h.createdAt))} · ${esc(h.actorNickname||'-')}</small>${changes?`<div class="migration-history-change">${esc(changes)}</div>`:''}</div>`}).join('');return first+logs}
  function formatAuditValue(key,value){if(value==null||value==='')return '미입력';if(key==='applicationStatus')return STATUS_KO[value]||value;if(key==='contactStatus')return CONTACT_KO[value]||value;if(key==='migrationTier')return TIER_KO[value]||value;return String(value)}
  function renderDetail(data){const a=state.current;$('#migrationListView').hidden=true;$('#migrationDeletedView').hidden=true;const host=$('#migrationDetailView');host.hidden=false;const deleted=Boolean(a.deletedAt);host.innerHTML=`<div class="migration-detail-toolbar"><button class="migration-back-button" type="button" data-migration-back>${deleted?'삭제된 신청':'목록'}으로 돌아가기</button></div><section class="migration-detail-hero"><div><h3>${esc(a.playerName)}</h3><div class="migration-detail-meta">서버 ${esc(a.currentState)} · ${esc(TIER_KO[a.migrationTier]||a.migrationTier)} · ${esc(dateTime(a.createdAt))} 신청</div></div><div class="migration-detail-badges">${badgeStatus(a.applicationStatus)}${badgeContact(a.contactStatus)}${badgeTier(a.migrationTier)}</div></section>${deleted?renderDeletedControls(a):renderAdminControls(a)}<div class="migration-detail-sections">${detailCard('신청자 정보',detailRow('게임 닉네임',a.playerName)+detailRow('게임 UID',a.gameUid)+detailRow('Discord',a.discord))}${detailCard('현재 정보',detailRow('현재 서버',a.currentState)+detailRow('현재 연맹',a.currentAlliance))}${detailCard('이민 프로필',detailRow('1번 차량 파워',power(a.vehicle1PowerValue,a.vehicle1PowerUnit))+detailRow('2번 차량 파워',power(a.vehicle2PowerValue,a.vehicle2PowerUnit))+detailRow('산업 레벨',`${a.industryLevel} / 10`)+detailRow('과금 타입',`${a.spendingLevel} / 10 · ${spendingKo(a.spendingLevel)}`))}${detailCard('이민 등급',detailRow('이민 등급',TIER_KO[a.migrationTier]||a.migrationTier))}${detailCard('이민 사유',detailRow('이민 신청 사유',a.migrationReason,true)+detailRow('추가 전달사항',a.additionalNotes,true))}${detailCard('동반 이민',detailRow('함께 이민하는 그룹',a.migrationGroup)+detailRow('추천인',a.referrer))}<section class="migration-detail-card"><h4>처리 이력</h4><div class="migration-history">${renderHistory()}</div></section></div>${!deleted&&isSuper()?`<div class="migration-super-actions"><section class="migration-super-card"><h4>최고관리자 관리</h4><button class="secondary" type="button" data-migration-edit>신청 내용 수정</button></section><section class="migration-super-card migration-danger-zone"><h4>위험 작업</h4><button class="danger" type="button" data-migration-delete>신청서 삭제</button></section></div>`:''}`;bindDetailEvents();}
  function renderAdminControls(a){return `<section class="migration-admin-controls"><div class="migration-admin-control"><label>신청 상태</label><select id="migrationDetailStatus"><option value="received" ${a.applicationStatus==='received'?'selected':''}>접수됨</option><option value="reviewing" ${a.applicationStatus==='reviewing'?'selected':''}>검토 중</option><option value="approved" ${a.applicationStatus==='approved'?'selected':''}>승인</option><option value="rejected" ${a.applicationStatus==='rejected'?'selected':''}>거절</option></select><textarea id="migrationRejectionReason" placeholder="거절 사유" ${a.applicationStatus==='rejected'?'':'hidden'}>${esc(a.rejectionReason||'')}</textarea><div class="migration-admin-control-actions"><button class="primary" type="button" data-migration-status-save>상태 저장</button></div></div><div class="migration-admin-control"><label>연락 상태</label><select id="migrationDetailContact"><option value="not_contacted" ${a.contactStatus==='not_contacted'?'selected':''}>미연락</option><option value="contacted" ${a.contactStatus==='contacted'?'selected':''}>연락 완료</option></select><div class="migration-admin-control-actions"><button class="primary" type="button" data-migration-contact-save>연락 상태 저장</button></div></div><div class="migration-admin-control full"><label>관리자 메모</label><textarea id="migrationAdminMemo" maxlength="2000" placeholder="운영진 내부 메모">${esc(a.adminMemo||'')}</textarea><div class="migration-admin-control-actions"><button class="primary" type="button" data-migration-memo-save>메모 저장</button></div></div></section>`}
  function renderDeletedControls(a){return `<section class="migration-admin-controls"><div class="migration-admin-control full"><label>삭제 정보</label><div class="migration-detail-meta">삭제 처리자: ${esc(a.deletedByNickname||'-')} · 삭제 일시: ${esc(dateTime(a.deletedAt))}</div><div class="migration-admin-control-actions"><button class="primary" type="button" data-migration-restore>복구</button></div></div></section>`}
  function bindDetailEvents(){const status=$('#migrationDetailStatus');status?.addEventListener('change',()=>{$('#migrationRejectionReason').hidden=status.value!=='rejected'});$('[data-migration-back]')?.addEventListener('click',()=>state.current?.deletedAt?renderDeletedList():renderList());$('[data-migration-status-save]')?.addEventListener('click',saveStatus);$('[data-migration-contact-save]')?.addEventListener('click',saveContact);$('[data-migration-memo-save]')?.addEventListener('click',saveMemo);$('[data-migration-edit]')?.addEventListener('click',renderEdit);$('[data-migration-delete]')?.addEventListener('click',deleteCurrent);$('[data-migration-restore]')?.addEventListener('click',restoreCurrent)}
  async function saveStatus(){const status=$('#migrationDetailStatus').value,reason=$('#migrationRejectionReason').value.trim();if(status==='rejected'&&!reason){toast('거절 사유를 입력해 주세요.','error');return}if(['approved','rejected'].includes(status)){const ok=await confirmAction(status==='approved'?'이 신청을 승인하시겠습니까?':'이 신청을 거절하시겠습니까?',status==='approved'?'승인 처리 후에도 연락 상태는 자동 변경되지 않습니다.':'거절 사유는 관리자 내부 기록으로 저장됩니다.',status==='approved'?'승인':'거절',status==='rejected');if(!ok)return}try{await api(`/api/admin/migration/${state.current.id}/status`,{method:'PUT',body:JSON.stringify({status,rejectionReason:reason})});toast('신청 상태를 저장했습니다.');await loadList();await openDetail(state.current.id);}catch(e){toast(errorMessage(e),'error')}}
  async function saveContact(){try{await api(`/api/admin/migration/${state.current.id}/contact`,{method:'PUT',body:JSON.stringify({status:$('#migrationDetailContact').value})});toast('연락 상태를 저장했습니다.');await loadList();await openDetail(state.current.id);}catch(e){toast(errorMessage(e),'error')}}
  async function saveMemo(){try{await api(`/api/admin/migration/${state.current.id}/memo`,{method:'PUT',body:JSON.stringify({memo:$('#migrationAdminMemo').value})});toast('관리자 메모를 저장했습니다.');await openDetail(state.current.id);}catch(e){toast(errorMessage(e),'error')}}
  function renderEdit(){if(!isSuper())return;const a=state.current,host=$('#migrationDetailView');host.innerHTML=`<div class="migration-detail-toolbar"><button class="migration-back-button" type="button" data-migration-edit-cancel>취소</button><strong>신청 내용 수정</strong></div><section class="migration-detail-card"><div class="migration-edit-grid">${editField('playerName','게임 닉네임',a.playerName)}${editField('gameUid','게임 UID',a.gameUid,'text','16')}${editField('discord','Discord',a.discord||'')}${editField('currentState','현재 서버',a.currentState)}${editField('currentAlliance','현재 연맹',a.currentAlliance||'')}${editPower('vehicle1','1번 차량 파워',a.vehicle1PowerValue,a.vehicle1PowerUnit)}${editPower('vehicle2','2번 차량 파워',a.vehicle2PowerValue??'',a.vehicle2PowerUnit||'')}${editSelect('industryLevel','산업 레벨',a.industryLevel,Array.from({length:10},(_,i)=>[i+1,String(i+1)]))}${editSelect('spendingLevel','과금 타입',a.spendingLevel,Array.from({length:10},(_,i)=>[i+1,`${i+1} · ${spendingKo(i+1)}`]))}${editSelect('migrationTier','이민 등급',a.migrationTier,Object.entries(TIER_KO))}${editArea('migrationReason','이민 신청 사유',a.migrationReason,true)}${editArea('additionalNotes','추가 전달사항',a.additionalNotes||'',true)}${editField('migrationGroup','함께 이민하는 그룹',a.migrationGroup||'')}${editField('referrer','추천인',a.referrer||'')}</div><div class="migration-admin-control-actions" style="margin-top:18px"><button class="secondary" type="button" data-migration-edit-cancel>취소</button><button class="primary" type="button" data-migration-edit-save>변경사항 저장</button></div></section>`;host.querySelectorAll('[data-migration-edit-cancel]').forEach(b=>b.onclick=()=>openDetail(a.id));$('[data-migration-edit-save]').onclick=saveEdit;}
  function editField(key,label,value,type='text',maxlength=''){return `<div class="migration-edit-field"><label>${esc(label)}</label><input data-edit-field="${key}" type="${type}" value="${esc(value)}" ${maxlength?`maxlength="${maxlength}"`:''}></div>`}
  function editArea(key,label,value,full=false){return `<div class="migration-edit-field${full?' full':''}"><label>${esc(label)}</label><textarea data-edit-field="${key}" maxlength="2000">${esc(value)}</textarea></div>`}
  function editPower(prefix,label,value,unit){return `<div class="migration-edit-field"><label>${esc(label)}</label><div class="migration-power-edit"><input data-edit-field="${prefix}PowerValue" type="text" inputmode="decimal" value="${esc(value)}"><select data-edit-field="${prefix}PowerUnit"><option value="" ${!unit?'selected':''}>-</option><option value="G" ${unit==='G'?'selected':''}>G</option><option value="M" ${unit==='M'?'selected':''}>M</option></select></div></div>`}
  function editSelect(key,label,value,options){return `<div class="migration-edit-field"><label>${esc(label)}</label><select data-edit-field="${key}">${options.map(([v,l])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select></div>`}
  async function saveEdit(){const payload={};document.querySelectorAll('[data-edit-field]').forEach(el=>payload[el.dataset.editField]=el.value.trim());payload.industryLevel=Number(payload.industryLevel);payload.spendingLevel=Number(payload.spendingLevel);payload.vehicle2PowerValue=payload.vehicle2PowerValue||null;payload.vehicle2PowerUnit=payload.vehicle2PowerUnit||null;const ok=await confirmAction('신청 내용을 수정하시겠습니까?','변경 전/후 값과 수정자, 시각이 처리 이력에 기록됩니다.','저장');if(!ok)return;try{await api(`/api/admin/migration/${state.current.id}`,{method:'PUT',body:JSON.stringify(payload)});toast('신청 내용을 수정했습니다.');await loadList();await openDetail(state.current.id);}catch(e){toast(errorMessage(e),'error')}}
  async function deleteCurrent(){const ok=await confirmAction('이 신청서를 삭제하시겠습니까?','신청서는 영구 삭제되지 않으며 최고관리자가 삭제된 신청에서 복구할 수 있습니다.','삭제',true);if(!ok)return;try{await api(`/api/admin/migration/${state.current.id}`,{method:'DELETE'});toast('신청서를 삭제했습니다.');await loadList();renderList();}catch(e){toast(errorMessage(e),'error')}}
  async function restoreCurrent(){const ok=await confirmAction('이 신청서를 복구하시겠습니까?','복구하면 삭제 전 신청 상태와 연락 상태가 그대로 유지됩니다.','복구');if(!ok)return;try{await api(`/api/admin/migration/${state.current.id}/restore`,{method:'POST',body:'{}'});toast('신청서를 복구했습니다.');await loadDeleted();}catch(e){toast(errorMessage(e),'error')}}
  function confirmAction(title,message,confirmText,danger=false){return new Promise(resolve=>{const host=$('#migrationConfirmModal');host.hidden=false;host.innerHTML=`<div class="migration-confirm-backdrop" data-confirm-cancel></div><section class="migration-confirm-card"><h3>${esc(title)}</h3><p>${esc(message)}</p><div class="migration-confirm-actions"><button class="secondary" type="button" data-confirm-cancel>취소</button><button class="${danger?'danger':'primary'}" type="button" data-confirm-ok>${esc(confirmText)}</button></div></section>`;const done=v=>{host.hidden=true;host.innerHTML='';resolve(v)};host.querySelectorAll('[data-confirm-cancel]').forEach(b=>b.onclick=()=>done(false));host.querySelector('[data-confirm-ok]').onclick=()=>done(true);});}

  async function loadDeleted(){try{const data=await api('/api/admin/migration/deleted');state.deletedItems=data.items||[];renderDeletedList();}catch(e){toast(errorMessage(e),'error')}}
  function renderDeletedList(){state.view='deleted';$('#migrationListView').hidden=true;$('#migrationDetailView').hidden=true;const host=$('#migrationDeletedView');host.hidden=false;host.innerHTML=`<div class="migration-deleted-toolbar"><button class="migration-back-button" type="button" data-deleted-back>목록으로 돌아가기</button><strong>삭제된 신청</strong></div><div class="migration-deleted-list">${state.deletedItems.map(x=>`<article class="migration-deleted-item" data-deleted-id="${x.id}"><span>${esc(dateOnly(x.deletedAt))}</span><strong>${esc(x.playerName)}</strong><span>서버 ${esc(x.currentState)}</span><span>${esc(STATUS_KO[x.applicationStatus]||x.applicationStatus)}</span></article>`).join('')||'<div class="migration-empty">삭제된 신청이 없습니다.</div>'}</div>`;host.querySelector('[data-deleted-back]').onclick=()=>renderList();host.querySelectorAll('[data-deleted-id]').forEach(el=>el.onclick=()=>openDetail(Number(el.dataset.deletedId)));}

  const IMPORT_TEMPLATE_VERSION='EZPK Migration Import v1';
  const IMPORT_TEMPLATE_FILE='EZPK_이민신청_업로드양식_v1.xlsx';
  const IMPORT_MAX_FILE_BYTES=5*1024*1024;
  const IMPORT_HEADERS=['게임 닉네임','UID','Discord','현재 서버','현재 연맹','1번 차량 파워','1번 차량 단위','2번 차량 파워','2번 차량 단위','산업 레벨','과금 타입','이민 등급','이민 신청 사유','추가 전달사항','함께 이민하는 그룹','추천인'];

  function syncImportAccess(){const superAdmin=isSuper();const t=$('#migrationImportTemplate'),i=$('#migrationExcelImport');if(t)t.hidden=!superAdmin;if(i)i.hidden=!superAdmin;}
  function downloadImportTemplate(){if(!isSuper()){toast('최고관리자만 사용할 수 있습니다.','error');return}const a=document.createElement('a');a.href=`./${encodeURIComponent(IMPORT_TEMPLATE_FILE)}`;a.download=IMPORT_TEMPLATE_FILE;document.body.appendChild(a);a.click();a.remove();}
  function closeImport(){const host=$('#migrationImportModal');host.hidden=true;host.innerHTML='';state.importData=null;}
  function importStatusBadge(row){const labels={ready:'등록 가능',existing:'기존 신청 제외',file_duplicate:'파일 내 중복 제외',invalid:'입력 오류'};return `<span class="migration-import-status ${esc(row.status)}">${esc(labels[row.status]||'오류')}</span>`}
  function importSummaryCards(summary={}){return `<div class="migration-import-summary"><button type="button" data-import-filter="all" class="active"><span>전체</span><strong>${Number(summary.total||0)}</strong></button><button type="button" data-import-filter="ready"><span>등록 가능</span><strong>${Number(summary.ready||0)}</strong></button><button type="button" data-import-filter="existing"><span>기존 신청 제외</span><strong>${Number(summary.existing||0)}</strong></button><button type="button" data-import-filter="file_duplicate"><span>파일 내 중복 제외</span><strong>${Number(summary.fileDuplicate||0)}</strong></button><button type="button" data-import-filter="invalid"><span>입력 오류</span><strong>${Number(summary.invalid||0)}</strong></button></div>`}
  async function loadImportHistory(){const host=$('#migrationImportHistory');if(!host)return;host.innerHTML='<div class="migration-import-muted">최근 업로드 이력을 불러오는 중...</div>';try{const data=await api('/api/admin/migration/import/batches');const items=data.items||[];if(data.schemaReady===false){host.innerHTML='<div class="migration-import-muted">DB Import migration(0029)이 아직 적용되지 않아 호환 모드로 동작합니다. 등록은 가능하지만 Batch 이력은 migration 적용 후 기록됩니다.</div>';return}host.innerHTML=items.length?items.map(x=>`<div class="migration-import-history-item"><div><strong>${esc(x.fileName)}</strong><small>${esc(dateTime(x.committedAt||x.createdAt))} · ${esc(x.actorNickname||'-')}</small></div><div><span>등록 ${Number(x.imported||0)}</span><span>제외 ${Number(x.skipped||0)}</span><span>실패 ${Number(x.failed||0)}</span></div></div>`).join(''):'<div class="migration-import-muted">업로드 이력이 없습니다.</div>';}catch(e){host.innerHTML=`<div class="migration-import-muted">업로드 이력을 불러오지 못했습니다. ${esc(errorMessage(e))}${e?.status?` (HTTP ${e.status})`:''}</div>`;}}
  function openImport(){if(!isSuper()){toast('최고관리자만 사용할 수 있습니다.','error');return}const host=$('#migrationImportModal');host.hidden=false;host.innerHTML=`<div class="migration-import-backdrop" data-import-close></div><section class="migration-import-card"><header><div><h3>이민 신청 엑셀 업로드</h3><p>공식 양식의 신규 신청을 검토한 뒤 등록합니다.</p></div><button type="button" data-import-close aria-label="닫기">×</button></header><div class="migration-import-guide"><strong>업로드 전 확인</strong><span>.xlsx 파일만 가능 · 최대 500건</span><span>UID는 16자리 숫자의 텍스트 셀이어야 합니다.</span><span>기존 신청·파일 내 중복·입력 오류 행만 제외하고 정상 행은 등록됩니다.</span></div><div id="migrationImportStage"><label class="migration-import-file"><span>파일 선택</span><input id="migrationImportFile" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"></label><div id="migrationImportFileStatus" class="migration-import-muted">업로드 양식을 선택해 주세요.</div><div class="migration-import-actions"><button class="secondary" type="button" data-import-close>취소</button><button id="migrationImportPreviewButton" class="primary" type="button" disabled>업로드 검토</button></div></div><section class="migration-import-history"><h4>최근 업로드 이력</h4><div id="migrationImportHistory"></div></section></section>`;host.querySelectorAll('[data-import-close]').forEach(b=>b.onclick=closeImport);$('#migrationImportFile').onchange=handleImportFile;$('#migrationImportPreviewButton').onclick=previewImport;loadImportHistory();}
  async function sha256File(buffer){const hash=await crypto.subtle.digest('SHA-256',buffer);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}
  function cellRaw(sheet,r,c){const cell=sheet[XLSX.utils.encode_cell({r,c})];return cell?cell.v:''}
  function cellType(sheet,r,c){const cell=sheet[XLSX.utils.encode_cell({r,c})];return cell?.t||''}
  function parseImportWorkbook(buffer,file){if(!window.XLSX)throw new Error('Excel 라이브러리를 불러오지 못했습니다.');const wb=XLSX.read(buffer,{type:'array',cellDates:false,cellText:false});const guide=wb.Sheets['안내'];const version=String(guide?.B2?.v||'').trim();if(version!==IMPORT_TEMPLATE_VERSION){const e=new Error('공식 업로드 양식이 아니거나 양식 버전이 다릅니다.');e.code='MIGRATION_IMPORT_INVALID_META';throw e}const sheet=wb.Sheets['이민신청 업로드'];if(!sheet)throw new Error('이민신청 업로드 시트를 찾을 수 없습니다.');const range=XLSX.utils.decode_range(sheet['!ref']||'A1:P1');const headers=IMPORT_HEADERS.map((_,c)=>String(cellRaw(sheet,0,c)??'').trim());if(IMPORT_HEADERS.some((h,i)=>headers[i]!==h))throw new Error('업로드 양식의 열 제목이 변경되었습니다. 공식 양식을 다시 내려받아 주세요.');const rows=[];for(let r=1;r<=range.e.r;r++){const values=IMPORT_HEADERS.map((_,c)=>cellRaw(sheet,r,c));if(values.every(v=>String(v??'').trim()===''))continue;rows.push({rowNumber:r+1,playerName:values[0],gameUid:values[1],uidCellType:cellType(sheet,r,1),discord:values[2],currentState:values[3],currentAlliance:values[4],vehicle1PowerValue:values[5],vehicle1PowerUnit:values[6],vehicle2PowerValue:values[7],vehicle2PowerUnit:values[8],industryLevel:values[9],spendingLevel:values[10],migrationTier:values[11],migrationReason:values[12],additionalNotes:values[13],migrationGroup:values[14],referrer:values[15]});}if(!rows.length)throw new Error('등록할 신청 데이터가 없습니다.');if(rows.length>500)throw new Error('한 번에 최대 500건까지 업로드할 수 있습니다.');return rows;}
  async function handleImportFile(e){const file=e.target.files?.[0];const status=$('#migrationImportFileStatus'),button=$('#migrationImportPreviewButton');state.importData=null;button.disabled=true;if(!file){status.textContent='업로드 양식을 선택해 주세요.';return}if(!/\.xlsx$/i.test(file.name)){status.textContent='.xlsx 파일만 업로드할 수 있습니다.';return}if(file.size>IMPORT_MAX_FILE_BYTES){status.textContent='파일 크기는 5MB 이하여야 합니다.';return}try{const buffer=await file.arrayBuffer();const rows=parseImportWorkbook(buffer,file);const fileSha256=await sha256File(buffer);state.importData={fileName:file.name,fileSha256,rows,idempotencyKey:(crypto.randomUUID?crypto.randomUUID():`${Date.now()}_${Math.random().toString(36).slice(2)}`).replace(/[^A-Za-z0-9_-]/g,'_')};status.textContent=`${file.name} · ${rows.length}건을 확인했습니다.`;button.disabled=false;}catch(err){status.textContent=errorMessage(err);toast(errorMessage(err),'error')}}
  async function previewImport(){if(!state.importData)return;const button=$('#migrationImportPreviewButton');button.disabled=true;button.textContent='검토 중...';const oldError=$('#migrationImportStage')?.querySelector('.migration-import-server-error');if(oldError)oldError.remove();try{const data=await api('/api/admin/migration/import/preview',{method:'POST',body:JSON.stringify({templateVersion:IMPORT_TEMPLATE_VERSION,...state.importData})});renderImportPreview(data);}catch(e){const msg=`업로드 검토 실패: ${errorMessage(e)}${e?.status?` (HTTP ${e.status})`:''}`;showImportServerError(msg);toast(msg,'error');button.disabled=false;button.textContent='업로드 검토'}}
  function renderImportPreview(data){const stage=$('#migrationImportStage');const s=data.summary||{},rows=data.rows||[],compat=data.schemaReady===false?'<div class="migration-import-compat-note"><strong>호환 모드</strong><span>DB Import migration(0029)이 아직 적용되지 않았습니다. 정상 행 등록은 가능하며, 기존 UID/파일 중복 방어도 그대로 적용됩니다. Batch 이력만 기록되지 않습니다.</span></div>':'';const rowHtml=r=>{const messages=[...(r.errors||[]),...(r.notices||[])];return `<tr data-import-row-status="${esc(r.status)}"><td>${Number(r.rowNumber||0)}</td><td>${esc(r.playerName||'-')}</td><td>${esc(r.gameUid||'-')}</td><td>${importStatusBadge(r)}</td><td>${esc(messages.join(' / ')||'등록 가능')}</td></tr>`};stage.innerHTML=`<div class="migration-import-preview-head"><div><strong>업로드 검토 결과</strong><span>${esc(state.importData?.fileName||'')}</span></div><button id="migrationImportChangeFile" class="secondary" type="button">파일 다시 선택</button></div>${compat}${importSummaryCards(s)}<div class="migration-import-preview-note">정상 행만 등록됩니다. 제외/오류 항목을 누르면 해당 행만 확인할 수 있습니다.</div><div class="migration-import-preview-table-wrap"><table class="migration-import-preview-table"><thead><tr><th>행</th><th>닉네임</th><th>UID</th><th>결과</th><th>확인 내용</th></tr></thead><tbody>${rows.map(rowHtml).join('')}</tbody></table></div><div class="migration-import-actions"><button id="migrationImportCancelPreview" class="secondary" type="button">취소</button><button id="migrationImportCommit" class="primary" type="button" ${Number(s.ready||0)<1?'disabled':''}>신청서 ${Number(s.ready||0)}건 등록</button></div>`;stage.querySelectorAll('[data-import-filter]').forEach(btn=>btn.onclick=()=>{stage.querySelectorAll('[data-import-filter]').forEach(x=>x.classList.toggle('active',x===btn));const filter=btn.dataset.importFilter;stage.querySelectorAll('[data-import-row-status]').forEach(tr=>{tr.hidden=filter!=='all'&&tr.dataset.importRowStatus!==filter})});$('#migrationImportChangeFile').onclick=()=>{closeImport();openImport()};$('#migrationImportCancelPreview').onclick=closeImport;$('#migrationImportCommit').onclick=commitImport;}
  async function commitImport(){if(!state.importData)return;const btn=$('#migrationImportCommit');const ok=await confirmAction('검토된 신청서를 등록하시겠습니까?',`${btn?.textContent||'신청서 등록'} 후에는 일반 이민 신청과 동일하게 관리자 페이지에서 관리됩니다.`,'등록');if(!ok)return;btn.disabled=true;btn.textContent='등록 중...';const oldError=$('#migrationImportStage')?.querySelector('.migration-import-server-error');if(oldError)oldError.remove();try{const data=await api('/api/admin/migration/import/commit',{method:'POST',body:JSON.stringify({templateVersion:IMPORT_TEMPLATE_VERSION,...state.importData})});renderImportComplete(data);await loadList();}catch(e){const msg=`신청서 등록 실패: ${errorMessage(e)}${e?.status?` (HTTP ${e.status})`:''}`;showImportServerError(msg);toast(msg,'error');btn.disabled=false;btn.textContent='신청서 등록'}}
  function renderImportComplete(data){const s=data.summary||{},stage=$('#migrationImportStage');stage.innerHTML=`<div class="migration-import-complete"><div class="migration-import-complete-icon">✓</div><h4>엑셀 업로드가 완료되었습니다.</h4><p>등록된 신청은 즉시 이민 신청 목록과 UID 조회에 반영됩니다.</p><div class="migration-import-result-grid"><span>전체 <strong>${Number(s.total||0)}</strong></span><span>등록 <strong>${Number(s.imported||0)}</strong></span><span>제외 <strong>${Number(s.skipped||0)}</strong></span><span>실패 <strong>${Number(s.failed||0)}</strong></span></div><button id="migrationImportDone" class="primary" type="button">확인</button></div>`;$('#migrationImportDone').onclick=closeImport;loadImportHistory();}

  const TIER_COLORS={gray:{fill:'59616d',text:'F5F7FA',canvasFill:'#59616d',canvasText:'#f5f7fa'},blue:{fill:'2457A6',text:'EAF2FF',canvasFill:'#2457a6',canvasText:'#eaf2ff'},purple:{fill:'7138A8',text:'F5EAFF',canvasFill:'#7138a8',canvasText:'#f5eaff'},gold:{fill:'A97816',text:'FFF3CE',canvasFill:'#a97816',canvasText:'#fff3ce'}};
  function serverNumber(v){const m=String(v??'').match(/\d+/);return m?Number(m[0]):Number.POSITIVE_INFINITY}
  function exportPowerNormalized(a,prefix){const n=Number(a?.[`${prefix}PowerNormalized`]);if(Number.isFinite(n)&&n>0)return n;const value=Number(a?.[`${prefix}PowerValue`]);if(!Number.isFinite(value)||value<=0)return Number.NEGATIVE_INFINITY;return value*(String(a?.[`${prefix}PowerUnit`]||'').toUpperCase()==='G'?1000:1)}
  function exportIndustry(a){const n=Number(a?.industryLevel);return Number.isFinite(n)?n:Number.NEGATIVE_INFINITY}
  function exportCreatedAt(a){const raw=String(a?.createdAt||'').trim(),iso=/Z$|[+-]\d{2}:?\d{2}$/.test(raw)?raw:`${raw.replace(' ','T')}Z`,t=Date.parse(iso);return Number.isFinite(t)?t:Number.POSITIVE_INFINITY}
  function sortMigrationExportItems(items){return [...items].sort((a,b)=>serverNumber(a.currentState)-serverNumber(b.currentState)||exportPowerNormalized(b,'vehicle1')-exportPowerNormalized(a,'vehicle1')||exportPowerNormalized(b,'vehicle2')-exportPowerNormalized(a,'vehicle2')||exportIndustry(b)-exportIndustry(a)||exportCreatedAt(a)-exportCreatedAt(b)||Number(a.id||0)-Number(b.id||0))}
  async function fetchExportItems(){const p=new URLSearchParams({limit:'1000',detail:'1'});if(state.status)p.set('status',state.status);if(state.search)p.set('search',state.search);const data=await api(`/api/admin/migration?${p}`);return sortMigrationExportItems(data.items||[])}
  function styleExcelCell(cell,style){if(cell)cell.s={...(cell.s||{}),...style}}
  function excelMetaRows(total){return [['내보낸 시각',new Date().toLocaleString('ko-KR')],['상태 필터',state.status?(STATUS_KO[state.status]||state.status):'전체'],['검색어',state.search||'없음'],['총 인원',total],['정렬 기준','서버 오름차순 → 1번 차량 파워 내림차순 → 2번 차량 파워 내림차순 → 산업 레벨 내림차순 → 신청일 오름차순 → ID 오름차순']]}
  async function exportExcel(){if(!window.XLSX){toast('Excel 라이브러리를 불러오지 못했습니다.','error');return}try{const items=await fetchExportItems();if(!items.length){toast('엑셀로 내보낼 신청 목록이 없습니다.','error');return}const headers=['Application Date','Player Name','UID','Discord','Current State','Current Alliance','Vehicle 1 Power','Vehicle 2 Power','Industry Level','Spending Type','Migration Tier','Migration Reason','Additional Notes','Group / Friends','Referrer','Application Status','Contact Status'];const rows=items.map(a=>[a.createdAt,a.playerName,String(a.gameUid||''),a.discord||'',a.currentState,a.currentAlliance||'',power(a.vehicle1PowerValue,a.vehicle1PowerUnit).replace('미입력',''),power(a.vehicle2PowerValue,a.vehicle2PowerUnit).replace('미입력',''),`${a.industryLevel} / 10`,`${a.spendingLevel} / 10 · ${spendingEn(a.spendingLevel)}`,TIER_EN[a.migrationTier]||a.migrationTier,a.migrationReason,a.additionalNotes||'',a.migrationGroup||'',a.referrer||'',STATUS_EN[a.applicationStatus]||a.applicationStatus,CONTACT_EN[a.contactStatus]||a.contactStatus]);const wb=XLSX.utils.book_new(),ws=XLSX.utils.aoa_to_sheet([headers,...rows]);ws['!autofilter']={ref:`A1:Q${rows.length+1}`};ws['!cols']=[{wch:20},{wch:22},{wch:19},{wch:22},{wch:14},{wch:18},{wch:18},{wch:18},{wch:16},{wch:27},{wch:18},{wch:34},{wch:34},{wch:24},{wch:20},{wch:20},{wch:20}];for(let c=0;c<headers.length;c++){const cell=ws[XLSX.utils.encode_cell({r:0,c})];styleExcelCell(cell,{font:{bold:true,color:{rgb:'FFF1C2'}},fill:{patternType:'solid',fgColor:{rgb:'182231'}},alignment:{vertical:'center',horizontal:'center'},border:{bottom:{style:'thin',color:{rgb:'3C4A5C'}}}})}items.forEach((a,i)=>{const r=i+1;const uidCell=ws[XLSX.utils.encode_cell({r,c:2})];if(uidCell){uidCell.t='s';uidCell.z='@';styleExcelCell(uidCell,{numFmt:'@'})}const tierCell=ws[XLSX.utils.encode_cell({r,c:10})],colors=TIER_COLORS[a.migrationTier]||TIER_COLORS.gray;styleExcelCell(tierCell,{font:{bold:true,color:{rgb:colors.text}},fill:{patternType:'solid',fgColor:{rgb:colors.fill}},alignment:{horizontal:'center',vertical:'center'}});[4,6,7,8].forEach(c=>styleExcelCell(ws[XLSX.utils.encode_cell({r,c})],{alignment:{horizontal:'right'}}));});XLSX.utils.book_append_sheet(wb,ws,'Migration Applications');const info=XLSX.utils.aoa_to_sheet([['EZPK Migration Export',''],...excelMetaRows(items.length)]);info['!cols']=[{wch:24},{wch:82}];styleExcelCell(info.A1,{font:{bold:true,sz:16,color:{rgb:'A97816'}}});for(let r=1;r<=5;r++)styleExcelCell(info[XLSX.utils.encode_cell({r,c:0})],{font:{bold:true},fill:{patternType:'solid',fgColor:{rgb:'E9EDF3'}}});XLSX.utils.book_append_sheet(wb,info,'정보');XLSX.writeFile(wb,`EZPK_Migration_Applications_${new Date().toISOString().slice(0,10)}.xlsx`);}catch(e){toast(errorMessage(e),'error')}}
  function imagePower(a){return power(a.vehicle1PowerValue,a.vehicle1PowerUnit).replace('미입력','-').replace(/\s+/g,'')}
  function drawTierBadge(c,tier,x,y,w,h){const colors=TIER_COLORS[tier]||TIER_COLORS.gray,label=TIER_EN[tier]||String(tier||'-');c.fillStyle=colors.canvasFill;c.fillRect(x,y,w,h);c.fillStyle=colors.canvasText;c.font='700 18px Arial, sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText(label,x+w/2,y+h/2+1);c.textAlign='left';c.textBaseline='alphabetic'}
  function tierCounts(items){const counts={gold:0,purple:0,blue:0,gray:0};items.forEach(x=>{if(counts[x.migrationTier]!=null)counts[x.migrationTier]++});return counts}
  function drawTierSummary(c,counts,y){const cards=[['특급','gold'],['고급','purple'],['중급','blue'],['일반','gray']],startX=70,gap=14,w=303,h=56;cards.forEach(([label,tier],i)=>{const x=startX+i*(w+gap),colors=TIER_COLORS[tier];c.fillStyle='#0d131b';c.fillRect(x,y,w,h);c.strokeStyle=colors.canvasFill;c.lineWidth=2;c.strokeRect(x+.5,y+.5,w-1,h-1);c.fillStyle=colors.canvasFill;c.fillRect(x,y,5,h);c.fillStyle='#aeb8c6';c.font='700 17px Arial, sans-serif';c.fillText(label,x+20,y+34);c.fillStyle='#f1f4f8';c.font='700 24px Arial, sans-serif';c.textAlign='right';c.fillText(`${Number(counts[tier]||0)}명`,x+w-18,y+36);c.textAlign='left'})}
  function buildMigrationImagePage(items,pageIndex,pageCount,total,counts){const width=1400,rowH=58,headH=282,height=headH+rowH*(items.length+1)+72,canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const c=canvas.getContext('2d');c.fillStyle='#070a0f';c.fillRect(0,0,width,height);c.fillStyle='#e2bb64';c.font='700 42px Arial, sans-serif';c.fillText('EZPK Migration Applications',70,70);c.fillStyle='#9fa9b8';c.font='21px Arial, sans-serif';const filter=state.status?STATUS_EN[state.status]:'All',search=state.search?`   ·   Search: ${String(state.search).slice(0,26)}`:'';c.fillText(`Status: ${filter}   ·   Applications: ${total}${search}`,70,112);c.font='18px Arial, sans-serif';c.fillText(`Page ${pageIndex+1}/${pageCount}   ·   Generated: ${new Date().toLocaleString('en-US')}`,70,145);drawTierSummary(c,counts,166);const tableY=238,cols=[['State',70,155],['Player',225,435],['Tier',660,210],['Vehicle 1',870,235],['Industry',1105,205]];c.fillStyle='#111822';c.fillRect(55,tableY,width-110,rowH);c.fillStyle='#e2bb64';c.font='700 21px Arial, sans-serif';cols.forEach(([name,x])=>c.fillText(name,x,tableY+37));items.forEach((a,i)=>{const y=tableY+rowH*(i+1);c.fillStyle=i%2?'#0b1017':'#0e141d';c.fillRect(55,y,width-110,rowH);c.fillStyle='#e8edf4';c.font='21px Arial, sans-serif';c.fillText(String(a.currentState??'-'),70,y+37);c.fillText(String(a.playerName||'-').slice(0,30),225,y+37);drawTierBadge(c,a.migrationTier,670,y+13,170,32);c.textAlign='right';c.fillStyle='#e8edf4';c.font='700 21px Arial, sans-serif';c.fillText(imagePower(a),1075,y+37);c.fillText(a.industryLevel==null?'-':`Lv.${a.industryLevel}`,1265,y+37);c.textAlign='left';});c.fillStyle='#737e8c';c.font='17px Arial, sans-serif';c.fillText('EZPK · Migration List',70,height-28);return canvas}
  async function imageDownload(){try{const items=await fetchExportItems();if(!items.length){toast('이미지로 만들 신청 목록이 없습니다.','error');return}const pageSize=50,pageCount=Math.ceil(items.length/pageSize),counts=tierCounts(items),host=$('#migrationImagePreview');host.innerHTML='';for(let p=0;p<pageCount;p++){const pageItems=items.slice(p*pageSize,(p+1)*pageSize),canvas=buildMigrationImagePage(pageItems,p,pageCount,items.length,counts),url=canvas.toDataURL('image/png'),figure=document.createElement('figure'),img=document.createElement('img'),caption=document.createElement('figcaption'),link=document.createElement('a');img.src=url;img.alt=`EZPK Migration Applications ${p+1}/${pageCount}`;link.href=url;link.download=`EZPK_Migration_Applications_${new Date().toISOString().slice(0,10)}_${String(p+1).padStart(2,'0')}.png`;link.className='secondary migration-image-save';link.textContent=`PNG 다운로드 ${p+1}/${pageCount}`;caption.appendChild(link);figure.append(img,caption);host.appendChild(figure)}$('#migrationImageModal').hidden=false;}catch(e){toast(errorMessage(e),'error')}}
  function closeImage(){const modal=$('#migrationImageModal');modal.hidden=true;$('#migrationImagePreview').innerHTML=''}

  function bind(){if(state.initialized)return;state.initialized=true;$('#migrationStatusTabs').addEventListener('click',e=>{const b=e.target.closest('[data-migration-status]');if(!b)return;state.status=b.dataset.migrationStatus;clearSelection();$('#migrationStatusTabs').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));loadList()});let timer;$('#migrationSearch').addEventListener('input',e=>{state.search=e.target.value.trim();clearSelection();clearTimeout(timer);timer=setTimeout(loadList,250)});$('#migrationRefresh').onclick=()=>{clearSelection();loadList()};$('#migrationSortMenu').addEventListener('click',e=>{const b=e.target.closest('[data-migration-sort]');if(!b)return;state.sort=b.dataset.migrationSort;renderList();$('#migrationSortControl').open=false});$('#migrationSelectAll').addEventListener('change',e=>{const ids=sortMigrationListItems(state.items).map(x=>Number(x.id));if(e.target.checked)ids.forEach(id=>state.selected.add(id));else ids.forEach(id=>state.selected.delete(id));renderSelectionState()});$('#migrationSelectionClear').onclick=clearSelection;$('#migrationBulkStatus').addEventListener('change',e=>{state.bulkStatus=e.target.value;renderSelectionState()});$('#migrationBulkApply').onclick=applyBulkStatus;$('#migrationRows').addEventListener('change',e=>{const input=e.target.closest('[data-migration-select]');if(!input)return;const id=Number(input.value);if(input.checked)state.selected.add(id);else state.selected.delete(id);renderSelectionState()});$('#migrationRows').addEventListener('click',e=>{if(e.target.closest('[data-migration-select]'))return;const row=e.target.closest('[data-migration-id]');if(row){clearSelection();openDetail(Number(row.dataset.migrationId))}});$('#migrationCards').addEventListener('change',e=>{const input=e.target.closest('[data-migration-select]');if(!input)return;const id=Number(input.value);if(input.checked)state.selected.add(id);else state.selected.delete(id);renderSelectionState()});$('#migrationCards').addEventListener('click',e=>{if(e.target.closest('.migration-card-select'))return;const row=e.target.closest('[data-migration-id]');if(row){clearSelection();openDetail(Number(row.dataset.migrationId))}});$('#migrationExcelExport').onclick=exportExcel;$('#migrationImportTemplate').onclick=downloadImportTemplate;$('#migrationExcelImport').onclick=openImport;$('#migrationImageDownload').onclick=imageDownload;$('#migrationDeletedOpen').onclick=loadDeleted;syncImportAccess();renderSortMenu();renderSelectionState();document.querySelectorAll('[data-migration-image-close]').forEach(b=>b.onclick=closeImage);document.querySelector('[data-panel="migrationPanel"]')?.addEventListener('click',()=>loadList());window.addEventListener('ezpk-admin-ready',()=>{setTimeout(()=>{$('#migrationDeletedOpen').hidden=!isSuper();syncImportAccess();if(window.EZPKAdminAccess?.has?.('migration'))loadList()},0)});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();
