(function(){'use strict';
const q=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let votes=[];
async function api(url,opt={}){const r=await fetch(url,{credentials:'include',headers:{'content-type':'application/json',...(opt.headers||{})},...opt});const p=await r.json().catch(()=>({}));if(!r.ok||!p.ok)throw new Error(p.error||'REQUEST_FAILED');return p.data}
function emptyVote(){return{id:null,title:'',description:'',voteType:'single',startsAt:new Date().toISOString().slice(0,16),endsAt:'',showResults:false,options:[{label:'O',description:'참여 가능'},{label:'X',description:'참여 불가'}]}}
function renderEditor(v=emptyVote()){const el=q('#voteEditor');el.hidden=false;el.innerHTML=`<h3>${v.id?'투표 수정':'새 투표 만들기'}</h3><div class="vote-editor-grid"><label class="full">제목<input id="voteTitleInput" value="${esc(v.title)}" maxlength="120"></label><label class="full">설명<textarea id="voteDescriptionInput" rows="2" maxlength="400">${esc(v.description)}</textarea></label><label>선택 방식<select id="voteTypeInput"><option value="single" ${v.voteType==='single'?'selected':''}>단일 선택</option><option value="multiple" ${v.voteType==='multiple'?'selected':''}>다중 선택</option></select></label><label>결과 공개<select id="voteShowResultsInput"><option value="false" ${!v.showResults?'selected':''}>비공개</option><option value="true" ${v.showResults?'selected':''}>공개</option></select></label><label>시작 일시<input id="voteStartsInput" type="datetime-local" value="${localValue(v.startsAt)}"></label><label>종료 일시<input id="voteEndsInput" type="datetime-local" value="${localValue(v.endsAt)}"></label></div><h4>선택지</h4><div id="voteOptionEditor">${(v.options||[]).map((o,i)=>optionRow(o,i)).join('')}</div><div class="vote-editor-actions"><button id="addVoteOption" type="button">+ 선택지 추가</button><button id="saveVote" class="primary" type="button">저장</button><button id="cancelVoteEdit" class="secondary" type="button">취소</button></div>`;bindEditor(v.id)}
function localValue(x){if(!x)return'';const d=new Date(x);if(Number.isNaN(d))return String(x).slice(0,16);const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,16)}
function optionRow(o={},i=0){return `<div class="vote-option-editor" data-vote-option><input data-label placeholder="선택지" value="${esc(o.label||'')}"><input data-description placeholder="설명 (선택)" value="${esc(o.description||'')}"><button type="button" data-remove-option>삭제</button></div>`}
function bindEditor(id){q('#addVoteOption').onclick=()=>{const box=q('#voteOptionEditor');box.insertAdjacentHTML('beforeend',optionRow({},box.children.length));bindRemoves()};q('#cancelVoteEdit').onclick=()=>q('#voteEditor').hidden=true;q('#saveVote').onclick=()=>save(id);bindRemoves()}
function bindRemoves(){document.querySelectorAll('[data-remove-option]').forEach(b=>b.onclick=()=>{if(document.querySelectorAll('[data-vote-option]').length<=2)return alert('선택지는 최소 2개가 필요합니다.');b.closest('[data-vote-option]').remove()})}
async function save(id){const options=[...document.querySelectorAll('[data-vote-option]')].map(r=>({label:r.querySelector('[data-label]').value.trim(),description:r.querySelector('[data-description]').value.trim()})).filter(x=>x.label);const body={title:q('#voteTitleInput').value.trim(),description:q('#voteDescriptionInput').value.trim(),voteType:q('#voteTypeInput').value,showResults:q('#voteShowResultsInput').value==='true',startsAt:q('#voteStartsInput').value?new Date(q('#voteStartsInput').value).toISOString():null,endsAt:q('#voteEndsInput').value?new Date(q('#voteEndsInput').value).toISOString():null,options};if(!body.title||options.length<2)return alert('제목과 선택지 2개 이상을 입력하세요.');await api(id?`/api/admin/votes/${id}`:'/api/admin/votes',{method:id?'PUT':'POST',body:JSON.stringify(body)});q('#voteEditor').hidden=true;await load()}
async function load(){try{const d=await api('/api/admin/votes');votes=d.votes||[];render(votes,d.summary||{})}catch(e){q('#voteAdminList').innerHTML=`<div class="vote-admin-empty">VOTE 데이터를 불러오지 못했습니다.</div>`}}
function render(list,summary){q('#voteActiveCount').textContent=summary.active||0;q('#voteEndedCount').textContent=summary.ended||0;q('#voteMissingCount').textContent=summary.currentMissing||0;q('#voteRiskCount').textContent=summary.risk||0;const box=q('#voteAdminList');if(!list.length){box.innerHTML='<div class="vote-admin-empty">현재 진행 중인 투표가 없습니다.</div>';return}box.innerHTML=list.map(v=>`<article class="vote-admin-card"><header><div><h3>${esc(v.title)}</h3><p>${esc(v.description||'')}</p></div><span class="vote-badge ${v.status==='active'?'active':''}">${v.status==='active'?'진행 중':v.status==='ended'?'종료':'예정'}</span></header><div class="vote-card-actions"><button data-results="${v.id}">결과 보기</button><button data-edit="${v.id}">수정</button>${v.status!=='ended'?`<button class="primary" data-end="${v.id}">투표 종료</button>`:''}<button class="danger" data-delete="${v.id}">삭제</button></div></article>`).join('');box.querySelectorAll('[data-results]').forEach(b=>b.onclick=()=>showResults(Number(b.dataset.results)));box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>renderEditor(votes.find(v=>v.id===Number(b.dataset.edit))));box.querySelectorAll('[data-end]').forEach(b=>b.onclick=()=>endVote(Number(b.dataset.end)));box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeVote(Number(b.dataset.delete)))}
async function endVote(id){if(!confirm('투표를 종료하면 현재 미투표 기록이 확정됩니다. 종료할까요?'))return;await api(`/api/admin/votes/${id}/end`,{method:'POST',body:'{}'});await load();await showResults(id)}
async function removeVote(id){if(!confirm('이 투표와 응답 기록을 삭제할까요?'))return;await api(`/api/admin/votes/${id}`,{method:'DELETE'});await load()}
async function showResults(id){const d=await api(`/api/admin/votes/${id}/results`),el=q('#voteResultPanel');el.hidden=false;el.innerHTML=`<h3>${esc(d.vote.title)}</h3><div class="vote-result-tabs"><button data-vtab="answers" class="primary">투표 결과</button><button data-vtab="missing">현재 미투표</button><button data-vtab="streak">연속 미투표</button></div><div id="voteResultBody"></div>`;const renderTab=name=>{const body=q('#voteResultBody');if(name==='answers')body.innerHTML=(d.options||[]).map(o=>`<section class="vote-option-group"><h4>${esc(o.label)} ${esc(o.description||'')} · ${o.members.length}명</h4>${table(o.members,true)}</section>`).join('')||'<p>응답이 없습니다.</p>';if(name==='missing')body.innerHTML=table(d.missing||[],false);if(name==='streak')body.innerHTML=`<div class="vote-result-tabs"><button data-streak="0">전체</button><button data-streak="1">1회 이상</button><button data-streak="2">2회 이상</button><button data-streak="3" class="danger">3회 이상</button></div><div id="voteStreakTable">${table(d.streaks||[],false)}</div>`;el.querySelectorAll('[data-vtab]').forEach(b=>b.onclick=()=>renderTab(b.dataset.vtab));el.querySelectorAll('[data-streak]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.streak);q('#voteStreakTable').innerHTML=table((d.streaks||[]).filter(x=>x.consecutiveMissedVotes>=n),false);bindExclusions(id)});bindExclusions(id)};renderTab('answers')}
function bindExclusions(voteId){document.querySelectorAll('[data-exclude-member]').forEach(b=>b.onclick=async()=>{const memberId=Number(b.dataset.excludeMember),excluded=b.dataset.excluded!=='1';await api(`/api/admin/votes/exclusions/${memberId}`,{method:'PUT',body:JSON.stringify({excluded})});await showResults(voteId);await load()})}
function table(rows,withTime){if(!rows.length)return'<p>명단이 없습니다.</p>';return `<table class="vote-result-table"><thead><tr><th>닉네임</th><th>회원등급</th>${withTime?'<th>투표시간</th>':'<th>연속 미투표</th>'}<th>집계</th></tr></thead><tbody>${rows.map(m=>`<tr class="${m.excluded?'vote-excluded':''}"><td>${esc(m.nickname)}</td><td>${esc(m.memberRank||'')}</td><td>${withTime?esc(m.updatedAt?new Date(m.updatedAt).toLocaleString():''):Number(m.consecutiveMissedVotes||0)+'회'}</td><td><button data-exclude-member="${m.id}" data-excluded="${m.excluded?'1':'0'}">${m.excluded?'제외 해제':'집계 제외'}</button></td></tr>`).join('')}</tbody></table>`}
q('#newVoteButton')?.addEventListener('click',()=>renderEditor());window.addEventListener('ezpk-admin-ready',load);})();