const LANGS={
ko:{flag:'🇰🇷',name:'한국어',dir:'ltr',ui:{lineup:'팀 편성',members:'멤버 목록',strategy:'세부 전략',orders:'공통 지침',season7:'Season 7 정보',lead:'BGB 전장 위치와 각 위치별 담당 연맹원을 확인하세요.',mapTitle:'BGB 전장 지도',mapHelp:'지도에서 R1~R6, M1~M2, H1~H2, CENTER 위치를 확인하세요.',pinch:'모바일에서는 두 손가락으로 확대해 확인하세요.',locationTitle:'장소 명칭 안내',locationLead:'지도에 표시된 코드와 실제 시설 명칭입니다.',assignmentTitle:'위치별 담당 멤버',assignmentLead:'각 항목을 눌러 담당 멤버를 펼치거나 접을 수 있습니다.',none:'배정된 멤버가 없습니다.',updated:'마지막 업데이트',footer:'각자의 위치를 확인하고 함께 승리하세요!'}},
en:{flag:'🇺🇸',name:'English',dir:'ltr',ui:{lineup:'Team Lineup',members:'Members',strategy:'Strategy',orders:'Common Orders',season7:'Season 7 Info',lead:'Check the BGB battlefield locations and the alliance members assigned to each position.',mapTitle:'BGB Battlefield Map',mapHelp:'Use the map to identify R1–R6, M1–M2, H1–H2 and CENTER.',pinch:'Pinch to zoom on mobile.',locationTitle:'Location Information',locationLead:'Map codes and their full facility names.',assignmentTitle:'Assigned Members by Location',assignmentLead:'Select a location to expand or collapse its assigned member list.',none:'No members assigned.',updated:'Last Updated',footer:'Know your position, trust your team, and win together!'}},
pt:{flag:'🇧🇷',name:'Português',dir:'ltr',ui:{lineup:'Equipes',members:'Membros',strategy:'Estratégia',orders:'Ordens Comuns',season7:'Temporada 7',lead:'Consulte os locais do campo BGB e os membros designados para cada posição.',mapTitle:'Mapa do Campo BGB',mapHelp:'Localize R1–R6, M1–M2, H1–H2 e CENTER.',pinch:'No celular, use dois dedos para ampliar.',locationTitle:'Informações dos Locais',locationLead:'Códigos do mapa e nomes completos das instalações.',assignmentTitle:'Membros por Local',assignmentLead:'Toque em um local para abrir ou fechar a lista.',none:'Nenhum membro designado.',updated:'Última atualização',footer:'Conheça sua posição e lutem juntos até a vitória!'}},
vi:{flag:'🇻🇳',name:'Tiếng Việt',dir:'ltr',ui:{lineup:'Đội hình',members:'Thành viên',strategy:'Chiến thuật',orders:'Mệnh lệnh chung',season7:'Thông tin Mùa 7',lead:'Xem vị trí chiến trường BGB và thành viên được phân công tại từng khu vực.',mapTitle:'Bản đồ Chiến trường BGB',mapHelp:'Xác định R1–R6, M1–M2, H1–H2 và CENTER trên bản đồ.',pinch:'Trên điện thoại, dùng hai ngón tay để phóng to.',locationTitle:'Thông tin Địa điểm',locationLead:'Mã bản đồ và tên đầy đủ của từng cơ sở.',assignmentTitle:'Thành viên theo Vị trí',assignmentLead:'Nhấn vào từng vị trí để mở hoặc thu gọn danh sách.',none:'Chưa có thành viên được phân công.',updated:'Cập nhật lần cuối',footer:'Nắm rõ vị trí, tin tưởng đồng đội và cùng chiến thắng!'}},
ar:{flag:'🇸🇦',name:'العربية',dir:'rtl',ui:{lineup:'التشكيلة',members:'الأعضاء',strategy:'الاستراتيجية',orders:'الأوامر المشتركة',season7:'معلومات الموسم 7',lead:'راجع مواقع ساحة BGB وأعضاء التحالف المكلّفين بكل موقع.',mapTitle:'خريطة ساحة BGB',mapHelp:'حدّد مواقع R1–R6 وM1–M2 وH1–H2 وCENTER.',pinch:'استخدم إصبعين للتكبير على الهاتف.',locationTitle:'معلومات المواقع',locationLead:'رموز الخريطة والأسماء الكاملة للمنشآت.',assignmentTitle:'الأعضاء المكلّفون حسب الموقع',assignmentLead:'اضغط على الموقع لفتح قائمة الأعضاء أو إغلاقها.',none:'لا يوجد أعضاء مكلّفون.',updated:'آخر تحديث',footer:'اعرف موقعك وثق بفريقك وانتصروا معًا!'}},
'zh-tw':{flag:'🇹🇼',name:'繁體中文',dir:'ltr',ui:{lineup:'隊伍編成',members:'成員名單',strategy:'詳細戰略',orders:'共同指令',season7:'第 7 賽季資訊',lead:'查看 BGB 戰場位置以及各位置的負責聯盟成員。',mapTitle:'BGB 戰場地圖',mapHelp:'在地圖上確認 R1–R6、M1–M2、H1–H2 與 CENTER。',pinch:'手機上可使用雙指縮放。',locationTitle:'地點名稱說明',locationLead:'地圖代碼與完整設施名稱。',assignmentTitle:'各位置負責成員',assignmentLead:'點擊位置即可展開或收合負責成員名單。',none:'尚未指派成員。',updated:'最後更新',footer:'確認自己的位置，彼此信任，一起獲勝！'}}
};
const LOCATIONS=[['R1','REFINERY 1'],['R2','REFINERY 2'],['R3','REFINERY 3'],['R4','REFINERY 4'],['R5','REFINERY 5'],['R6','REFINERY 6'],['M1','MILITARY BASE 1'],['M2','MILITARY BASE 2'],['H1','HOSPITAL 1'],['H2','HOSPITAL 2'],['CENTER','ALLOY FACTORY']];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let lang=localStorage.getItem('ezpk-lang-v5')||'en',members=[],bgb={lastUpdated:'',locations:{}};if(!LANGS[lang])lang='en';
async function load(){const [mr,br]=await Promise.all([fetch('../data/members.json?v='+Date.now(),{cache:'no-store'}),fetch('../data/bgb.json?v='+Date.now(),{cache:'no-store'})]);if(!mr.ok||!br.ok)throw new Error('Data load failed');const md=await mr.json();members=md.members||[];bgb=await br.json();render()}
function render(){const l=LANGS[lang],u=l.ui;document.documentElement.lang=lang;document.documentElement.dir=l.dir;document.body.classList.toggle('rtl',l.dir==='rtl');$('#flag').textContent=l.flag;$('#lname').textContent=l.name;$$('[data-k]').forEach(e=>e.textContent=u[e.dataset.k]||'');$('#lead').textContent=u.lead;$('#mapTitle').textContent=u.mapTitle;$('#mapHelp').textContent=u.mapHelp;$('#pinch').textContent=u.pinch;$('#locationTitle').textContent=u.locationTitle;$('#locationLead').textContent=u.locationLead;$('#assignmentTitle').textContent=u.assignmentTitle;$('#assignmentLead').textContent=u.assignmentLead;$('#updatedLabel').textContent=u.updated;$('#updatedDate').textContent=bgb.lastUpdated||'-';$('#footerText').textContent=u.footer;$('#locationLegend').innerHTML=LOCATIONS.map(([code,name])=>`<article class="legend-item"><span class="location-code">${code}</span><div><strong>${name}</strong><small>${code}</small></div></article>`).join('');$('#locationCards').innerHTML=LOCATIONS.map(([code,name])=>{const assigned=bgb.locations?.[code]||[];const items=assigned.map(n=>members.find(m=>m.nickname===n)||{nickname:n,rank:'',ind:'',power:''});return `<article class="location-card"><button class="location-toggle" type="button" aria-expanded="true"><span class="location-title"><span class="location-code">${code}</span><span><h3>${name}</h3><p>${code}</p></span></span><span class="location-meta"><span class="member-count">${items.length}</span><span class="chevron">⌃</span></span></button><div class="assigned-list">${items.length?items.map(m=>`<div class="assigned-member"><strong>${esc(m.nickname)}</strong><small>${esc(m.rank||'')} · IND. ${esc(m.ind??'-')} · ${Number(m.power||0).toLocaleString()}</small></div>`).join(''):`<div class="empty-assignment">${u.none}</div>`}</div></article>`}).join('');$$('.location-toggle').forEach(btn=>btn.onclick=()=>{const card=btn.closest('.location-card'),list=card.querySelector('.assigned-list'),open=btn.getAttribute('aria-expanded')==='true';btn.setAttribute('aria-expanded',String(!open));list.hidden=open;card.classList.toggle('collapsed',open)});localStorage.setItem('ezpk-lang-v5',lang)}
$('#langBtn').onclick=()=>$('#langMenu').hidden=!$('#langMenu').hidden;$$('#langMenu button').forEach(b=>b.onclick=()=>{lang=b.dataset.l;$('#langMenu').hidden=true;render()});$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');$$('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));load().catch(e=>{console.error(e);$('#locationCards').innerHTML='<div class="empty-assignment">Unable to load BGB data.</div>'});
