const T={
ko:{title:'EZPK 멤버',sortLabel:'정렬',lead:'등급별 닉네임, IND.와 전투력을 확인하세요.',total:'전체 인원',tp:'전체 전투력',avg:'평균 전투력',search:'닉네임 검색',all:'전체 등급',rank:'등급순',high:'전투력 높은 순',low:'전투력 낮은 순',level:'IND. 높은 순',name:'닉네임순',member:'명',shelter:'IND.',power:'전투력',empty:'검색 결과가 없습니다.',footer:'함께 싸우고, 함께 승리하자!',updated:'마지막 업데이트',loadError:'멤버 데이터를 불러오지 못했습니다.'},
en:{title:'EZPK MEMBERS',sortLabel:'Sort',lead:'View nicknames, IND. levels, and combat power by rank.',total:'Total Members',tp:'Total Power',avg:'Average Power',search:'Search nickname',all:'All Ranks',rank:'Rank Order',high:'Power: High to Low',low:'Power: Low to High',level:'IND. High to Low',name:'Nickname A–Z',member:'Members',shelter:'IND.',power:'Power',empty:'No members found.',footer:'Fight together, win together!',updated:'Last Updated',loadError:'Could not load member data.'},
pt:{title:'MEMBROS EZPK',sortLabel:'Ordenar',lead:'Veja apelidos, IND. e poder de combate por patente.',total:'Total de Membros',tp:'Poder Total',avg:'Poder Médio',search:'Buscar apelido',all:'Todas as Patentes',rank:'Ordem de Patente',high:'Maior Poder',low:'Menor Poder',level:'Maior IND.',name:'Apelido A–Z',member:'Membros',shelter:'IND.',power:'Poder',empty:'Nenhum membro encontrado.',footer:'Lutem juntos, vençam juntos!',updated:'Última atualização',loadError:'Não foi possível carregar os dados.'},
vi:{title:'THÀNH VIÊN EZPK',sortLabel:'Sắp xếp',lead:'Xem biệt danh, IND. và lực chiến theo cấp bậc.',total:'Tổng Thành Viên',tp:'Tổng Lực Chiến',avg:'Lực Chiến Trung Bình',search:'Tìm biệt danh',all:'Tất Cả Cấp Bậc',rank:'Theo Cấp Bậc',high:'Lực Chiến Cao → Thấp',low:'Lực Chiến Thấp → Cao',level:'IND. Cao → Thấp',name:'Biệt Danh A–Z',member:'Thành viên',shelter:'IND.',power:'Lực chiến',empty:'Không tìm thấy thành viên.',footer:'Cùng chiến đấu, cùng chiến thắng!',updated:'Cập nhật lần cuối',loadError:'Không thể tải dữ liệu thành viên.'},
ar:{title:'أعضاء EZPK',sortLabel:'الترتيب',lead:'اعرض الأسماء ومستويات IND. والقوة القتالية حسب الرتبة.',total:'إجمالي الأعضاء',tp:'إجمالي القوة',avg:'متوسط القوة',search:'ابحث عن اسم',all:'كل الرتب',rank:'ترتيب الرتبة',high:'القوة: من الأعلى',low:'القوة: من الأقل',level:'IND. من الأعلى',name:'الاسم أ–ي',member:'أعضاء',shelter:'IND.',power:'القوة',empty:'لم يتم العثور على أعضاء.',footer:'قاتلوا معًا وانتصروا معًا!',updated:'آخر تحديث',loadError:'تعذر تحميل بيانات الأعضاء.'},
ja:{title:'EZPK メンバー',sortLabel:'並び替え',lead:'ランク別のニックネーム、IND.、戦闘力を確認できます。',total:'総メンバー数',tp:'総戦闘力',avg:'平均戦闘力',search:'ニックネーム検索',all:'すべてのランク',rank:'ランク順',high:'戦闘力：高い順',low:'戦闘力：低い順',level:'IND.：高い順',name:'ニックネーム順',member:'名',shelter:'IND.',power:'戦闘力',empty:'メンバーが見つかりません。',footer:'共に戦い、共に勝利しよう！',updated:'最終更新',loadError:'メンバーデータを読み込めませんでした。'},
'zh-tw':{title:'EZPK 成員',sortLabel:'排序',lead:'依階級查看暱稱、IND. 與戰力。',total:'總成員數',tp:'總戰力',avg:'平均戰力',search:'搜尋暱稱',all:'全部階級',rank:'階級順序',high:'戰力：高至低',low:'戰力：低至高',level:'IND.：高至低',name:'暱稱 A–Z',member:'成員',shelter:'IND.',power:'戰力',empty:'找不到成員。',footer:'攜手作戰，共同取勝！',download:'下載 Excel',excelError:'無法載入 Excel 功能。',updated:'最後更新',loadError:'無法載入成員資料。'}};
const ROLES={R5:'Leader',R4:'Officer',R3:'Core',R2:'Support',R1:'Reserve'},ORDER={R5:5,R4:4,R3:3,R2:2,R1:1};
let MEMBERS=[],visibleMembers=[],LAST_UPDATED='-';
let lang=localStorage.getItem('ezpk-lang-v5')||'en'; if(!window.EZPK_DATA[lang])lang='en';
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),fmt=n=>new Intl.NumberFormat('en-US').format(n),compact=n=>new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:2}).format(n),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function ui(){const c=window.EZPK_DATA[lang],t=T[lang];document.documentElement.lang=lang;document.documentElement.dir=c.dir;document.body.classList.toggle('rtl',c.dir==='rtl');$('#flag').textContent=c.flag;$('#lname').textContent=c.name;$$('[data-k]').forEach(e=>{if(c.ui[e.dataset.k]!=null)e.textContent=c.ui[e.dataset.k]});$('#membersTitle').textContent=t.title;$('#membersLead').textContent=t.lead;$('#totalLabel').textContent=t.total;$('#totalPowerLabel').textContent=t.tp;$('#avgPowerLabel').textContent=t.avg;$('#memberSearch').placeholder=t.search;$('#rankFilter').innerHTML=`<option value="ALL">${t.all}</option>${['R5','R4','R3','R2','R1'].map(r=>`<option value="${r}">${r} · ${ROLES[r]}</option>`).join('')}`;$('#mobileSortLabel').textContent=t.sortLabel;$('#sortMembers').innerHTML=`<option value="rank">${t.rank}</option><option value="high">${t.high}</option><option value="low">${t.low}</option><option value="level">${t.level}</option><option value="name">${t.name}</option>`;$('#emptyState').textContent=t.empty;$('#memberFooter').textContent=t.footer;$('#updatedLabel').textContent=t.updated;$('#updatedDate').textContent=LAST_UPDATED+' KST';updateSummary();localStorage.setItem('ezpk-lang-v5',lang);render()}
function updateSummary(){const sum=MEMBERS.reduce((a,m)=>a+m.power,0);$('#totalMembers').textContent=MEMBERS.length;$('#totalPower').textContent=compact(sum);$('#avgPower').textContent=MEMBERS.length?compact(Math.round(sum/MEMBERS.length)):'0'}
function render(){const t=T[lang],isMobile=window.matchMedia('(max-width:620px)').matches;if(isMobile){$('#memberSearch').value='';$('#rankFilter').value='ALL';}const q=$('#memberSearch').value.trim().toLocaleLowerCase(),rf=isMobile?'ALL':$('#rankFilter').value,sort=$('#sortMembers').value;let list=MEMBERS.filter(m=>(rf==='ALL'||m.rank===rf)&&m.nickname.toLocaleLowerCase().includes(q));list=[...list].sort((a,b)=>sort==='high'?b.power-a.power:sort==='low'?a.power-b.power:sort==='level'?(b.ind-a.ind||b.power-a.power):sort==='name'?a.nickname.localeCompare(b.nickname):(ORDER[b.rank]-ORDER[a.rank]||b.power-a.power));visibleMembers=list;const groups=['R5','R4','R3','R2','R1'].map(r=>{const arr=list.filter(m=>m.rank===r);if(!arr.length)return'';return `<section class="rank-group"><button class="rank-head" aria-expanded="true"><div class="rank-title"><span class="rank-badge">${r}</span><div><h2>${ROLES[r]}</h2><small>${r}</small></div></div><div class="rank-count"><strong>${arr.length}</strong><span class="label">${t.member}</span><span class="rank-arrow">⌃</span></div></button><div class="rank-list">${arr.map((m,i)=>`<article class="member-card"><div class="member-index">${String(i+1).padStart(2,'0')}</div><div><h3 class="member-name">${esc(m.nickname)}</h3><div class="member-meta"><span>${t.shelter} <b>${m.ind}</b></span><span>${t.power} <b>${fmt(m.power)}</b></span></div></div><div class="power-chip">${compact(m.power)}</div></article>`).join('')}</div></section>`}).join('');$('#memberGroups').innerHTML=groups;$('#emptyState').hidden=!!list.length;$$('.rank-head').forEach(b=>b.onclick=()=>{const g=b.closest('.rank-group'),l=g.querySelector('.rank-list'),open=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',String(!open));l.hidden=open;g.classList.toggle('collapsed',open)})}
async function loadMembers(){try{const res=await fetch('../data/members.json?v=81',{cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);const data=await res.json();MEMBERS=Array.isArray(data.members)?data.members:[];LAST_UPDATED=data.lastUpdated||'-';visibleMembers=[...MEMBERS];ui()}catch(err){console.error(err);$('#memberGroups').innerHTML=`<div class="empty-state">${T[lang].loadError}</div>`}}
$('#langBtn').onclick=()=>$('#langMenu').hidden=!$('#langMenu').hidden;$$('#langMenu button').forEach(b=>b.onclick=()=>{lang=b.dataset.l;$('#langMenu').hidden=true;ui()});$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');$$('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));$('#memberSearch').oninput=render;$('#rankFilter').onchange=render;$('#sortMembers').onchange=render;window.addEventListener('resize',render);loadMembers();
