const T={
ko:{title:"연맹원 명단",lead:"티어별 전력과 상세 정보를 확인하세요.",total:"전체 인원",tp:"전체 전투력",avg:"평균 전투력",search:"닉네임 검색",all:"전체 등급",sortLabel:"정렬",v1:"차량1 높은 순",v2:"차량2 높은 순",high:"전투력 높은 순",level:"산업 레벨 높은 순",rank:"등급 높은 순",name:"닉네임 순",unregistered:"미등록",specsRequired:"세부 스펙 필요",member:"명",industry:"산업 레벨",power:"전투력",empty:"검색 결과가 없습니다.",footer:"함께 싸우고, 함께 승리하자!",loadError:"멤버 데이터를 불러오지 못했습니다.",legacyLead:"등급별 닉네임, 산업 레벨과 전투력을 확인하세요.",me:"나"},
en:{title:"ALLIANCE MEMBERS",lead:"View power and detailed information by tier.",total:"Total Members",tp:"Total Power",avg:"Average Power",search:"Search nickname",all:"All Ranks",sortLabel:"Sort",v1:"Vehicle #1 Power ↓",v2:"Vehicle #2 Power ↓",high:"CP ↓",level:"Industry Level ↓",rank:"Alliance Rank ↓",name:"Nickname A–Z",unregistered:"Not Set",specsRequired:"Specs Required",member:"Members",industry:"Industry Level",power:"CP",empty:"No members found.",footer:"Fight together, win together!",loadError:"Could not load member data.",legacyLead:"View nicknames, industry levels, and CP by alliance rank.",me:"ME"},
pt:{title:"MEMBROS DA ALIANÇA",lead:"Veja o poder e os detalhes por nível.",total:"Total de Membros",tp:"Poder Total",avg:"Poder Médio",search:"Pesquisar apelido",all:"Todas as Patentes",sortLabel:"Ordenar",v1:"Poder do Veículo 1 ↓",v2:"Poder do Veículo 2 ↓",high:"CP ↓",level:"Nível Industrial ↓",rank:"Patente da Aliança ↓",name:"Apelido A–Z",unregistered:"Não registrado",specsRequired:"Especificações necessárias",member:"Membros",industry:"Nível Industrial",power:"CP",empty:"Nenhum membro encontrado.",footer:"Lutem juntos, vençam juntos!",loadError:"Não foi possível carregar os dados.",legacyLead:"Veja apelidos, níveis industriais e CP por patente.",me:"EU"},
vi:{title:"THÀNH VIÊN LIÊN MINH",lead:"Xem sức mạnh và thông tin chi tiết theo bậc.",total:"Tổng Thành Viên",tp:"Tổng Lực Chiến",avg:"Lực Chiến Trung Bình",search:"Tìm kiếm biệt danh",all:"Tất Cả Cấp Bậc",sortLabel:"Sắp xếp",v1:"Sức mạnh Xe 1 ↓",v2:"Sức mạnh Xe 2 ↓",high:"CP ↓",level:"Cấp Công Nghiệp ↓",rank:"Cấp Liên Minh ↓",name:"Biệt Danh A–Z",unregistered:"Chưa đăng ký",specsRequired:"Cần thông số",member:"Thành viên",industry:"Cấp Công Nghiệp",power:"CP",empty:"Không tìm thấy thành viên.",footer:"Cùng chiến đấu, cùng chiến thắng!",loadError:"Không thể tải dữ liệu thành viên.",legacyLead:"Xem biệt danh, cấp công nghiệp và CP theo cấp liên minh.",me:"Tôi"},
ar:{title:"أعضاء التحالف",lead:"اعرض القوة والمعلومات التفصيلية حسب الفئة.",total:"إجمالي الأعضاء",tp:"إجمالي القوة",avg:"متوسط القوة",search:"البحث عن الاسم المستعار",all:"كل الرتب",sortLabel:"الترتيب",v1:"قوة المركبة 1 ↓",v2:"قوة المركبة 2 ↓",high:"CP ↓",level:"المستوى الصناعي ↓",rank:"رتبة التحالف ↓",name:"الاسم أ–ي",unregistered:"غير مسجل",specsRequired:"المواصفات مطلوبة",member:"أعضاء",industry:"المستوى الصناعي",power:"CP",empty:"لم يتم العثور على أعضاء.",footer:"قاتلوا معًا وانتصروا معًا!",loadError:"تعذر تحميل بيانات الأعضاء.",legacyLead:"اعرض الأسماء والمستوى الصناعي وCP حسب رتبة التحالف.",me:"أنا"},
ja:{title:"同盟メンバー一覧",lead:"ティア別の戦力と詳細情報を確認できます。",total:"総メンバー数",tp:"総戦闘力",avg:"平均戦闘力",search:"ニックネーム検索",all:"すべてのランク",sortLabel:"並び替え",v1:"車両1戦力の高い順",v2:"車両2戦力の高い順",high:"CPの高い順",level:"産業レベルの高い順",rank:"同盟ランクの高い順",name:"ニックネーム順",unregistered:"未登録",specsRequired:"スペック登録が必要",member:"名",industry:"産業レベル",power:"CP",empty:"メンバーが見つかりません。",footer:"共に戦い、共に勝利しよう！",loadError:"メンバーデータを読み込めませんでした。",legacyLead:"同盟ランク別のニックネーム、産業レベル、CPを確認できます。",me:"自分"},
"zh-tw":{title:"聯盟成員名單",lead:"查看各階級的戰力與詳細資訊。",total:"總成員數",tp:"總戰力",avg:"平均戰力",search:"搜尋暱稱",all:"全部階級",sortLabel:"排序",v1:"車輛1戰力由高至低",v2:"車輛2戰力由高至低",high:"CP由高至低",level:"產業等級由高至低",rank:"聯盟階級由高至低",name:"暱稱 A–Z",unregistered:"未登記",specsRequired:"需要詳細規格",member:"成員",industry:"產業等級",power:"CP",empty:"找不到成員。",footer:"攜手作戰，共同取勝！",loadError:"無法載入成員資料。",legacyLead:"依聯盟階級查看暱稱、產業等級與CP。",me:"我"},
th:{title:"รายชื่อสมาชิกพันธมิตร",lead:"ตรวจสอบพลังและข้อมูลโดยละเอียดตามเทียร์",total:"สมาชิกทั้งหมด",tp:"พลังรบรวม",avg:"พลังรบเฉลี่ย",search:"ค้นหาชื่อเล่น",all:"ทุกอันดับ",sortLabel:"เรียงลำดับ",v1:"พลังรถ 1 สูงสุด",v2:"พลังรถ 2 สูงสุด",high:"CP สูงสุด",level:"ระดับอุตสาหกรรมสูงสุด",rank:"อันดับพันธมิตรสูงสุด",name:"ชื่อเล่น A–Z",unregistered:"ยังไม่ลงทะเบียน",specsRequired:"ต้องลงทะเบียนสเปก",member:"คน",industry:"ระดับอุตสาหกรรม",power:"CP",empty:"ไม่พบสมาชิก",footer:"สู้ไปด้วยกันและชนะไปด้วยกัน!",loadError:"ไม่สามารถโหลดข้อมูลสมาชิกได้",legacyLead:"ตรวจสอบชื่อเล่น ระดับอุตสาหกรรม และ CP ตามอันดับพันธมิตร",me:"ฉัน"}
};
const ROLES={R5:'Leader',R4:'Officer',R3:'Core',R2:'Support',R1:'Reserve'};
const RANK_ORDER={R5:5,R4:4,R3:3,R2:2,R1:1};
const TIER_ORDER=['SS','S','A','B','C','UNREGISTERED'];
let MEMBERS=[];let IS_LOGGED_IN=false;let MY_MEMBER_ID=0;let MY_NICKNAME="";
let lang=localStorage.getItem('ezpk-lang-v5')||'en';
if(!window.EZPK_DATA?.[lang]||!T[lang])lang='en';
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fullNumber=n=>new Intl.NumberFormat(lang==='en'?'en-US':lang).format(Number(n)||0);
function numberOrNull(value){if(value===null||value===undefined||value==='')return null;const n=Number(value);return Number.isFinite(n)&&n>0?n:null}
function industryNumber(value){if(value===null||value===undefined||value==='')return null;const n=Number(String(value).toUpperCase().replace(/^I/,''));return Number.isFinite(n)&&n>0?n:null}
function compactRaw(value){const n=numberOrNull(value);if(!n)return'-';const unit=n>=1e9?'G':n>=1e6?'M':'';const divisor=unit==='G'?1e9:unit==='M'?1e6:1;const rounded=Math.round((n/divisor)*10)/10;return `${Number.isInteger(rounded)?rounded:rounded.toFixed(1)}${unit}`}
function compactNormalized(value){const n=numberOrNull(value);if(!n)return'-';const amount=n>=1000?n/1000:n;const unit=n>=1000?'G':'M';const rounded=Math.round(amount*10)/10;return `${Number.isInteger(rounded)?rounded:rounded.toFixed(1)}${unit}`}
function vehicleIcon(type){return({fighter:'⚔️',shooter:'🎯',rider:'🏍️'})[String(type||'').toLowerCase()]||'🚙'}
function tierOf(m){const v=m.vehicle1Power;if(!v)return'UNREGISTERED';if(v>=8000)return'SS';if(v>=5000)return'S';if(v>=3000)return'A';if(v>=2000)return'B';return'C'}
function compareMissingLast(a,b){const am=a==null,bm=b==null;if(am!==bm)return am?1:-1;if(am&&bm)return 0;return b-a}
function sortMembers(list,sort){return [...list].sort((a,b)=>{if(sort==='v2')return compareMissingLast(a.vehicle2Power,b.vehicle2Power)||a.nickname.localeCompare(b.nickname,undefined,{sensitivity:'base'});if(sort==='cp')return compareMissingLast(a.power,b.power)||a.nickname.localeCompare(b.nickname,undefined,{sensitivity:'base'});if(sort==='industry')return compareMissingLast(a.ind,b.ind)||compareMissingLast(a.power,b.power)||a.nickname.localeCompare(b.nickname,undefined,{sensitivity:'base'});if(sort==='rank')return (RANK_ORDER[b.rank]||0)-(RANK_ORDER[a.rank]||0)||a.nickname.localeCompare(b.nickname,undefined,{sensitivity:'base'});if(sort==='name')return a.nickname.localeCompare(b.nickname,undefined,{sensitivity:'base'});return compareMissingLast(a.vehicle1Power,b.vehicle1Power)||compareMissingLast(a.vehicle2Power,b.vehicle2Power)||a.nickname.localeCompare(b.nickname,undefined,{sensitivity:'base'});})}
function updateSummary(){const withPower=MEMBERS.filter(m=>m.power);const sum=withPower.reduce((acc,m)=>acc+m.power,0);$('#totalMembers').textContent=fullNumber(MEMBERS.length);$('#totalPower').textContent=fullNumber(sum);$('#avgPower').textContent=withPower.length?fullNumber(Math.round(sum/withPower.length)):'0'}
function applyUi(){const c=window.EZPK_DATA[lang],t=T[lang];document.documentElement.lang=lang;document.documentElement.dir=c.dir;document.body.classList.toggle('rtl',c.dir==='rtl');document.body.classList.toggle('tier-mode',IS_LOGGED_IN);document.body.classList.toggle('legacy-mode',!IS_LOGGED_IN);if($('#flag'))$('#flag').textContent=c.flag;if($('#lname'))$('#lname').textContent=c.name;$$('[data-k]').forEach(e=>{if(c.ui[e.dataset.k]!=null)e.textContent=c.ui[e.dataset.k]});$('#membersTitle').textContent=t.title;$('#membersLead').textContent=IS_LOGGED_IN?t.lead:t.legacyLead;$('#totalLabel').textContent=t.total;$('#totalPowerLabel').textContent=t.tp;$('#avgPowerLabel').textContent=t.avg;$('#memberSearch').placeholder=t.search;$('#sortLabel').textContent=t.sortLabel;$('#rankFilter').innerHTML=`<option value="ALL">${t.all}</option>${['R5','R4','R3','R2','R1'].map(r=>`<option value="${r}">${r} · ${ROLES[r]}</option>`).join('')}`;$('#sortMembers').innerHTML=IS_LOGGED_IN?`<option value="v1">${t.v1}</option><option value="v2">${t.v2}</option><option value="cp">${t.high}</option><option value="industry">${t.level}</option><option value="rank">${t.rank}</option><option value="name">${t.name}</option>`:`<option value="cp">${t.high}</option><option value="industry">${t.level}</option><option value="rank">${t.rank}</option><option value="name">${t.name}</option>`;$('#emptyState').textContent=t.empty;$('#memberFooter').textContent=t.footer;$('#vehicleLegend').hidden=!IS_LOGGED_IN;updateSummary();localStorage.setItem('ezpk-lang-v5',lang);render()}
function tierCard(m){const tier=tierOf(m);const tierLabel=tier==='UNREGISTERED'?T[lang].unregistered:tier;const v1=`${vehicleIcon(m.vehicle1Class)} ${compactNormalized(m.vehicle1Power)}`;const v2=`${vehicleIcon(m.vehicle2Class)} ${compactNormalized(m.vehicle2Power)}`;const isMine=IS_LOGGED_IN&&((MY_MEMBER_ID>0&&m.id===MY_MEMBER_ID)||(!MY_MEMBER_ID&&MY_NICKNAME&&m.nickname.toLocaleLowerCase()===MY_NICKNAME.toLocaleLowerCase()));const mineMarker=isMine?`<span class="my-card-marker" aria-label="${esc(T[lang].me)}"><i aria-hidden="true"></i><b>${esc(T[lang].me)}</b></span>`:'';return `<article class="tier-card tier-card-${tier.toLowerCase()}${isMine?' is-my-card':''}"${isMine?' data-my-card="true"':''}><div class="card-top"><span class="tier-badge">${esc(tierLabel)}</span><span class="card-rank-column"><span class="alliance-rank">${esc(m.rank)}</span>${mineMarker}</span></div><h3 class="member-name" title="${esc(m.nickname)}">${esc(m.nickname)}</h3><div class="tier-stats"><span>${v1}</span><span>${v2}</span><span>🏭 ${m.ind?`Lv.${m.ind}`:'-'}</span><span>CP ${compactRaw(m.power)}</span></div></article>`}
function renderTier(list){const t=T[lang];return TIER_ORDER.map(tier=>{const arr=sortMembers(list.filter(m=>tierOf(m)===tier),$('#sortMembers').value);if(!arr.length)return'';const title=tier==='UNREGISTERED'?t.unregistered:tier;const subtitle=tier==='UNREGISTERED'?t.specsRequired:'';return `<section class="tier-group tier-${tier.toLowerCase()}"><header class="tier-head"><div><h2>${esc(title)}</h2>${subtitle?`<small>${esc(subtitle)}</small>`:''}</div><span>${arr.length} ${t.member}</span></header><div class="tier-grid">${arr.map(tierCard).join('')}</div></section>`}).join('')}
function renderLegacy(list){const t=T[lang];return ['R5','R4','R3','R2','R1'].map(rank=>{const arr=sortMembers(list.filter(m=>m.rank===rank),$('#sortMembers').value);if(!arr.length)return'';return `<section class="rank-group rank-${rank.toLowerCase()}"><button class="rank-head" aria-expanded="true"><div class="rank-title"><span class="rank-badge">${rank}</span><div><h2>${ROLES[rank]}</h2><small>${rank}</small></div></div><div class="rank-count"><strong>${arr.length}</strong><span class="label">${t.member}</span><span class="rank-arrow">⌃</span></div></button><div class="rank-list">${arr.map((m,i)=>`<article class="member-card"><div class="member-index">${String(i+1).padStart(2,'0')}</div><div><h3 class="member-name">${esc(m.nickname)}</h3><div class="member-meta"><span>${t.industry} <b>${m.ind?`Lv.${m.ind}`:'-'}</b></span><i>/</i><span>${t.power} <b>${m.power?fullNumber(m.power):'-'}</b></span></div></div></article>`).join('')}</div></section>`}).join('')}
function render(){const q=$('#memberSearch').value.trim().toLocaleLowerCase();const rank=$('#rankFilter').value||'ALL';let list=MEMBERS.filter(m=>m.nickname.toLocaleLowerCase().includes(q));if(!IS_LOGGED_IN&&rank!=='ALL')list=list.filter(m=>m.rank===rank);const html=IS_LOGGED_IN?renderTier(list):renderLegacy(list);$('#memberGroups').innerHTML=html;$('#emptyState').hidden=Boolean(list.length);$$('.rank-head').forEach(button=>button.onclick=()=>{const group=button.closest('.rank-group'),target=group.querySelector('.rank-list'),open=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!open));target.hidden=open;group.classList.toggle('collapsed',open)})}
function mapApiMember(item){return{id:Number(item?.id)||0,rank:String(item?.memberRank||'R1').toUpperCase(),nickname:String(item?.nickname||''),ind:industryNumber(item?.industryLevel),power:numberOrNull(item?.power),vehicle1Class:item?.vehicle1Class||null,vehicle1Power:numberOrNull(item?.vehicle1PowerNormalized),vehicle2Class:item?.vehicle2Class||null,vehicle2Power:numberOrNull(item?.vehicle2PowerNormalized)}}
async function checkLogin(){MY_MEMBER_ID=0;MY_NICKNAME="";try{const res=await fetch('/api/member/me',{cache:'no-store',credentials:'include',headers:{accept:'application/json'}});IS_LOGGED_IN=res.ok;if(!res.ok)return;const payload=await res.json();const me=payload?.data?.member||null;MY_MEMBER_ID=Number(me?.id)||0;MY_NICKNAME=String(me?.nickname||"").trim()}catch(_){IS_LOGGED_IN=false;MY_MEMBER_ID=0;MY_NICKNAME=""}}
async function fetchMemberPage(page){const res=await fetch(`/api/members?page=${page}&limit=100&sort=power_desc`,{cache:'no-store',credentials:'include',headers:{accept:'application/json'}});if(!res.ok)throw new Error(`HTTP ${res.status}`);const payload=await res.json();if(!payload?.ok)throw new Error(payload?.code||'MEMBER_API_ERROR');return payload.data||{}}
async function loadMembers(){try{await checkLogin();const first=await fetchMemberPage(1);const pages=Math.max(1,Number(first.pagination?.totalPages||0));let items=Array.isArray(first.items)?[...first.items]:[];if(pages>1){const rest=await Promise.all(Array.from({length:pages-1},(_,i)=>fetchMemberPage(i+2)));rest.forEach(p=>{if(Array.isArray(p.items))items.push(...p.items)})}MEMBERS=items.map(mapApiMember).filter(m=>m.nickname&&RANK_ORDER[m.rank]);applyUi()}catch(err){console.error(err);MEMBERS=[];updateSummary();$('#memberGroups').innerHTML=`<div class="empty-state">${T[lang].loadError}</div>`;$('#emptyState').hidden=true}}
window.addEventListener('ezpk-language-change',event=>{const next=event.detail?.lang||localStorage.getItem('ezpk-lang-v5')||'en';lang=T[next]?next:'en';applyUi()});
$('#memberSearch').addEventListener('input',render);$('#rankFilter').addEventListener('change',render);$('#sortMembers').addEventListener('change',render);loadMembers();
